### ISSUE TITLE
[Enabler] [zos_script] Deprecate the use of tmp_path in lieu of the engines/ssh.py remote_tmp var. 

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1024]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

This issue is in place so that we remove the the **tmp_path** option currently in the **zos_script** module that allows users to specify where the scripts will be written to on the remote node for execution and instead leverage the one that ansible users which is [remote_tmp](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/sh_shell.html#parameter-remote_tmp) that is part of the ssh connection. 

There are some draw backs to this approach which is we have to extract this value from the engine, the good news is we have already taken control of the ssh connection in our copy module, so we have examples, it should not be too difficult to figure out how to obtain access to that value if we look at the zos_copy plugin or zos_fetch plugin source.

The other draw back is this adds more overhead and tighter coupling with the communities code and means we have to be more diligent in testing ansible-core releases before they GA as we have seen in the past playcontext warnings and variables deprecated. 

See conversation [here](https://github.com/ansible-collections/ibm_zos_core/pull/961/files#r1346820457) for more context.

**Comment by rexemin** [comment]
If we go ahead with this item, we would need to do a couple of things:
1. Access `remote_tmp` from the playbook context and instead use that value when calling `tempfile` inside the action plugin for `zos_script`.
2. Change the module documentation to reflect this behavior so users are aware how they need to configure their environments to change their temp path correctly.
3. Test that `zos_script` works properly after this change (I don't really expect this change to break anything or be cumbersome, but you never know).

Just want to reiterate that this change would make any changes to the temp path global for a given playbook or role, instead of doing it on the task level.

**Comment by ddimatos** [comment]
Sharing my thoughts and snippets, oddly I was also updating this issue at the same time :). 

When reviewing what other **plugins** are doing they tend to rely on the [remote_tmp](https://docs.ansible.com/ansible/latest/collections/environment_variables.html#envvar-ANSIBLE_REMOTE_TMP) , `remote_tmp` is [documented](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/sh_shell.html#parameter-remote_tmp) as part of the plugin spec (below) but given `zos_script` is a module, we could not document the same, we could at best speak to it as part of the description and docs because documented options in a module will fail sanity testing when the option is not configured in the module but instead (globally) in the `ini` , `env var` or as a playbook var. 

Those plugins are:
- [ansible.builtin.sh shell plugin](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/sh_shell.html#ansible-collections-ansible-builtin-sh-shell)
- [ansible.posix.csh shell plugin](https://docs.ansible.com/ansible/latest/collections/ansible/posix/csh_shell.html#ansible-collections-ansible-posix-csh-shell)
- [ansible.posix.fish shell plugin](https://docs.ansible.com/ansible/latest/collections/ansible/posix/fish_shell.html#ansible-collections-ansible-posix-fish-shell)

The `ansible.builtin.sh` plugin doc snippet:
```
Temporary directory to use on targets when executing tasks.
Default: "~/.ansible/tmp"
Configuration:
    INI entry:
    [defaults]
    remote_tmp = ~/.ansible/tmp
    Environment variable: [ANSIBLE_REMOTE_TEMP](https://docs.ansible.com/ansible/latest/collections/environment_variables.html#envvar-ANSIBLE_REMOTE_TEMP)
    Environment variable: [ANSIBLE_REMOTE_TMP](https://docs.ansible.com/ansible/latest/collections/environment_variables.html#envvar-ANSIBLE_REMOTE_TMP)
    Variable: ansible_remote_tmp
```

Many of the **modules** which have an associated plugin **do use** the `remote_tmp` globally configured var to place temporary files, which are files copied from the controller to the managed node, in our case, a script via the `zos_script` module. 

The reason I brought this up initially in the code review is because we would have competing `tmp` locations, the global one and one our module, likely users would always set them as the same but could cause some confusion. Some of those modules with the associated plugins using `remote_tmp` are:
- unarchive
- script
- copy
- command

Below is a snippet added to the `zos_script` module to display the remote_tmp global value:
```
        if not remote_src:
            tmp_path = self._connection._shell.tmpdir
            display.vvv(u"ibm_zos_script show_remote_tmp: {0}".format(tmp_path), host=self._play_context.remote_addr)
```

Below is the `ansible.cfg` configuration update to configure the global `remote_tmp` , there are other ways but here is the configuration I used, notice `remote_tmp` is set to `/tmp/foo`:
```
[defaults]
forks = 25
timeout = 12
remote_tmp = /tmp/foo
```

Here is the verbose `-vvvv` output snippet of interest, look for `/tmp/foo`
```
<xxxxx.xxxx.xxx.ibm.com> (0, b'ansible-tmp-1698346098.2104309-4659-149358670794179=/tmp/foo/ansible-tmp-1698346098.2104309-4659-149358670794179\n', b'')
<xxxxxxxxx.xxx.xxx.ibm.com> ibm_zos_script show_remote_tmp: /tmp/foo/ansible-tmp-1698346098.2104309-4659-149358670794179/
Using module file /Users/ddimatos/git/github/ibm_zos_core/venv/venv-2.15/lib/python3.10/site-packages/ansible/modules/tempfile.py
Pipelining is enabled.
````
