### ISSUE TITLE
[Bug] [zos_submit_job] Option `return_output` when set to false continues to access job output

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1041]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Are the dependencies a supported version?

- [X] The dependencies are supported.

### IBM Z Open Automation Utilities

v1.2.5

### IBM Enterprise Python

v3.9.x

### IBM z/OS Ansible core Version

v1.6.0

### ansible-version

v2.14.x

### z/OS version

v2.5

### Ansible module

zos_job_submit

### Bug description

It was reported that when using `zos_job_submit` with option `return_output=false` that the module continues to invoke code that performs job output reads (jobs.read_output). I have not reviewed the code to understand why we access `jobs.read_output`, the fist thing would be to see if there is anything specific the code needs to operate minimally or is this an unnecessary invocation. 

I can see the value in avoiding this call if its not necessary because it is added overhead but more so,

Note: This could also serve as a work around to the known issue of reading chars that don't correspond to UTF-8 (which will be fixed in Q1 2024) by not reading non-UTF8 content. Although it could help, its only note and not the actual issue being highlighted here. 

This was reported by @jbyibm 
Internal thread: https://<sanitized>.slack.com/archives/CSLEJ8VGV/p1697623287742339?thread_ts=1697595176.094609&cid=CSLEJ8VGV

**Comment by richp405** [comment]
zos_submit_job calls job:job_output, and deletes the values returned

        job_output_txt = job_output(
            job_id=job_submitted_id, owner=None, job_name=None, dd_name=None,
            duration=duration, timeout=wait_time_s, start_time=start_time)


job:job_output calls job:job_detail:

job_detail = _get_job_status(job_id=job_id, owner=owner, job_name=job_name,
                                 dd_name=dd_name, duration=duration, timeout=timeout, start_time=start_time)


We added the ability to 'not' ask for data details in job:_get_job_status
def _get_job_status(job_id="*", owner="*", job_name="*", dd_name=None, dd_scan=True, duration=0, timeout=0, start_time=timer()):
  
But that setting wasn't back-propagated to submit_job or job_output.

It would be fairly trivial to pass this down the chain, so the contents wouldn't be queried.  Small job.
