### ISSUE TITLE
[Bug] [zos_operator] Module is passing wrong wait time property to zoau opercmd

### ISSUE THREAD

**Issue by richp405** [ansible-collections/ibm_zos_core#1043]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Are the dependencies a supported version?

- [X] The dependencies are supported.

### IBM Z Open Automation Utilities

v1.2.5

### IBM Enterprise Python

v3.9.x

### IBM z/OS Ansible core Version

v1.8.0-beta.1

### ansible-version

v2.14.x

### z/OS version

v2.5

### Ansible module

zos_operator, zos_operator_action_query

### Bug description

User reported inconsistency in wait-delay, which was recently addressed.  

When calling opercmd.exec, zos_operator passes the 'wait' boolean as kwarg 'wait_arg'.  This happened from a mis-reading of the opercmd source code.  It should be passing 'wait', not 'wait_arg'.  Originally diagnosed by James McKee.

I've added zos_operator_action_query to double-check, since it was changed at the same time.

**Comment by storfibm** [comment]
If this passed regression, some additional test cases in this area might be helpful

**Comment by ddimatos** [comment]
> If this passed regression, some additional test cases in this area might be helpful

See https://github.com/ansible-collections/ibm_zos_core/pull/1044#issuecomment-1791598073
