### ISSUE TITLE
[Enabler] [Pipeline] ZOAU 1.3 - Integrate new VR into CI/CD & tooling

### ISSUE THREAD

**Issue by storfibm** [ansible-collections/ibm_zos_core#1098]
### Epic
[[Enabler] [Epic] Adopt new ZOAU 1.3 Python changes](https://github.com/ansible-collections/ibm_zos_core/issues/931)

### Enabler description

With the adoption of ZOAU 1.3, a number of changes have occurred that will need to be migrated to the pipelines. Refer to  [migration guide](https://www.ibm.com/docs/en/zoau/1.3.x?topic=planning-migrating-zoau-v13-from-v12x-earlier). 

These include:

- [x] Installing ZOAU 1.3 latest on a Read Only share
- [x] Updating the environment vars to include the sub directories of the precompiled binaries for PYTHONPATH, see documentation [here](https://www.ibm.com/docs/en/zoau/1.3.x?topic=installing-zoau#pythonpath-environment-variable-method), e.g. `export PYTHONPATH=${PYTHONPATH}:${ZOAU_HOME}/lib/3.12`
   - [x] This should use variable substitution such that the proper precompiled binary is selected for the python version in use, noticed the 3.9 - 3.12 sub directories containing precompiled binaries.  
- [ ] Add the option to run only a particular test suite, today we have the exclude tests but this is a bit cumbersome to define when you know which test suite you want to run and override the dependency finder, 
Note:
- Although configure.py is no longer supported for 1.3 (or needed) the shared Python distributions in the share should continue to retain the symlink such that development recreations, support and patching back to zoau versions less than 1.3 can be done easily. (we could consider an automation task that symlinks dynamically in the future to ensure proper full spectrum testing of 1.3 without the symbolic link.

**Comment by richp405** [comment]
Verified 1.3 is latest build
Environment editors now passing startup testing.  This hinges on ZOAPATH/lib.

**Comment by richp405** [comment]
1.3 path corrections have rolled out as Jenkinsfile5e.  Next I will work through the 'force_test" function.  It appears I will need to recreate the configuration.yaml builder from the current dependencyfinder code..

**Comment by richp405** [comment]
Got the 'test only' field working... need to roll it out to group

**Comment by richp405** [comment]
After a few corrections, this now works witn 1.2.5 and 1.3.x of zoau, has a few extra output elements, and is available as Jenkinsfile5f to most pipelines.
