### ISSUE TITLE
[Enabler] [Dev] [zos_operator_action_query] Migrate module, module utilities and test cases to ZOAU 1.3

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1113]
## Ansible module
`zos_operator_action_query`

### See Epic
[[Enabler] [Epic] Adopt new ZOAU 1.3 Python changes](https://github.com/ansible-collections/ibm_zos_core/issues/931)

### Enabler description

With the adoption of ZOAU 1.3, modules, module utilities and test cases may need to be updated according to the [migration guide](https://www.ibm.com/docs/en/zoau/1.3.x?topic=planning-migrating-zoau-v13-from-v12x-earlier). 

APIs changes affecting module:
- Impacted by ZOAU Dataset API: Yes
- Impacted by ZOAU jobs API: No
- Impacted by the rename of types.py to ztypes.py: No
- Impacted by the contents of module volumes.py having been moved to datasets.py: No
- Impacted by opercmd timeout to milli seconds: Yes
- Impacted by JSON schema change in either apfadm, dmod, dsed or zinfo: No
- Impacted by Exceptions schema: No

Review the [zoautil_py datasets module migration doc](https://www.ibm.com/docs/en/zoau/1.3.x?topic=planning-migrating-zoau-v13-from-v12x-earlier#changes-to-the-datasets-module).

Upon review, this module is affected by:
- the opercmd utility argument timeout returns time in hundredths of a second (0.01 sec) rather than seconds
   - see: `response = opercmd.execute(operator_cmd, timeout, *args, **kwargs)`
   - NOTE: We will need to decide if we will leave the module timeout as seconds and perform conversions in the code or we should update the module interface to milliseconds but that might be to small an increment to make sense for a module that performs poorly over a newtwork. 

This issue depends on shared import identified by git issues:
- [module_utils/better_arg_parser.py](https://github.com/ansible-collections/ibm_zos_core/issues/1116)

**Comment by ketankelkar** [comment]
Note- Ansible zos_operator calculates `elapsed` independent of ZOAU. 
`elpased` is one of the fields the zos_operator module returns.


roughly:
```python
def execute_command(operator_cmd, timeout=1, *args, **kwargs):
    start = timer()
    response = opercmd.execute(   ...   )
    end = timer()

    ....

    elapsed = round(end - start, 2)
    return ..., elapsed
```
[src](https://github.com/ansible-collections/ibm_zos_core/blob/410925dfa16b6e658e772d7e37cbd8e98af540ea/plugins/modules/zos_operator.py#L175)
