### ISSUE TITLE
[Enabler] [Val] [module_utils/better_arg_parser.py] Migrate module, module utilities and test cases to ZOAU 1.3

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1116]
## module_utils
`better_arg_parser.py`

### See Epic
[[Enabler] [Epic] Adopt new ZOAU 1.3 Python changes](https://github.com/ansible-collections/ibm_zos_core/issues/931)

### Enabler description

With the adoption of ZOAU 1.3, modules, module utilities and test cases may need to be updated according to the [migration guide](https://www.ibm.com/docs/en/zoau/1.3.x?topic=planning-migrating-zoau-v13-from-v12x-earlier). 

Upon review, this module is **NOT** affected by ZAOU APIs 1.3, this is a placeholder for now to determine if any work needs to be tracked on this utility because of its reach across the collection. 

APIs changes affecting module:
- Impacted by ZOAU Dataset API: No
- Impacted by ZOAU jobs API: No
- Impacted by the rename of types.py to ztypes.py: No
- Impacted by the contents of module volumes.py having been moved to datasets.py: No
- Impacted by opercmd timeout to milli seconds: No
- Impacted by JSON schema change: No
- Impacted by Exceptions schema: No

The dependency finder found this util use imported by these sources:
- /tests/functional/modules/test_zos_tso_command_func.py 
- /tests/functional/modules/test_zos_script_func.py 
- /tests/unit/test_zos_operator_action_query_unit.py 
- /tests/functional/modules/test_zos_operator_action_query_func.py 
- /tests/functional/modules/test_zos_data_set_func.py 
- /tests/functional/modules/test_zos_fetch_func.py 
- /tests/functional/modules/test_zos_backup_restore.py 
- /tests/functional/modules/test_zos_archive_func.py 
- /tests/functional/modules/test_zos_encode_func.py 
- /tests/functional/modules/test_zos_blockinfile_func.py 
- /tests/unit/test_zos_mvs_raw_unit.py 
- /tests/functional/modules/test_zos_operator_func.py 
- /tests/functional/modules/test_zos_copy_func.py 
- /tests/functional/modules/test_zos_mount_func.py 
- /tests/functional/modules/test_zos_lineinfile_func.py 
- /tests/unit/test_zos_operator_unit.py 
- /tests/functional/modules/test_zos_job_query_func.py 
- /tests/functional/modules/test_zos_job_output_func.py 
- /tests/functional/modules/test_zos_find_func.py 
- /tests/functional/modules/test_zos_mvs_raw_func.py 
- /tests/functional/modules/test_module_security.py 
- /tests/functional/modules/test_zos_apf_func.py 
- /tests/functional/modules/test_zos_unarchive_func.py 
- /tests/functional/modules/test_zos_volume_init_func.py 
- /tests/functional/modules/test_zos_job_submit_func.py 
- /tests/unit/test_zos_backup_restore_unit.py

**Comment by ddimatos** [comment]
You should be able to run the isolated functional test cases on the parser `/tests/functional/module_utils/test_arg_parser.py` as part of this validation.

**Comment by ketankelkar** [comment]
Upon further investigation, nothing came up as requiring adaptations/modifications in light of the migration to ZOAU 1.3.0.
