### ISSUE TITLE
[Enabler] [tests/test_zos_data_set_func.py] Migrate module, module utilities and test cases to ZOAU 1.3 

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1124]
## module_utils
`test_zos_data_set_func.py`

### See Epic
[[Enabler] [Epic] Adopt new ZOAU 1.3 Python changes](https://github.com/ansible-collections/ibm_zos_core/issues/931)

### Enabler description

With the adoption of ZOAU 1.3, modules, module utilities and test cases may need to be updated according to the [migration guide](https://www.ibm.com/docs/en/zoau/1.3.x?topic=planning-migrating-zoau-v13-from-v12x-earlier). 

APIs changes affecting module:
- Impacted by ZOAU Dataset API: No
- Impacted by ZOAU jobs API: No
- Impacted by the rename of types.py to ztypes.py: No
- Impacted by the contents of module volumes.py having been moved to datasets.py: No
- Impacted by opercmd timeout to milli seconds: No
- Impacted by JSON schema change: Yes (zinfo)
- Impacted by Exceptions schema: No

Review the [zoautil_py datasets module migration doc](https://www.ibm.com/docs/en/zoau/1.3.x?topic=planning-migrating-zoau-v13-from-v12x-earlier#changes-to-the-datasets-module).

Upon review, this module is affected by:
- the utilities apfadm, dmod, dsed, and zinfo supported limited JSON output with a schema that is now obsolete, so any use of previous output must be updated
   - See `result0 = hosts.all.shell(cmd="zinfo -t sys")`

- Note, that the content for `zinfo` has been encapsulated with a `data` object (#954), validation should be covered through regression testing to ensure our formatting is correct and possibly we might need to extract the content from the data object or create a migration guide. 

For reference the JSON Schema changes with examples should also be reviewed:
https://www.ibm.com/docs/en/zoau/1.3.x?topic=examples-json-schema

#954 - we may cancel this issue if the work is handled on each module

To learn more, see [ZOAU JSON schema and examples](https://www.ibm.com/docs/en/SSKFYE_1.3.x/json_examples.html).

This issue depends on shared import identified by git issues:
- [module_utils/better_arg_parser.py](https://github.com/ansible-collections/ibm_zos_core/issues/1116)

**Comment by fernandofloresg** [comment]
Since this uses `zos_job_submit` you will need to remove the `wait` option from any `zos_job_submit` call. This was recently removed.
