### ISSUE TITLE
[Enabler] [Val] [zos_job_output] Validate module with ZOAU 1.3

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1137]
## Ansible Module
`zos_job_output`

### See Epic
[[Enabler] [Epic] Adopt new ZOAU 1.3 Python changes](https://github.com/ansible-collections/ibm_zos_core/issues/931)

### Enabler description

This module has no identified migration work, its test cases have minimal to no module dependencies and because it is a foundational module used by other test cases need to have regression run. This modules regression should only be run, running other regression will result in error, on success, this issue can be closed.
 
[Migration guide](https://www.ibm.com/docs/en/zoau/1.3.x?topic=planning-migrating-zoau-v13-from-v12x-earlier) for reference.

**Comment by rexemin** [comment]
After migrating `module_utils/job.py`, I found out that the new exception hierarchy in ZOAU 1.3.0 breaks this module. Part of the validation work will involve handling the new `JobFetchException` when no jobs are found. To import the new exception:

```python
from zoautil_py.exceptions import JobFetchException
```

And the try/except block could look like this (leaving the exact `msg` used to Marcel):
```python
except JobFetchException as fetch_exception:
        module.fail_json(
            rc=fetch_exception.response.rc,
            stdout=fetch_exception.response.stdout_response,
            stderr=fetch_exception.response.stderr_response,
        )
```

More information about the new ZOAU exceptions [here](https://www.ibm.com/docs/en/zoau/1.3.x?topic=apis-exceptions).
