### ISSUE TITLE
[Enabler] [Val] [zos_tso_command] Validate module with ZOAU 1.3

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1138]
## Ansible Module
`zos_tso_command`

### See Epic
[[Enabler] [Epic] Adopt new ZOAU 1.3 Python changes](https://github.com/ansible-collections/ibm_zos_core/issues/931)

### Enabler description

This module has no identified migration work, its test cases have minimal to no module dependencies and because it is a foundational module used by other test cases need to have regression run. This modules regression should only be run, running other regression will result in error, on success, this issue can be closed.
 
[Migration guide](https://www.ibm.com/docs/en/zoau/1.3.x?topic=planning-migrating-zoau-v13-from-v12x-earlier) for reference.

**Comment by ketankelkar** [comment]
All `zos_tso_command` module functional tests PASSED with ZOAU `v1.3.0` on the internal Jenkins pipeline `zosAnsibleKetan` (job `#50`).

![image](https://github.com/ansible-collections/ibm_zos_core/assets/10567394/d985ed53-ef56-4e6a-bdea-40c5fa4e9ea8)

**Comment by ketankelkar** [comment]
Concluded initial prediction that no changes are needed was correct after doing a once-over of the code base.
