### ISSUE TITLE
[Enabler] [Val] [zos_ping] Validate module with ZOAU 1.3

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1139]
## Ansible Module
`zos_ping`

### See Epic
[[Enabler] [Epic] Adopt new ZOAU 1.3 Python changes](https://github.com/ansible-collections/ibm_zos_core/issues/931)

### Enabler description

This module has no identified migration work, its test cases have minimal to no module dependencies and because it is a foundational module used by other test cases need to have regression run. This modules regression should only be run, running other regression will result in error, on success, this issue can be closed.
 
[Migration guide](https://www.ibm.com/docs/en/zoau/1.3.x?topic=planning-migrating-zoau-v13-from-v12x-earlier) for reference.

**Comment by fernandofloresg** [comment]
Validated that zos_ping works with ZOAU v1.3.0 by testing using the pipeline.

![Image](https://github.com/ansible-collections/ibm_zos_core/assets/23223623/bb526a4b-0194-4400-b472-4e3c9e01f518)



![Image](https://github.com/ansible-collections/ibm_zos_core/assets/23223623/018ca2ef-dca3-4000-9d41-51760f741299)
