### ISSUE TITLE
[Enabler] [Val] [zos_job_query] Validate module with ZOAU 1.3

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1141]
## Ansible Module
`zos_job_query`

### See Epic
[[Enabler] [Epic] Adopt new ZOAU 1.3 Python changes](https://github.com/ansible-collections/ibm_zos_core/issues/931)

### Enabler description

This module has no identified migration work, its test cases have minimal to no module dependencies and because it is a foundational module used by other test cases need to have regression run. This modules regression should only be run, running other regression will result in error, on success, this issue can be closed.

JSON changes, jobs api has updated its response where it is now encapsulated by a `data` object and has additional properties , `program`, `options`, etc that may flow through Ansible responses which we may not want at this time, evaluate the responses , this relates to cancelled work item #942 , see documentation [here](https://www.ibm.com/docs/en/zoau/1.3.x?topic=examples-json-schema)
 
[Migration guide](https://www.ibm.com/docs/en/zoau/1.3.x?topic=planning-migrating-zoau-v13-from-v12x-earlier) for reference.

**Comment by rexemin** [comment]
ZOAU v1.3.0 changes the attribute `svc_class` from the `Job` class to `service_class`. It will be necessary to change this next portion of the code to accommodate this change (inside the `parsing_jobs` function):

```python
job_dict = {
            "job_name": job.get("job_name"),
            "owner": job.get("owner"),
            "job_id": job.get("job_id"),
            "system": job.get("system"),
            "subsystem": job.get("subsystem"),
            "ret_code": ret_code,
            "job_class": job.get("job_class"),
            "svc_class": job.get("svc_class"),
            "priority": job.get("priority"),
            "asid": job.get("asid"),
            "creation_date": job.get("creation_date"),
            "creation_time": job.get("creation_time"),
            "queue_position": job.get("queue_position"),
            "program_name": job.get("program_name"),
}
```

**Comment by ddimatos** [comment]
Nice catch !!!
