### ISSUE TITLE
[Collaboration] [Playbook Repository] Update documentation, configurations and examples in support of ZOAU 1.3

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1151]
### Epic
[[Enabler] [Epic] Adopt new ZOAU 1.3 Python changes](https://github.com/ansible-collections/ibm_zos_core/issues/931)

### Collaboration description

With the adoption of ZOAU 1.3, a number of changes have occurred that will need to be migrated to the pipelines. Refer to  [migration guide](https://www.ibm.com/docs/en/zoau/1.3.x?topic=planning-migrating-zoau-v13-from-v12x-earlier). 

These include:
- Updating the environment vars to include the sub directories of the precompiled binaries for PYTHONPATH, see documentation [here](https://www.ibm.com/docs/en/zoau/1.3.x?topic=installing-zoau#pythonpath-environment-variable-method), e.g. `export PYTHONPATH=${PYTHONPATH}:${ZOAU_HOME}/lib/3.12`
   - This should use variable substitution such that the proper precompiled binary is selected for the python version in use, noticed the 3.9 - 3.12 sub directories containing precompiled binaries.  

### Is there an existing issue for this?

- [X] There are no existing issues.

### Support and service?

- [ ] Yes, support and service is involved.
- [X] No, support and service is involved.

### Are the dependencies a supported?

- [X] Yes, the dependencies are supported.
- [ ] Not applicable to this collaboration.

### IBM Z Open Automation Utilities

None

### IBM z/OS Ansible core Version

None

### ansible-version

None

### z/OS version

v2.5

**Comment by ketankelkar** [comment]
The bulk of the work (designing the new configuration choices) was completed March 26 ([see this commit](https://github.com/IBM/z_ansible_collections_samples/pull/246/commits/e2cc5bc300d4929df509b8622a0c29c5285cb0b8)). 

Note- the above PR was closed when the branch was renamed.

The work that remains for this item is simply propagating the changes in the above commit to the remainder of the playbooks. Track that progress [here](https://github.com/IBM/z_ansible_collections_samples/pull/252)

**Comment by ketankelkar** [comment]
since this work was mostly completed in q1, and what remains is only reviews and merging, I am closing this issue out for the sake of "housekeeping".
