### ISSUE TITLE
[Enabler] [Discussion] Collaborate with IBM Python, Ansible partners and the community on the read binary and encoding issue to find a solution

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1159]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

This issue continues previous issue #979 , where communications with IBM Python for a short term solution now involves additional parties input. On initial review questions were raised and forwarded to Ansible Partners who will set up a future call to discuss them. 

What this issue aims to address is that all parties understand the issue with the communities modules opening files with an `RB` and how that impacts those modules when executed on z/OS USS (Unix System Services) such that files opened now with Python 3.10 or later are not opened/converted to UTF8 for Python to understand, instead they are opened as is (EBCDIC) and causes a encoding error. 

The nature of this issue will not be pinned to an iteration since it will be managed for some time, thus it will be placed at the Q1 2024 end and referenced regularly during team meetings. 

This issue is part of epic/collaboration #676

**Comment by ketankelkar** [comment]
Various discussions were had over emails, slack messages and webex calls. All parties involved now have a firm understanding of the issue regarding Ansible community modules reading files in `rb` mode and writing in `wb` and the impact to z/OS UNIX files encoded in EBCDIC. 

A multi-faceted approach will be taken to address the concern at hand and improve the user experience for those targeting z/OS managed nodes with `builtin` community modules. 

Firstly, docs will be updated to reflect the present limitations of Ansible community modules for use with files not encoded in UTF-8. Remedies to convert and appropriately tag z/OS UNIX files (`iconv`, `chtag`) will be mentioned too. This will aim to educate those targeting z/OS managed nodes of what expectations are reasonable from the community modules. 

Efforts will also be made to push code changes into the community; changes which will greatly enhance the z/OS managed node experience without impacting the non-z/OS experience. 

These efforts will be tracked in another epic. The scope of discussions mentioned in this current issue has been met.
