### ISSUE TITLE
[Epic] [Enabler] [Discussion] Modules zos_job_submit and zos_data_set are unable to support permitted `$` symbol in data set names

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1161]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Ansible module

zos_data_set, zos_job_submit

### Enabler description

See issues:
- #642 
- #724 
- #1011 

This epic is in place to manage the work previously done in Q4 2023 to address these issues, given the feedback provided on the pull request this item has been put on hold and carried forward to evaluate the current code proposed or a more generic yet global approach to modify the better_arg_parser or such that would satisfy all modules needs rather than `zos_job_submit` and `zos_data_set`. 

This evaluation has been sized according to a review and development discussion meaning the team will discuss the two options and some added research to conclude if the current PR is the best approach and if not, what is the best approach. 

Depending on the outcome of this issue, a new issue with proper sizing may be needed, there are always more than one way to solve everything, here we hope to achieve the most fitting solution with the least amount of impact and maintenance .

**Comment by ddimatos** [comment]
Going to reduce this down to 0 points given the work will likely be associated to issue #1366 and no further development was performed, other than a meeting to discuss the two designs which is not 3 pts of work.

**Comment by fernandofloresg** [comment]
Validated all the issues named in the description that tested this behavior.

**Comment by ddimatos** [comment]
It looks like this EPIC overlaps with Q2 work which will release as version 1.11.0-beta.1 (GDG and Symbol support) , I believe this epic was just there to group the various symbol issues and based on Fernando's note this work has been completed by the GDG work. "Validated all the issues named in the description that tested this behavior."

So I updated the target as it was pointing to 1.10-beta.1 and closing the issue and putting back to Q2.
