### ISSUE TITLE
[Enabler] [Pipeline] Test collections and update pipeline for ansible-core 2.17

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1170]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

May 29th is the anticipated GA of `ansible-core` 2.17, we should ensure compatibility of this release or sooner if possible. 

Note that the minimum python controller version is 2.10,  this will require that our pipeline minimally use slimbuster 3.10. 

![Image](https://github.com/ansible-collections/ibm_zos_core/assets/25803172/4cec3e67-0ff9-4f86-be0d-b20df9669a43)

**Comment by richp405** [comment]
completed
