### ISSUE TITLE
[Enabler] Add/evaluate support for ZOAU 1.3. to development tool `.ac`

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1174]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

The `mounts.env` should be updated by the time this issue is reviewed; its been reported the tooling correctly executes with the currently generated config.yml but thought worthwhile to investigate how this happens if any changes need to be made to the tooling. 

The tooling currently generates a static path for the zoau precompiled binaries which are fine for zoau 1.2 or earlier, but starting with 1.3 , zoau ships a nested set of precompiled binaries, one for each version of python that might need to reflected in the tools generated config. 

See [lines here](https://github.com/ansible-collections/ibm_zos_core/blob/94180f534d58cfba251bb6c5ed1f4991c87a18cb/scripts/venv.sh#L538) and [here](https://github.com/ansible-collections/ibm_zos_core/blob/94180f534d58cfba251bb6c5ed1f4991c87a18cb/scripts/venv.sh#L509)

```
CONFIG=${CONFIG}"  PYTHONPATH: ${ZOAU_HOME}/lib\\n"
```

**Comment by richp405** [comment]
canceled because it was done
