### ISSUE TITLE
[Bug] [zos_data_set] Test case fails by creating an entry in catalog with a non existing data set in specific volume

### ISSUE THREAD

**Issue by fernandofloresg** [ansible-collections/ibm_zos_core#1193]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Are the dependencies a supported version?

- [X] The dependencies are supported.

### IBM Z Open Automation Utilities

v1.3.0

### IBM Enterprise Python

v3.11.x, also 3.10 patched

### IBM z/OS Ansible core Version

v1.10.0-beta.1,

### ansible-version

v2.16.x, v2.14

### z/OS version

v2.5

### Ansible module

zos_data_set

### Bug description

While running test_data_set_func.py test_data_set_catalog_and_uncatalog an attempt is done to catalog a non-existing data set, however, later the test fails because there is an entry in the catalog that was not cleaned properly.

This is true of several tests in the test_zos_data_set_func.py... a new filename is cataloged, then deleted.  This has shown to leave "residue" in the catalog, especially during an assertion failure.  This in turn prevents file creation (because the file already appears to exist in the catalog).

**Comment by richp405** [comment]
I've recreated this several times during testing for sanity tests on zos_data_set.  This seems to happen with 2.14 ansible, any python, and zoau 1.2.5.2 or older.

Current status:
#1 - This test action had been removed so other tests could continue.
#2 - I'm now looking at other ways to determine the cause (a - why the catalog gets fouled up, b - how to fix it).

**Comment by richp405** [comment]
If a file is cataloged that does not exist, we get back 'success', and yet can't delete the file.

What MAY be related: deleting a file that doesn't exist can also cause this, because of a call to 'catalog if necessary' inside a delete call.  I'm researching this.

**Comment by fernandofloresg** [comment]
Might be fixed by #1242

**Comment by richp405** [comment]
I cloned dev, uncommented the tests that were cataloging non-existant files, and the tests fully passed.  Not sure if this needs the whole fragments formality since this is not customer facing.  I'll bring it up in stand-up on Thursday.


![Image](https://github.com/ansible-collections/ibm_zos_core/assets/39140439/c5a429d7-b3b5-4f79-91c4-affd2f6e7b72)
