### ISSUE TITLE
[Bug] [zos_job_submit] iconv error occur with module zos_job_submit

### ISSUE THREAD

**Issue by Emi-Furubayashi** [ansible-collections/ibm_zos_core#1211]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Are the dependencies a supported version?

- [X] The dependencies are supported.

### IBM Z Open Automation Utilities

v1.2.5

### IBM Enterprise Python

v3.11.4

### IBM z/OS Ansible core Version

v1.4.1

### ansible-version

v2.9.27

### z/OS version

v2.5

### Ansible module

zos_job_submit

### Bug description

When using module zos_job_submit, the following error occurs in the case of specifying location=LOCAL , encode from UTF-8 to IBM-1047.
The input file (UTF-8 , LF text JCL file) has been tested with other methods of iconv (at ubuntu , or , host with BPXBATCH) and confirmed that there's no error, the converted text JCL file are executed successfully at host.

fatal: [SYX]: FAILED! => {
    "changed": false,
    "checksum": "f0e7e00b819174e004a275f279b3df6a36f44ca2",
    "dest": "/tmp/ansible.tadive7g",
    "gid": 102,
    "group": "XXXXXXX",
    "invocation": {
        "module_args": {
            "encoding": null,
            "from_encoding": "UTF-8",
            "location": "LOCAL",
            "max_rc": null,
            "return_output": true,
            "src": "./IEFBR14#.txt",
            "temp_file": "/tmp/ansible.tadive7g",
            "template_parameters": null,
            "to_encoding": "IBM-1047",
            "use_template": false,
            "volume": null,
            "wait": false,
            "wait_time_s": 10
        }
    },
    "md5sum": "4e272a0c86d56c5f7fda6a251047f1d4",
    "mode": "0600",
    "msg": "Failed to convert the src /u/userhome/XXXXXX/IEFBR14#.txt from encoding UTF-8 to encoding IBM-1047, unable to submit job.",
    "owner": "XXXXXX",
    "size": 255,
    "src": "/u/userhome/xxxxxx/.ansible/tmp/ansible-tmp-1706169832.9919362-25-152643230797564/source",
    "state": "file",
    "stderr": "iconv: 1 illegal character sequence(s) for codeset in input file\\n",
    "stderr_lines": [
        "iconv: 1 illegal character sequence(s) for codeset in input file"
    ],
    "stdout": "",
    "stdout_lines": [],
    "uid": 3205
}

**Playbook**
- name: submit a JCL job
  hosts: all
  gather_facts: no
  collections:
    - ibm.ibm_zos_core
  environment:
    _BPXK_AUTOCVT: "ON"
    _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
    _TAG_REDIR_ERR: "txt"
    _TAG_REDIR_IN: "txt"
    _TAG_REDIR_OUT: "txt"
    LANG: "C"
  vars:
    jcl_src: "{{ jcl_source_name }}"
    jcl_loc: "{{ jcl_location_name }}"
  tasks:
  # zoscore_submit_jcl.yml
    - name: '{{ lookup(''pipe'', ''date "+%Y/%m/%d %H:%M:%S"'') }}  Submit JCL and wait up to 30 seconds for completion'
      zos_job_submit:
        src: "{{ jcl_src }}"
        location: "{{ jcl_loc }}"
        encoding: 
          from: "UTF-8"
          to: "IBM-1047"
      register: results

### Playbook verbosity output.

  config file = /runner/project/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.16 (default, May 31 2023, 12:44:21) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)]
Using /runner/project/ansible.cfg as config file
SSH password: 
setting up inventory plugins
host_list declined parsing /runner/inventory/hosts as it did not pass its verify_file() method
Parsed /runner/inventory/hosts inventory source with script plugin
Loading callback plugin awx_display of type stdout, v2.0 from /usr/lib/python3.8/site-packages/ansible_runner/callbacks/awx_display.py
Skipping callback 'actionable', as we already have a stdout callback.
Skipping callback 'awx_display', as we already have a stdout callback.
Skipping callback 'counter_enabled', as we already have a stdout callback.
Skipping callback 'debug', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'full_skip', as we already have a stdout callback.
Skipping callback 'json', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'null', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
Skipping callback 'selective', as we already have a stdout callback.
Skipping callback 'skippy', as we already have a stdout callback.
Skipping callback 'stderr', as we already have a stdout callback.
Skipping callback 'unixy', as we already have a stdout callback.
Skipping callback 'yaml', as we already have a stdout callback.

PLAYBOOK: zoscore_submit_jcl.yml ***********************************************
Positional arguments: zoscore_submit_jcl.yml
verbosity: 4
ask_pass: True
remote_user: XXXXXX
connection: smart
timeout: 60
become_method: sudo
tags: ('all',)
inventory: ('/runner/inventory/hosts',)
subset: SYX
extra_vars: ('@/runner/env/tmpszvb_xoz', '@/runner/env/tmp5_7l3zba', '@/runner/env/extravars')
forks: 5
1 plays in zoscore_submit_jcl.yml

**Comment by ddimatos** [comment]
@Emi-Furubayashi  thank you for opening an issue, I would close the duplicate [discussion](https://github.com/ansible-collections/ibm_zos_core/discussions/1206) since the git issue has more details. 

I understand you are able to convert the file on other hosts (ubuntu, z/os, etc) but to ensure the source is as it is being described I will need the output of the below playbook. The playbook will test the files encoding locally and remotely and submit it from USS instead of the controller. Please share the output, you should run with verbosity `ansible-playbook -i inventory playbook.yml -vvvv".

```
---
- hosts: zvm
  collections:
    - ibm.ibm_zos_core
  gather_facts: false

  environment: "{{ environment_vars }}"
  vars:
    jcl_src: "{{playbook_dir}}/files/hello.jcl"
    jcl_loc: "/tmp/hello.jcl"

  tasks:
    - name: Test a file for file encoding locally
      shell: /usr/bin/iconv -f UTF-8 -t UTF-8 "{{jcl_src}}" >/dev/null;echo $?
      delegate_to: localhost
      register: result

    - name: Results
      debug:
        var: result

    - name: Copy a local binary file to USS
      zos_copy:
        src: "{{jcl_src}}"
        dest: "{{jcl_loc}}"
        is_binary: true
        force: true
      register: result

    - name: Results
      debug:
        var: result

    - name: Test file on USS for UTF-8 encoding
      shell: iconv -f UTF-8 -t UTF-8 "{{jcl_loc}}" >/dev/null;echo $?
      register: result

    - name: Results
      debug:
        var: result

    - name: Create IBM-1047 encoding file on USS
      shell: iconv -f UTF-8 -t IBM-1047 "{{jcl_loc}}" >"{{jcl_loc}}.1047"; echo $?
      register: result

    - name: Results
      debug:
        var: result

    - name: Test file on USS for IBM-1047 encoding
      shell: iconv -f IBM-1047 -t IBM-1047 "{{jcl_loc}}" >/dev/null;echo $?
      register: result

    - name: Results
      debug:
        var: result

    - name: Submit IBM-1047 JCL on USS
      zos_job_submit:
        src: "{{jcl_loc}}.1047"
        location: USS
      register: result

    - name: Results
      debug:
        var: result
```

**Comment by Emi-Furubayashi** [comment]
Hi, i attached the output log file of the error playbook. 　I've changed some items in the log to dummy values.
[job_zos_job_submit_failed_#1211.zip](https://github.com/ansible-collections/ibm_zos_core/files/14217824/job_zos_job_submit_failed_.1211.zip)

**Comment by Emi-Furubayashi** [comment]
Then, i attached a log file , of another successful playbook.  
I changed some items to dummy values .
[job_zos_job_submit__sample_success_#1221.zip](https://github.com/ansible-collections/ibm_zos_core/files/14218082/job_zos_job_submit__sample_success_.1221.zip)

This playbook includes, removed some comment lines and parts:
  hosts: all
  gather_facts: no
  collections:
    - ibm.ibm_zos_core
  environment:
    _BPXK_AUTOCVT: "ON"
    _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
    _TAG_REDIR_ERR: "txt"
    _TAG_REDIR_IN: "txt"
    _TAG_REDIR_OUT: "txt"
    LANG: "C"
  vars:
    src: "{{ source_name }}"
    dest: "{{ dest_name }}"
  tasks:  
    - name: '{{ lookup(''pipe'', ''date "+%Y/%m/%d %H:%M:%S"'') }}  Step1.Copy a local JCL.txt file to a USS location '
      zos_copy:
        src: "{{ src }}"
        dest: "{{ dest }}"
        is_binary: true
        force: true
    - name: '{{ lookup(''pipe'', ''date "+%Y/%m/%d %H:%M:%S"'') }}  Step2.Submit JCL1 - iconv JCL'
      zos_job_submit:
        src: "TEST.ANS.JCL(BPXBATCH)"
        location: "DATA_SET"
        wait_time_s: 180
      register: results
    - name: Print response
      debug:
        var: results

<<Omitted irrelevant parts>>

    - name: '{{ lookup(''pipe'', ''date "+%Y/%m/%d %H:%M:%S"'') }}  Step4.Submit JCL3 - JCL.txt - team libraries request process'
      zos_job_submit:
        src: "/u/userhome/**uid**/IBM1047"
        location: "USS"
        wait_time_s: 180
      register: results
    - name: Print response
      debug:
        var: results

**Comment by ddimatos** [comment]
@Emi-Furubayashi 
- thank you for the zipped `job_zos_job_submit_failed_.1211.zip` output, it corresponds to the initial description you provided in the git issue. 
- thank you for the second zip `job_zos_job_submit__sample_success_#1221.zip` showing:
   - (1) You copied file `./IEFBR14#.txt` as BINARY  with option`is_binary=true` using module `zos_copy` to USS location `/u/userhome/**UID**/JCL.txt`
   - (2) You then submitted JCL in MEMBER `TEST.ANS.JCL(BPXBATCH)` which performs a `SH iconv -f UTF-8 -t IBM-1047 JCL.txt > IBM1047`
   - (3) you submit JCL named IBM1047 with success.
   
I see why you shared this, your point is that you, copied UTF8 Text to z/OS as BINARY , performed an `iconv` on the text without error and then submitted in summary. Thus showing that the UTF8 file is actually UTF8 and that there is no issue using `iconv` via BPXBATCH (on USS). Sound correct?

Well, here are my thoughts:
- but how do I know that the source after the BINARY copy located here `/u/userhome/**UID**/JCL.txt` is the same source being input to `iconv` via BPXBATCH, **there is no absolute path in the command** `PARM='SH iconv -f UTF-8 -t IBM-1047 JCL.txt > IBM1047'` ?
- Why don't I see any environment variables in your verbose log, which means your environment varialbles we require are not flowing to the managed z/OS node making it unstable and difficult to troubleshoot, you should be seeing something like this in your log if they are configured, you can read about configuring environment variables the preferred way [here](https://github.com/IBM/z_ansible_collections_samples/blob/main/docs/share/zos_core/configuration_guide.md#variables) , example of that in any [sample] (https://github.com/IBM/z_ansible_collections_samples/tree/main/zos_concepts/data_sets/data_set_basics) or if you just want to try something quickly add them to your playbook [here](https://github.com/ansible-collections/ibm_zos_core/discussions/657)
```
EXEC sshpass -d12 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="user1"' -o ConnectTimeout=10 -o 'ControlPath="/home/tstomeg/.ansible/cp/30113fc47b"' node.myserver.COM '/bin/sh -c '"'"'
_BPXK_AUTOCVT=ON 
ZOAU_HOME=/usr/idz/zoautil 
PYTHONPATH=/usr/idz/zoautil/lib
LIBPATH=/usr/idz/zoautil/lib:/usr/pyz/3.10.7/lib:/lib:/usr/lib:. 
PATH=/usr/idz/zoautil/bin:/usr/pyz/3.10.7/bin:/bin:/var/bin 
_CEE_RUNOPTS='"'"'"'"'"'"'"'"'
FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)'"'"'"'"'"'"'"'"' 
_TAG_REDIR_ERR=txt 
_TAG_REDIR_IN=txt 
_TAG_REDIR_OUT=txt 
LANG=C 
PYTHONSTDINENCODING=cp1047 
/usr/pyz/3.10.7/bin/python3.10 && sleep 0'"'"''
```
- You are currently on an unsupported version of Ansible 2.9.x, while its not probably the issue its another variable to consider. 

Suggestions:
- Upgrade ibm_zos_core to 1.7.0, that is the latest version you can use when using zoau 1.2.3 (just a suggestion)
- Enable `pipelining=true` as it appears to be off, not required but will improve performance

Must do:
- Configure your environment variables as noted above
- Upgrade your ansible-core to 2.14 or later, I suggest 2.15 or later as 2.14 go out of service in a few months
- Try again and send me the verbose log
- Try also the playbook I included as it removes the doubt about the source file being used with `iconv`


Note issues close after 30 days of inactivity.

**Comment by Emi-Furubayashi** [comment]
Thank you for your detailed thoughts, and I understand that the environment needs to be improved, such as the version of zoau. We will consider the content of the answer and try to do what is possible.

**Comment by Emi-Furubayashi** [comment]
It's a supplement.
The BPXBATCH jcl in the log file "job_zos_job_submit__sample_success_#1221.txt" is as belows,

//**UID**BX JOB MSGCLASS=V,CLASS=T,NOTIFY=&SYSUID,                               
//             GROUP=TESTGRP                                                    
/*JOBPARM SYSAFF=XTEXT                                                          
//*+------------------------------------------------------------------+         
//SHELLCMD EXEC PGM=BPXBATCH,                                                   
// PARM='SH iconv -f UTF-8 -t IBM-1047 JCL.txt > IBM1047'                       
//STEPLIB   DD DSN=SYS1.LINKLIB,DISP=SHR                                        
//STDERR   DD SYSOUT=*                                                          
//STDENV   DD *                                                                 
PATH=/u/userhome/**uid**                                                         
/*                                                                              
//*+------------------------------------------------------------------+

**Comment by ddimatos** [comment]
Ok, that helps, the recommendations still hold true but while those are being addressed, could you maybe attach your JCL, if it sensitive maybe just a more minimized version of the JCL so I can try to recreate with your JCL. If you could put it in a zip file and attach might help with any conversions done when transferring it.

**Comment by Emi-Furubayashi** [comment]
I have some questions; 
Q1. about "ansible-core to 2.14 or later" in "Must do"
Which version Is it , "ansible core" or "IBM z/OS Ansible core"?

Q2. about "version"
Does version "IBM z/OS Ansible core Version" mean the same as version"ibm_zos_core collections" ?

Q3. about "version"
Does version "ansible-version" mean the same as version"ansible core (ansible base)" ? 

Q4. Should the following command be run on Ansible Tower? 
"EXEC sshpass -d12 ssh -C -o ControlMaster=auto -o **Omitted below**

**Comment by ddimatos** [comment]
@Emi-Furubayashi , good questions, I should be more explicit as the products go by various conventions. 

Q1. about "ansible-core to 2.14 or later" in "Must do"
-  Install the Ansible package `ansible-core` , not the IBM z/OS core collection, in other words `pip install ansible-core==2.14.14` (please read down to Q4)

Q2. about "version" Does version "IBM z/OS Ansible core Version" mean the same as version"ibm_zos_core collections" ?
- For this upgrade your `ibm_zos_core` collection, its not required but you might as well use `ibm_zos_core=1.7.0` which is supported by your current installation of `ZOAU=1.2.3`
- `ansible-galaxy collection install -fc ibm.ibm_zos_core:1.7.0`

Q3. about "version" Does version "ansible-version" mean the same as version"ansible core (ansible base)" ?
- Not sure I understand but I think Q1 , Q2 clarify but just go to a bit into naming of Ansible:
   - In 2.9 it was referred to as `ansible`
   - In 2.10 it was renamed to `ansible-base`
   - In 2.11 and later it was renamed to `ansible-core`
   - Also, you might here others refer to Ansible as Ansible proper and Engine, basically it means `ansible-core`

Q4. Should the following command be run on Ansible Tower? "EXEC sshpass -d12 ssh -C -o ControlMaster=auto -o Omitted below...

I am bit confused by this question, if you are using AAP, I don't understand why you would want to run the above command. Each AAP comes with a specific version of Ansible, you can find that in the Ansible Automation Platform Life Cycle documentation [here](https://urldefense.proofpoint.com/v2/url?u=https-3A__access.redhat.com_support_policy_updates_ansible-2Dautomation-2Dplatform&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=3LYk_nKY2ZgoRXFagrpoPJRK8RFJWik0xzZ40rjm6SA&m=wlL6yT9XOQ-1qCZg5oQ7TG8Ng61f_En5zY2fRI5udP1CJZBoNDpeQb6fyc-YFarX&s=TrC7_RnKhaDUfRMIONWCRqFJ5-WGsdIBssXS9csQd2k&e=):
- AAP 1.2 = ansible 2.9
- AAP 2.3 = ansible-core 2.14 
- etc.....

Although this community does not support APP , we do use it but we are not Red Hat AAP nor AWX experts to be able to speak to as subject matter experts, most of us run the command line `ansible-playbook` as non-production and then move to AAP for production. I believe you need to upgrade your AAP to get to ansible-core 2.14, if you can not, we can still try to trouble shoot and help you.

As for the command output, what I was trying to share was that in your log I saw the below, notice there are no environment variables , during this ssh connection between Ansible/AAP , the ssh connection will transfer them, I don't see any of the environment variables required for our collection:
```
<111.222.3.444> SSH: EXEC sshpass -d10 scp -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="**UID**"' -o ConnectTimeout=60 -oServerAliveInterval=30 -oTCPKeepAlive=yes -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null '-
oProxyCommand=ssh -i $JH2_SSH_PRIVATE_KEY -W %h:%p -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oProxyCommand='"'"'ssh -i $JH1_SSH_PRIVATE_KEY -W 100.87.2.99:22 -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null autom801@100.79.240.9'"'"' **dummy1**@100.87.2.99' -o ControlPath=/runner/cp/2af7157f79 /home/runner/.ansible/tmp/ansible-local-19nior8rmp/tmp6lvqrqex '[111.222.3.444]:/u/userhome/**UID**/.ansible/tmp/ansible-tmp-1707454010.1091883-25-16688683473242/AnsiballZ_zos_copy.py'
```

Those environment variables are as I shared above which I pulled from my log:
```
EXEC sshpass -d12 ssh -C -o ......<removed as its irrelevant> .....
_BPXK_AUTOCVT=ON 
ZOAU_HOME=/usr/idz/zoautil 
PYTHONPATH=/usr/idz/zoautil/lib
LIBPATH=/usr/idz/zoautil/lib:/usr/pyz/3.10.7/lib:/lib:/usr/lib:. 
PATH=/usr/idz/zoautil/bin:/usr/pyz/3.10.7/bin:/bin:/var/bin 
_CEE_RUNOPTS='"'"'"'"'"'"'"'"'
FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)'"'"'"'"'"'"'"'"' 
_TAG_REDIR_ERR=txt 
_TAG_REDIR_IN=txt 
_TAG_REDIR_OUT=txt 
LANG=C 
PYTHONSTDINENCODING=cp1047
```

This is an old screen capture of how we passed in environment varialbes through inventory, I think this was AAP 1.2 (very old) [here](https://github.com/IBM/z_ansible_collections_samples/blob/main/zos_concepts/user_management/add_remove_user/tower-setup.md#step-3-add-a-new-host-to-inventory--update-existing-host-in-inventory).

The updated AAP docs are [here](https://docs.ansible.com/ansible-tower/latest/html/userguide/job_templates.html) for this same topic.
I hope this helps.

**Comment by richp405** [comment]
closed because of inactivity.

**Comment by Emi-Furubayashi** [comment]
Thanks for your supports, Currently, we are working to meet the conditions that have been pointed out as mandatory. After the response work is completed, we plan to post the continuation as a new QA.
