### ISSUE TITLE
[Documentation] Update docs to reflect that the supported version of z/OS is V2R4 (or later) but prior to version V3R1

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1225]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Documentation issue description

Update the release notes to reflect that the supported versions are V2R4 (or later) but prior to version V3R1.
Update issue types to include selection of V3R1.
Update issue (all) types to reflect latest versions and options.

### IBM z/OS Ansible core Version

None

**Comment by fernandofloresg** [comment]
Fixed by #1226
