### ISSUE TITLE
lab setup to contribute to Ansible/Z

### ISSUE THREAD

**Issue by marcredhat** [ansible-collections/ibm_zos_core#124]
Could you please document what is the easiest way to setup a lab?
1) zD&T does not come with ZOAU; is there an easy/scripted way install ZOAU on zD&T?
2) zTrials?
3) Hercules; is it possible to install ZOAU on Hercules?
4) other?

Thanks,
Marc

**Comment by ddimatos** [comment]
Hello @marcredhat , nice to hear your interest in our offering.

I am looking into this as it aligns with some other work we have been looking into which is outlining the contributors guidelines. 

Are you looking to host a Lab? If so, when would that be?

I ask this because it could change how we might document the request.

**Comment by marcredhat** [comment]
Hello @ddimatos , yes, I have an zD&T EE lab that I can share with other Red Hatters who want to contribute to Ansiblw/Z. 
Just need to install ZOAU.

**Comment by ddimatos** [comment]
Nice!!!

@marcredhat, couple of comments:
Our next IBM z/OS core Galaxy release is coming out in a few weeks , we will require the latest ZOAU 1.0.3 with PTF (program temporary fix), I would recommend we put our focus on getting that version. 

Second comment, would you mind emailing me at  ddimatos@us.ibm.com since you are a RH employee so I can put you in touch with a few of the ZOAU members ? 

Thanks (I reply to email tomorrow).

**Comment by marcredhat** [comment]
**description of the lab**:
- baremetal server with RHEL 8.2/KVM/libvirt

- for zD&T EE, two RHEL 7.9 guests

- on this same baremetal server, OpenShift clusters are deployed (fully automated) using 
  https://github.com/kxr/ocp4_setup_upi_kvm
  **So we have mainframe access (zcEE, z/OSMF etc) from the OpenShift nodes and pods**

- molecule using podman to test on various RHEL 7 and RHEL 8 versions

**Molecule example**
[marc@dell-r730-001 ~]$ pip3 install ansible --user
[marc@dell-r730-001 ~]$ pip3 install virtualenv --user

python3 -m virtualenv molecule_ansible
source molecule_ansible/bin/activate
pip3 install ansible testinfra molecule podman python-vagrant ansible-lint flake8 molecule[lint] molecule[podman]


(molecule_ansible) [marc@dell-r730-001 ~]$ molecule init role marc-role --driver-name podman
--> Initializing new role marc-role...
Initialized role in /home/marc/marc-role successfully.
cd marc-role/molecule/default

Working examples with podman/RHEL7/RHEL8:
wget https://raw.githubusercontent.com/marcredhat/molecule/master/molecule.yml
wget https://raw.githubusercontent.com/marcredhat/molecule/master/verify.yml
cd ../..

NOTE1: you need to be logged in to registry.redhat.io
NOTE2: you need to run "molecule test" as root

(molecule_ansible) [marc@dell-r730-001 marc-role]$ su root
Password:

(molecule_ansible) [root@dell-r730-001 marc-role]# podman  login -u="<user>"   https://registry.redhat.io
Password:
Login Succeeded!


(molecule_ansible) [root@dell-r730-001 marc-role]# MOLECULE_NO_LOG="false" ANSIBLE_SSH_PIPELINING=False molecule test


**OpenShift clusters (fully automated)**
Using https://github.com/kxr/ocp4_setup_upi_kvm you can easily deploy additional clusters with different versions.

This is how I deployed OpenShift 4 in the lab:
As root
echo -e "[main]\ndns=dnsmasq" > /etc/NetworkManager/conf.d/nm-dns.conf
systemctl restart NetworkManager

copy cloud.redhat.com/openshift/install/pull-secret to /root/pull-secret
https://github.com/kxr/ocp4_setup_upi_kvm
git clone https://github.com/kxr/ocp4_setup_upi_kvm.git

[root@dell-r730-001 /]# cat /home/marc/ocp4_setup_upi_kvm/setupocp44stable.sh
./ocp4_setup_upi_kvm.sh --ocp-version 4.4.stable

cat /root/ocp4_setup_ocp4/install_dir/auth/kubeadmin-password


On your laptop, change /etc/hosts so that
console-openshift-console.apps.ocp4.local and
oauth-openshift.apps.ocp4.local
point to 127.0.0.1

sudo ssh -X  root@<baremetal server> -L 443:console-openshift-console.apps.ocp4.local:443

https://console-openshift-console.apps.ocp4.local/
Connect as kubeadmin/<password from cat /root/ocp4_setup_ocp4/install_dir/auth/kubeadmin-password>

cp /root/ocp4_setup_ocp4/oc /usr/bin
cp /root/ocp4_setup_ocp4/install_dir/auth/kubeconfig ~/.kube/config


oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"storage":{"emptyDir":{}}}}'
oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"managementState": "Managed"}}'

Create user / authentication using htpasswd
Follow the steps at
https://github.com/marcredhat/workshop/blob/master/userauth_htpasswd.adoc

Configure AlertManager
Follow the steps at
https://blog.openshift.com/openshift-4-3-alertmanager-configuration/



Optional - Adding KVM guests
virt-manager is installed; RHEL 7.9 and 8.2 ISOs available at var/lib/libvirt/images/; please feel free to add other ISOs.

If you need to, you can ssh to the nodes as follows:
ssh -i /root/ocp4_setup_ocp4/sshkey core@master-1.ocp4.local

As marc or your user:
sudo ssh -X marc@<baremetal server> -L 443:console-openshift-console.apps.ocp4.local:443
sudo usermod --append --groups libvirt `whoami`
virt-manager


**Installed packages**
dnf -y install podman buildah skopeo libvirt*  bind-utils wget tar gcc python3-devel python3  virt-install virt-viewer virt-manager libguestfs-tools-c tmux httpd-tools git x3270-x11 xorg-x11-apps
systemctl start libvirtd.service
systemctl enable libvirtd

**Comment by ddimatos** [comment]
Given we had the introductory presentation and built out a lab for the RHters, I will be closing this. Thanks for this @marcredhat .
