### ISSUE TITLE
Add system to job query response

### ISSUE THREAD

**Issue by mtcohoon** [ansible-collections/ibm_zos_core#125]
##### SUMMARY
When querying jobs with `zos_job_query`, the following four properties are returned per job: `job_id`, `job_name`, `owner`, `ret_code`. This Feature Request asks that a fifth property `system` be returned, containing the system the job ran on / is running on.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`zos_job_query`

##### ADDITIONAL INFORMATION
Having the system returned would be valuable for numerous reasons. One such reason could be taking action against a job returned by `zos_job_query`. A cancel or modify action would require a command routed to the system the job is running on. Currently, there is not a good way to know that system.

**Comment by asifmahmud** [comment]
@mtcohoon Is this kind of what you were looking for?
```
TASK [Response for job query] ********************************
ok: [ec33013a.vmec.svl.ibm.com] => {
    "msg": {
        "changed": false,
        "failed": false,
        "jobs": [
            {
                "job_id": "STC00048",
                "job_name": "INIT",
                "owner": "USRT001",
                "ret_code": null,
                "subsystem": "STL1",
                "system": "EC33013A"
            }
        ],
        "message": ""
    }
}
```

**Comment by blakeinate** [comment]
@mtcohoon is this information that can possibly be obtained using [magic variables?](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#accessing-information-about-other-hosts-with-magic-variables) specifically, `ansible_hostname` and `inventory_hostname` could provide the relevant system information.

**Comment by mtcohoon** [comment]
@asifmahmud -- Yes, that is exactly what was looking for... specifically that `subsystem` property is what I was looking for.

@blakeinate -- I don't think so. Perhaps I used the wrong word with "system." I meant what this project calls `subsystem`. This is another value that SDSF can provide, similar to the other properties in the response. The same job can run on different subsystems at different times, so I think the most appropriate way to get this information is from SDSF, similar to the other properties.

**Comment by blakeinate** [comment]
@mtcohoon I believe this should be a one line change to add this information, as it is already retrieved in the utility used to retrieve job information.

**Comment by asifmahmud** [comment]
@blakeinate Yes, it is a fairly minor change. I can go ahead and open a PR

**Comment by blakeinate** [comment]
Thanks @asifmahmud!

**Comment by mtcohoon** [comment]
Thanks to both!
