### ISSUE TITLE
[Enabler] [zos_job_submit] Correct code path in plugin

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1250]
### Is there an existing issue for this?

- [X] #1721

### Ansible module

zos_job_submit

### Enabler description

The plugin module appears to have competing transfer logic where its using community and zos_copy when it could rely on zos_copy alone.

See [remote_path = self._transfer_file(source_full, tmp_src)](https://github.com/ansible-collections/ibm_zos_core/blob/d739905aa9d4ce13f34e696a4dd1c3638d45130e/plugins/action/zos_job_submit.py#L135) which then goes on to do a [ self._fixup_perms2((tmp, remote_path))](https://github.com/ansible-collections/ibm_zos_core/blob/d739905aa9d4ce13f34e696a4dd1c3638d45130e/plugins/action/zos_job_submit.py#L138) , although `_fixup_perms2` is recommended, I question if its needed based on our modules needs; there is considerable logic in [_fixup_perms2](https://github.com/alibaba/ansible-provider-docs/blob/100b695b0b0c4d8d08af362069557ffc735d0d7e/lib/ansible/plugins/action/__init__.py#L381) that could be helpful  such as `sudo` but still unsure its necessary. 

Then if you see a [zos_copy call a bit further down](https://github.com/ansible-collections/ibm_zos_core/blob/d739905aa9d4ce13f34e696a4dd1c3638d45130e/plugins/action/zos_job_submit.py#L156) , where zos_copy can handle encodings. 

The point is , effort was made to remove the modules dependency on `copy` in lieu of `zos_copy` but still has calls back to the community transfer functions. 

This issus should review the code , decide what should be changed, ideally a solution built on the ibm_zos_core where we control the behavior is optimal but not required. 

![image](https://github.com/ansible-collections/ibm_zos_core/assets/25803172/ca81f384-4f76-40ed-b362-72d87ff60167)

**Comment by richp405** [comment]
Plan to move the remaining community call to zos_copy.  Just reviewing code to make sure there wasn't a reason for it (I don't see one)

**Comment by fernandofloresg** [comment]
This code was fixed in #1786

**Comment by richp405** [comment]
Fernando pointed out that this is now resolved through #1786, which obviated this code change.
