### ISSUE TITLE
[Enabler] [module_utils/data_set.py] Revert extra conditional in DataSet.ensure_present()

### ISSUE THREAD

**Issue by ketankelkar** [ansible-collections/ibm_zos_core#1264]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

ZOAU Tracker - `JIRA-10451`

Expected outcome:
Error messages surfaced from the underlying system should be properly propagated through ZOAU python Exceptions and the conditional to determine when to attempt a re-catalog, which was widened can be narrowed back to its original state to save on unnecessary function calls.

revert from
```python3
if "DatasetVerificationError" in e.msg or "Error Code: 0x4704" in e.msg:
```
to:
```python3
 if "Error Code: 0x4704" in e.msg:
```
[link to code](https://github.com/ansible-collections/ibm_zos_core/blob/73ba2c1174f4e22a4796f9c23072f62ea2ace497/plugins/module_utils/data_set.py#L187)

Context:
As of the creation of this issue (Feb 28, 2024), the `DatasetVerificationError` thrown by the ZOAU python API does not surface any error information from any underlying tools/calls/systems. This behavior primarily stemmed from the migration from the `datasets._create()` function call to the `datasets.create()` function call, where the former throws the `DatasetVerification` Exception while the latter returns a `ZOAUResponse` object, which contained stdout/stderr info. 

The above scenario (and code path) is triggered when the `ensure_present()` function calls `DataSet.create()` for an _existing_ and _un-cataloged_ data set on a particular volume. In this case, the "create" operation is _expected- to fail (and it does) and the appropriate action would be to re-catalog the data set in question. 

`datasets._create()` returns a `ZOAUResponse` Object whose contents are:
```4  BGYSC1402E Dynalloc Failure. Error Code: 0x4704, Information Code: 0x5c```

`datasets.create()` raises a `DatasetVerificationError` whose contents are:
```KETAN.PRIVATE.TESTDS```

The `zos_data_set` module code was recently refactored to call the `create()` function rather than the “hidden” `_create()`, which is how this discrepancy was exposed and why the conditional highlighted needed to be widened.

Recreate (see attached file for `python` script):
- create a data set
- un-catalog data set
- ** attempt to re-create same data set
- with _create()
- with create()
- cleanup
- re-catalog data set
- remove data set

[recreate-no-dynalloc-error-code.py.txt](https://github.com/ansible-collections/ibm_zos_core/files/14441103/recreate-no-dynalloc-error-code.py.txt)

**Comment by richp405** [comment]
Needs validation against zoau 1.3.1
