### ISSUE TITLE
[Enabler] [pipeline] Adopt ZOAU wheels into the share dasd and pipeline

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1276]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

Wheel support has been in place since ZOAU 1.2, this work item is in place to allocate time to migrate from the precompiled binaries to wheels. Below I am sharing the scripts that can help with creating the wheels, directories on the shared DASD should created so they can persist after an IPL. 

ZOAU wheel installation guide:
- https://www.ibm.com/docs/en/zoau/1.2.x?topic=installing-configuring-zoau#python-wheel-installation-method

1. My steps for installing the ZOAU Python modules into the Python Home (where Python is installed):

This requires that the Python be mounted in READ/WRITE so the packages can be placed into Pythons subdirectories; I recommend at this time that you avoid doing this because what I am witnessing is that after a APAR is applied to Python, the user installed packages are not preserved, in other words, any user added files under Python's home are subject to reinstallation after an APAR.

```
export PYTHON_VERSION=3.12
export ZOAU_HOME=/usr/lpp/IBM/zoautil
export PYTHON_HOME=/usr/lpp/IBM/cyp/v3r12/pyz/
                 
export _BPXK_AUTOCVT=ON
export PYTHON=$PYTHON_HOME/bin
export PATH=$PATH:$PYTHON
export PYZ=`echo $PYTHON_VERSION | tr -d '.'`
pip3 install $ZOAU_HOME/zoautil*${PYZ}-none-any.whl
pip3 list
```
 
 
2. This is the second and preferred option for installing the ZOAU Python modules to a specific target.
This option differs from the first option because it does not install into Pythons home directory, the idea here is that by using --target and reinstating PYTHONPATH we can control where the ZOAU Python modules are installed and found. 

PYTHONPATH instructs Python where to look for the python modules, this removes the modules out from the Python home installation so they are not subject to loss during a PTF (still waiting for confirmation on this from Python). Below are shell commands you can use, all you should need to update is the ZOAU_WHEEL_HOME, which should be where you want to manage your wheels:

```
# Script configurations
export PYTHON_VERSION=3.12
export ZOAU_WHEEL_HOME=/tmp/wheels/$PYTHON_VERSION
export ZOAU_HOME=/usr/lpp/IBM/zoautil
export PYTHON_HOME=/usr/lpp/IBM/cyp/v3r12/pyz/

# Create the directory where to install the wheels
export DIR_PERMISSIONS=755
mkdir $ZOAU_WHEEL_HOME
chmod $DIR_PERMISSIONS $ZOAU_WHEEL_HOME
 
# Shell exports needed by python to run the pip command
export _BPXK_AUTOCVT=ON
export PYTHON=$PYTHON_HOME/bin
export PATH=$PATH:$PYTHON
export PYZ=`echo $PYTHON_VERSION | tr -d '.'`

# Pip install the zoau libs using --target where the target is defined by $ ZOAU_WHEEL_HOME
pip3 install --target $ZOAU_WHEEL_HOME $ZOAU_HOME/zoautil*${PYZ}-none-any.whl
 
# Optional, just to be sure the wheels installed
export PYTHONPATH=/tmp/wheels
pip3 list
```
 
Once yo have installed the wheels using target, add PYTHONPATH back to the environment variables so python knows where to find the wheels:
```
environment_vars:
  _BPXK_AUTOCVT: "ON"
  ZOAU_HOME: "{{ ZOAU }}"
  PYTHONPATH: "/tmp/wheels/3.12"
  LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
  PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin:/var/bin"
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_ERR: "txt"
  _TAG_REDIR_IN: "txt"
  _TAG_REDIR_OUT: "txt"
  LANG: "C"
  PYTHONSTDINENCODING: "cp1047"
 ```
 
3. I have also included a playbook which can perform the second option using pip3 --target .

In the playbook modify:
-  hosts: zvm to your host
- consider changing where wheel is installed by changing export ZOAU_WHEEL_HOME=/tmp/wheels/3.12

```

---
- hosts: zvm
  collections:
    - ibm.ibm_zos_core
  gather_facts: false

  environment: "{{ environment_vars }}"

  tasks:
    - name: Run pip3 commands
      raw: |
        export _BPXK_AUTOCVT=ON;
        export PYTHON_VERSION=3.12;
        export ZOAU_WHEEL_HOME=/tmp/wheels/$PYTHON_VERSION;
        export ZOAU_HOME=/usr/lpp/IBM/zoautil;
        export PYTHON_HOME=/usr/lpp/IBM/cyp/v3r12/pyz/;
        export DIR_PERMISSIONS=755;
        mkdir $ZOAU_WHEEL_HOME;
        chmod $DIR_PERMISSIONS $ZOAU_WHEEL_HOME;
        export PYTHON=$PYTHON_HOME/bin;
        export PATH=$PATH:$PYTHON;
        export PYZ=`echo $PYTHON_VERSION | tr -d '.'`;
        pip3 install --target $ZOAU_WHEEL_HOME $ZOAU_HOME/zoautil*${PYZ}-none-any.whl;
        export PYTHONPATH=/u/wheels;
        pip3 list;
        pip3 show zoautil-py;
      args:
        executable: /bin/sh
      register: result

    - name: Results
      debug:
        var: result
      ignore_errors: True
```

**Comment by ddimatos** [comment]
Suggest the first design for the shared DASD ZOAU wheels, it has the drawback that after we apply a fix we lose the wheels but a simple script can reinstall. The second design will not have the issues of losing the wheel, but wheels will need cleaning up. 

```
/zoau/
     |
     +-> v1.3.0/
     |
     +-> v1.3.1/
     |
     +-> v1.3.2/
     |
     +-> wheels/
     		   +->v1.3.0/
               |        |
               |        +->3.10/
               |        |
               |        +->3.11/
               |        |
               |        +->3.12/
               |
               +->/v1.3.1/
               |         |
               |         +->3.10/
               |         |
               |         +->3.11/
               |         |
               |         +->3.12/
               |
               +->/v1.3.2/
                         |
                         +->3.10/
                         |
                         +->3.11/
                         |
                         +->3.12/
               
                      
/zoau/
     |
     +-> v1.3.0 
     |		  |
	 |	      +-> wheels/
	 |				    |
	 |				    +->3.10/
	 |				    |
	 |				    +->3.11/
	 |				    |
	 |				    +->3.12/
     +-> v1.3.1 
	 |		  |
	 |	      +-> wheels/
	 |				    |
	 |				    +->3.10/
	 |				    |
	 |				    +->3.11/
	 |				    |
	 |				    +->3.12/
     +-> v1.3.2 
     		  |
			  +-> wheels/
						|
						+->3.10/
						|
						+->3.11/
						|
						+->3.12/
```

**Comment by richp405** [comment]
I'll run a test experiment tomorrow on 01132.  I tend to agree with the first wheel architecture, so all the wheels are in one shared folder for resets.  From earlier notes, I don't think we could used /tmp/whatever, because that will be lost in IPL's.

So, based on the notes, I'm assuming ONLY 3.10, 3.11 and 3.12 python will be used.  The tricky part will be preserving the environment for 1.2.x zoau (maybe a secondary version switch...need to think on that.)

I'll start a Jenkinsfile6J branch tomorrow.

**Comment by richp405** [comment]
All the wheels built (3 pythons in 3 zoau's) in a wheels folder.  I will test the environment manually, and when it works, I'll put the change into 6J pipeline

**Comment by richp405** [comment]
Here is the reworked environment as a shell.
export _BPXK_AUTOCVT=ON

export PYTHON_VER_MA=3
export PYTHON_VER_MI=12
export PYTHON_VERSION=$PYTHON_VER_MA.$PYTHON_VER_MI
export ZOAU_VERSION=v1.3.2.0
export ZOAU_WHEEL_HOME=/zoau/wheels/$ZOAU_VERSION/$PYTHON_VERSION
export ZOAU_HOME=/zoau/$ZOAU_VERSION
export PYTHON_HOME=/allpython/$PYTHON_VERSION/usr/lpp/IBM/cyp/v${PYTHON_VER_MA}r${PYTHON_VER_MI}/pyz/

export PYTHON=$PYTHON_HOME/bin
export PATH=$PYTHON:$PATH

export PYTHONPATH=/zoau/wheels/$ZOAU_VERSION/$PYTHON_VERSION

export LIBPATH=$PYTHON_HOME/lib:$ZOAU_HOME/lib:$LIBPATH:/lib:/usr/lib:.
export PATH=$PYTHON_HOME/bin:$ZOAU_HOME/bin:/bin:/usr/lpp/rsusr/ported/bin:/var/bin:/usr/lpp/rsusr/ported/bin:/usr/lpp/java/java180/J8.0_64/bin:/bin:.
export ZOAU=$ZOAU_HOME/bin


I worked through this manually.  Will try in a pipeline next.

**Comment by richp405** [comment]
consolidated list, as used in pipeline:

_BPXK_AUTOCVT: "ON"
_CEE_RUNOPTS: "'FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)'"
_TAG_REDIR_ERR: txt
_TAG_REDIR_IN: txt
_TAG_REDIR_OUT: txt
LANG: C
PYTHON_VER_MA: 3
PYTHON_VER_MI: 12
PYTHON_VERSION: $PYTHON_VER_MA.$PYTHON_VER_MI
ZOAU_VERSION: v1.3.2.0
ZOAU_WHEEL_HOME: /zoau/wheels/$ZOAU_VERSION/$PYTHON_VERSION
ZOAU_HOME: /zoau/$ZOAU_VERSION
PYTHON_HOME: /allpython/$PYTHON_VERSION/usr/lpp/IBM/cyp/v${PYTHON_VER_MA}r${PYTHON_VER_MI}/pyz/
PYTHON: $PYTHON_HOME/bin
PYTHONPATH: /zoau/wheels/$ZOAU_VERSION/$PYTHON_VERSION
LIBPATH: $PYTHON_HOME/lib:$ZOAU_HOME/lib:$LIBPATH:/lib:/usr/lib:.
PATH: $PYTHON_HOME/bin:$ZOAU_HOME/bin:/bin:/usr/lpp/rsusr/ported/bin:/var/bin:/usr/lpp/rsusr/ported/bin:/usr/lpp/java/java180/J8.0_64/bin:/bin:.
ZOAU: $ZOAU_HOME/bin
ZOAU_ROOT: $ZOAU_HOME
ZOAUTIL_DIR: $ZOAU_HOME
PATH: $ZOAU_HOME/bin:$PYTHON:/usr/sbin:/var/bin:/usr/lpp/java/java180/J8.0_64/bin:/bin
PYTHONSTDINENCODING: "cp1047"

I'll work through the use of the new variable values.

**Comment by richp405** [comment]
Works manually... should have 5J script working tomorrow morning.

**Comment by richp405** [comment]
zoau.1.0.1.ga now includes the wheels master folder for zoau 1.3.x and python 10/11/12. script will be distributed during holiday break.
