### ISSUE TITLE
[Documentation] [zos_ping] Update docs to include the scp legacy option `-O`

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1281]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Documentation issue description

The zos_ping module action plugin requires scp over sftp, this is because the module is then transferred to the managed node as its default encoding, eg EBCDIC. Because the zos_ping module is a REXX program , it itself is the file being transferred over the Ansible ssh connection that needs to be converted to the native encoding to run. 

 OpenSSH_9.0 or later, scp will be switching scp calls with sftp , thus we decided not to support scp . You can see that depreciation in the release notes here: https://www.openssh.com/txt/release-9.0
```
This release switches scp(1) from using the legacy scp/rcp protocol to using the SFTP protocol by default.
```

The documentation should explain that if OpenSSH 9 or later is used with zos_ping the legacy option `-O` will need to be added to the SSh options, eg:
```
[ssh_connection]
transfer_method = scp
scp_extra_args="-O"
```

Additional info:

To determine your OpenSSH version below are a couple of examples:
MacOS:
```
$ ssh -V
OpenSSH_9.0p1, LibreSSL 3.3.6
```
Ubuntu:
```
$ ssh -V
OpenSSH_8.9p1 Ubuntu-3ubuntu0.5, OpenSSL 3.0.2 15 Mar 2022
```
### IBM z/OS Ansible core Version

v1.8.0 (default)

### Ansible module

zos_ping

**Comment by ehrocha** [comment]
Works on Ubuntu 23.11 :D Been trying to make this work since yesterday.

**Comment by ddimatos** [comment]
> Works on Ubuntu 23.11 :D Been trying to make this work since yesterday.

Are you still struggling, if you are using **less** than `OpenSSH_9.0`, it should not require any change, `OpenSSH_9.0` or later will require the legacy fallback to `scp` which will transfer the REXX as EBCDIC encoded ready to execute on z/OS. That can be done by adding to ansible.cfg:
```
[ssh_connection]
transfer_method = scp
scp_extra_args="-O"
```

Off hand I don't know of any other options, I suppose we could in the future look at invoking a raw connection as the source is being transferred and converting it to the encoding using the SFTP transport simplifying the user experience.

**Comment by ehrocha** [comment]
Hello @ddimatos, thanks for checking, and yes, I am using OpenSSH > 9 :
OpenSSH_9.3p1 Ubuntu-1ubuntu3.2, OpenSSL 3.0.10 1 Aug 2023

Things are going smoothly now, I should have elaborated a little more on my comment.

**Comment by ddimatos** [comment]
<img width="782" alt="image" src="https://github.com/ansible-collections/ibm_zos_core/assets/25803172/fd37a494-b311-491b-8654-3c76779406a1">
