### ISSUE TITLE
Automate passing password to prompt for data transfers

### ISSUE THREAD

**Issue by alex-diss** [ansible-collections/ibm_zos_core#130]
##### SUMMARY

With data transfer modules (e.g. zos_fetch, zos_copy), using `--ask-pass` or passing an `ansible_password` still prompts for a user password on those modules. It would be useful if the provided password could be passed automatically to avoid the prompt.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`zos_fetch`, `zos_copy`

##### ADDITIONAL INFORMATION

If implemented, this feature would help to further automate processes using these modules when using a userid+password, as the user wouldn't need to re-enter their password on each use of these modules. One example is use with continuous integration tools such as Jenkins.

**Comment by ddimatos** [comment]
Thank you for the request, we will be looking into this and reporting back.

**Comment by ddimatos** [comment]
We have scheduled this work to start on **9/14/20** (if things go well, it could be sooner), tracked by our work item number **2792**. 

We will look into the effort needed to address the prompts that occur when using `zos_fetch` and `zos_copy` with adhoc option `--ask-pass` and report back.

**Comment by asifmahmud** [comment]
Automatic avoidance of the prompt when using `--ask-pass` would require quite a significant re-write of the data transfer methods used for zos_copy and zos_fetch. These modules use sFTP for data transfer internally to preserve data encoding when transferring to/from z/OS.

Even if `ansible_password` is defined, it would need to be passed to sFTP at runtime. There is currently no secure way to do this without requiring the user to install additional programs on the controller.

One option is to use `sshpass`, which is not a native Unix/Linux program and will need to be installed.

Another is to use `expect` to specify a password, but it is not secure at all and the password will likely be exposed on the terminal log. It is also an external program that needs to be installed.

Unless we completely change how we handle data transfer for copy/fetch, then it is highly recommended to use SSH keys for authentication.

**Comment by ddimatos** [comment]
Thank you for reporting this @alex-diss, I do agree with @asifmahmud.

At this point, our preferred Ansible controller authentication with the Ansible target is through passwordless authentication using SSH keys. I am under the impression that interactive Ansible sessions with the target are a small number and likely experimenting with the offering and when deploying this in a any enterprise fashion either through scripting, AWX or Tower, our preferred authentication would be adopted thus lowering the priority of such a feature. 

It has been put in our backlog for tracking with no plan to fix anytime soon, thus closing this issue for now. 

That said, soon we will be accepting contributions and would really be great if the community would like to help out.

**Comment by ddimatos** [comment]
Reopened, alpha install included in the [PR here](https://github.com/ansible-collections/ibm_zos_core/pull/286)

**Comment by ddimatos** [comment]
This was fixed in ibm_zos_core version 1.4.0.-beta.1. 
See release notes [here](https://ibm.github.io/z_ansible_collections_doc/ibm_zos_core/docs/source/release_notes.html#what-s-new)


zos_copy was enhanced to support the ansible.builtin.ssh connection options; for further reference refer to the [SSH plugin](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/ssh_connection.html) documentation.
