### ISSUE TITLE
[Enabler] Test cases failing with latest case sensitivity changes to zos_data_set module

### ISSUE THREAD

**Issue by fernandofloresg** [ansible-collections/ibm_zos_core#1317]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Bug description

Currently some test cases will fail because zos_data_set `type` and `record_format` option is now case sensitive, hence getting errors when using `type='pds'` or `record_format='fba'` instead of `type='PDS'` or `record_format='FBA'` respectively.

Will document here the different occurrences for each test file I find.
test_zos_archive_func.py - use of type="member" in multiple test cases.
test_zos_backup_restore_func.py - use of type="seq"
test_zos_blockinfile_func.py - use of type="member"
test_zos_encode_func.py - use of type="seq",type="pds",type="member"
test_zos_fetch_func.py - use of type="member"
test_zos_find_func.py - use of type="seq", type="pds"
test_zos_job_submit_func.py - use of type="pds"
test_zos_lineinfile_func.py - use of type = "member"
test_zos_mount_func.py - use of type="pdse", record_format="fba"
test_zos_mvs_raw_func.py - use of type="pdse", record_format="fb", space_type="m"
test_zos_unarchive_func.py - use of type="member"
test_zos_volume_init_func.py - use of type='pds'

### IBM z/OS Ansible core Version

v1.10.0-beta.1

### IBM Z Open Automation Utilities

v1.2.5 (default)

### IBM Enterprise Python

v3.11.x (default)

### ansible-version

v2.16.x (default)

### z/OS version

v2.5 (default)

**Comment by rexemin** [comment]
Cancelling this issue due to #1360.
