### ISSUE TITLE
[Enabler] [ac] Update ac tool to use ansible-lint 6.22

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1325]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

In order to allow for development easy offline testing , update ac tool to use ansible-lint 6.22

**Comment by ddimatos** [comment]
Increasing the size as it ended up needing additional changes to several scripts, I also updated the `.ac` tool to support more than RSA certs, fixed a script issues location awareness that resulting in error when run from another script, added a env for 2.17.

**Comment by fernandofloresg** [comment]
Fixed by #1484
