### ISSUE TITLE
[Enabler] Create a started task to replace the one use on the zVMs

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1329]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

Actual support for started tasks has never been stated yet we do perform some periodic testing , this is mainly because the responses for started tasks are different than jobs and would need a code path of their own. No matter, the test suites to include some started task testing , usually using an existing on on the zVMs such as `STC00002` , the idea here is to not use one on the system to allow for test case portability onto another system.

This is is so that time is spent creating a started task and integrating that into our test suite, with a START and STOP.

**Comment by ddimatos** [comment]
This is being handled by https://github.com/ansible-collections/ibm_zos_core/issues/1591

**Comment by richp405** [comment]
closed as duplicate.
