### ISSUE TITLE
Ansible with Z Open Automation Utilities on z/OS

### ISSUE THREAD

**Issue by WladyslawBorysow** [ansible-collections/ibm_zos_core#139]
##### SUMMARY
I am testing Ansible 2.9.9 with z/OS as managed node. I also installed ZOA 1.0.3, but it seems ZOA commands from Ansible fail. "Normal" shell commands work well. I don't know if this is a bug or I am unable to issue this command properly.
Thank You!

##### ISSUE TYPE
- Bug Report???

##### COMPONENT NAME
ibm.ibm_zos_core
shell: "zoaversion"

##### ANSIBLE VERSION
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/zpdt/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

##### CONFIGURATION
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 25

##### OS / ENVIRONMENT
z/OS 2.4
Rocket Python 3.6.1
ZOA V1.0.3

##### STEPS TO REPRODUCE
this works fine:
---
- hosts: all
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"

  tasks:
     - name: issue shell command
       shell: "ls -l"
       register: result
     - name: response
       debug:
         msg: " {{ result }} "

doesn't work:
---
- hosts: all
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"
  tasks:
  - name: test
    shell: "zoaversion"
    register: result
  - name: Response
    debug:
     msg: "Output from command is {{ result }}"

fatal: [zpm]: FAILED! => {"changed": true, "cmd": "zoaversion", "delta": "0:00:02.762870", "end": "2020-07-14 12:37:33.010991", "msg": "non-zero return code", "rc": 1, "start": "2020-07-14 12:37:30.248121", "stderr": "FSUM7341 bad file descriptor \"0\"", "stderr_lines": ["FSUM7341 bad file descriptor \"0\""], "stdout": "", "stdout_lines": []}

##### EXPECTED RESULTS
I wanted to have output from ZOA command utilities

##### ACTUAL RESULTS
["FSUM7341 bad file descriptor \"0\""], "stdout": "", "stdout_lines": []}

```

**Comment by blakeinate** [comment]
Hi @WladyslawBorysow , would you be able to provide the variables in your group_vars/all.yml file?

**Comment by WladyslawBorysow** [comment]
Hello Blake,

environment_vars:
       _BPXK_AUTOCVT: "ON"
       ZOAU_HOME: "/var/zoa/ZOA102/usr/lpp/IBM/zoautil"
       PYTHONPATH: "/var/zoa/ZOA102/usr/lpp/IBM/zoautil/lib/"
       LIBPATH: "/var/zoa/ZOA102/usr/lpp/IBM/zoautil/lib/:/rsusr/rocket/python-2017-04-12-py36/python36/lib:/usr/lib:/lib:."
       PATH: "/var/zoa/ZOA102/usr/lpp/IBM/zoautil/bin:/rsusr/rocket/python-2017-04-12-py36/python36/bin:/bin"
       _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
       _TAG_REDIR_ERR: "txt"
       _TAG_REDIR_IN: "txt"
       _TAG_REDIR_OUT: "txt"
       LANG: "C"

Thank you!

**Comment by blakeinate** [comment]
Hi @WladyslawBorysow , just to verify, you are using ZOAU 1.0.3 correct? I notice the ZOAU paths have `ZOA102` in the name.

I am unable to reproduce the exact behavior, but do have another customer reporting the same issue. Can you run your playbook with `-vvv` and provide the output? It might give some clues as to what is going wrong

**Comment by WladyslawBorysow** [comment]
Hello Blake,


[zpdt@oc4720374184 playbooks]$ ansible-playbook test9.yaml -vvv
ansible-playbook 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/zpdt/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Parsed /etc/ansible/hosts inventory source with yaml plugin

PLAYBOOK: test9.yaml ************************************************************************************************************************************************************************
1 plays in test9.yaml

PLAY [all] **********************************************************************************************************************************************************************************
META: ran handlers

TASK [issue shell command] ******************************************************************************************************************************************************************
task path: /etc/ansible/playbooks/test9.yaml:9
Using module file /usr/lib/python2.7/site-packages/ansible/modules/commands/command.py
Pipelining is enabled.
<10.1.1.2> ESTABLISH SSH CONNECTION FOR USER: pl25816
<10.1.1.2> SSH: EXEC sshpass -d8 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=1023 -o 'User="pl25816"' -o ConnectTimeout=10 -o ControlPath=/home/zpdt/.ansible/cp/1498b269d5 10.1.1.2 '/bin/sh -c '"'"'_BPXK_AUTOCVT=ON LANG=C _TAG_REDIR_IN=txt ZOAU_HOME=/var/zoa/ZOA102/usr/lpp/IBM/zoautil PYTHONPATH=/var/zoa/ZOA102/usr/lpp/IBM/zoautil/lib/ _TAG_REDIR_OUT=txt _CEE_RUNOPTS='"'"'"'"'"'"'"'"'FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)'"'"'"'"'"'"'"'"' PATH=/var/zoa/ZOA102/usr/lpp/IBM/zoautil/bin:/rsusr/rocket/python-2017-04-12-py36/python36/bin:/bin LIBPATH=/var/zoa/ZOA102/usr/lpp/IBM/zoautil/lib/:/rsusr/rocket/python-2017-04-12-py36/python36/lib:/usr/lib:/lib:. _TAG_REDIR_ERR=txt /rsusr/rocket/python-2017-04-12-py36/python36/bin/python3.6 && sleep 0'"'"''
<10.1.1.2> (1, '\n{"msg": "non-zero return code", "cmd": "zoaversion", "stdout": "", "stderr": "FSUM7341 bad file descriptor \\"0\\"", "rc": 1, "start": "2020-07-17 08:38:51.756316", "end": "2020-07-17 08:38:52.134747", "delta": "0:00:00.378431", "changed": true, "failed": true, "invocation": {"module_args": {"_uses_shell": true, "_raw_params": "zoaversion", "warn": true, "stdin_add_newline": true, "strip_empty_ends": true, "argv": null, "chdir": null, "executable": null, "creates": null, "removes": null, "stdin": null}}}\n', '')
<10.1.1.2> Failed to connect to the host via ssh:
fatal: [zpm]: FAILED! => {
    "changed": true,
    "cmd": "zoaversion",
    "delta": "0:00:00.378431",
    "end": "2020-07-17 08:38:52.134747",
    "invocation": {
        "module_args": {
            "_raw_params": "zoaversion",
            "_uses_shell": true,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2020-07-17 08:38:51.756316",
    "stderr": "FSUM7341 bad file descriptor \"0\"",
    "stderr_lines": [
        "FSUM7341 bad file descriptor \"0\""
    ],
    "stdout": "",
    "stdout_lines": []
}


Regarding ZOA it is for sure 1.0.3, but guys from IBM GSD (internal standard of packaging and delivery) didn't change it's path name.

# zoaversion
2020/05/06 18:17:13 CUT V1.0.3

May I have one more question?

Do I have to set different vars on the mainframe LPAR (in etc/profile), or Ansible will handle this with environment vars in the playbook? I did some tests and it seems I don't have to set any vars in etc/profile on LPAR.

**Comment by blakeinate** [comment]
Hi @WladyslawBorysow , Ansible controls the environment variables used during execution, your z/OS system profile should have no impact on the final result.

I worked with another user yesterday and we were able to resolve the same issue you are encountering by upgrading ZOAU to the latest PTF `UI70435`

**Comment by WladyslawBorysow** [comment]
Hello Blake,
Thank you! I will try it after my vacation. For now I will close the issue since I will be on vacation for 2 weeks. If the solution won't work I will let you know. 
regards,
