### ISSUE TITLE
[Enabler] [Demo] Prepare material to present the zos_script module to the Ansible Guild

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1395]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

Prepare charts and a live demo for the Ansible Guild. 
A few intro charts, eg why the zos_script module, what can it do differently the the community module, demo and some time for feedback or future ideas. 

Z Ansible guild call dates : 

May 8th
June 12th
July 10th
August 14th

### Ansible module

zos_script

**Comment by fernandofloresg** [comment]
completed by June 12 demo
