### ISSUE TITLE
[Enabler] [Demo] Prepare material to present the  zos_archive and zos_unarchive  module to the Ansible Guild 

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1396]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

Prepare charts and a live demo for the Ansible Guild.
A few intro charts, eg about the modules, what can it do differently the the community modules, demo and some time for feedback or future ideas.

Z Ansible guild call dates : 

May 8th
June 12th
July 10th
August 14th
Sept 11th
Oct 9th
Nov 13th
Dec 11th

### Ansible module

zos_archive, zos_unarchive

**Comment by fernandofloresg** [comment]
Presented this today.
