### ISSUE TITLE
[Enabler] [Demo] Prepare material to present the zos_volume_init module to the Ansible Guild

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1397]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

Prepare charts and a live demo for the Ansible Guild.
A few intro charts, eg about the module, what can it do, demo and some time for feedback or future ideas.

Z Ansible guild call dates : 

May 8th
June 12th
July 10th
August 14th

### Ansible module

zos_volume_init

**Comment by ketankelkar** [comment]
I'm planning on just pressing "play" on the video (#574  and answering any questions afterwards
