### ISSUE TITLE
zos_job_submit does not accept special characters on src parameter

### ISSUE THREAD

**Issue by bmjunior** [ansible-collections/ibm_zos_core#148]
##### SUMMARY
Calling zos_job_submit using PDS source like this:
    - name: Submit job to extract CIRATS missing
      zos_job_submit:
        src: RTSGM.MAINT.EUE4.CNTL(####REQ3)
        location: DATA_SET
        max_rc: 4
        wait: true
        wait_time_s: 30
      register: job_result
we get this error message:
fatal: [meue4.vipa.uk.ibm.com]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "encoding": null,
            "from_encoding": "ISO8859-1",
            "location": "DATA_SET",
            "max_rc": 4,
            "return_output": true,
            "src": "RTSGM.MAINT.EUE4.CNTL(####REQ3)",
            "temp_file": null,
            "to_encoding": "IBM-1047",
            "volume": null,
            "wait": true,
            "wait_time_s": 30
        }
    },
    "msg": "The parameter src for data set is not a valid name pattern. Please check the src input."
}
but PDS member exists:
 BROWSE    RTSGM.MAINT.EUE4.CNTL(####REQ3) - 01.62  Line 0000000000 Col 001 080
********************************* Top of Data **********************************
//BLD1PREC JOB (BRRW1121),'R3S',CLASS=H,REGION=0M,                      00010016

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zos_job_submit on zos_ibm_core collection at version 1.2.0-beta.1

##### ANSIBLE VERSION

```paste below
ansible 2.9.10
  config file = /home/bmjr/ansible/cirats/ansible.cfg
  configured module search path = ['/home/bmjr/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/bmjr/ansible/cirats/ansible.cfg) = True
DEFAULT_FORKS(/home/bmjr/ansible/cirats/ansible.cfg) = 25
DEFAULT_MANAGED_STR(/home/bmjr/ansible/cirats/ansible.cfg) = Ansible managed
DEFAULT_REMOTE_USER(/home/bmjr/ansible/cirats/ansible.cfg) = br11920
DEFAULT_TIMEOUT(/home/bmjr/ansible/cirats/ansible.cfg) = 60
```

##### OS / ENVIRONMENT

target OS is zOS 2.3

##### STEPS TO REPRODUCE

```yaml
    - name: Submit job to extract CIRATS missing
      zos_job_submit:
        src: RTSGM.MAINT.EUE4.CNTL(####REQ3)
        location: DATA_SET
        max_rc: 4
        wait: true
        wait_time_s: 30
      register: job_result
```

##### EXPECTED RESULTS

JOB submit to JES

##### ACTUAL RESULTS

module refuse src parameter

```paste below
fatal: [meue4.vipa.uk.ibm.com]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "encoding": null,
            "from_encoding": "ISO8859-1",
            "location": "DATA_SET",
            "max_rc": 4,
            "return_output": true,
            "src": "RTSGM.MAINT.EUE4.CNTL(####REQ3)",
            "temp_file": null,
            "to_encoding": "IBM-1047",
            "volume": null,
            "wait": true,
            "wait_time_s": 30
        }
    },
    "msg": "The parameter src for data set is not a valid name pattern. Please check the src input."
}
```

**Comment by blakeinate** [comment]
Hi @bmjunior, thanks for notifying us of this issue. I will make an update momentarily

**Comment by blakeinate** [comment]
I am opening up a pull request to fix this issue, in case you need this issue fixed before our next release, I am attaching a build with the updates that should allow special characters in data set names.

[ibm-ibm_zos_core-1.2.0-beta.1.tar.gz](https://github.com/ansible-collections/ibm_zos_core/files/5023370/ibm-ibm_zos_core-1.2.0-beta.1.tar.gz)

You can install this collection build using
```
ansible-galaxy collection install ibm-ibm_zos_core-1.2.0-beta.1.tar.gz --force
```
From the directory which contains the gzip.

**Comment by bmjunior** [comment]
Update tested and worked perfectly.
Closing issue.
Thanks.
