### ISSUE TITLE
[Enabler][Z Trial] (1) Scenario ALL - Move current scenario 4 to 6

### ISSUE THREAD

**Issue by fernandofloresg** [ansible-collections/ibm_zos_core#1576]
This task is a part of epic: #1523 

### Enabler description
As a developer I want to move Z Trial scenario 4 to the last position such that other scenarios can be highlighted instead.

### Tasks
- [x] rename the folder (?)

Note- this task does not involve updating any playbook files, updating any guide, or "refreshing" the scenario in any other way beyond re-numbering it.

**Comment by richp405** [comment]
will send not to Jenny today

**Comment by ketankelkar** [comment]
- The initial mechanics of the move are completed. Any additional last-minute edits will be captured in #1708
