### ISSUE TITLE
[Enabler][Z Trial] (4) Scenario 1 - First Draft refresh for the zos ping scenario

### ISSUE THREAD

**Issue by fernandofloresg** [ansible-collections/ibm_zos_core#1578]
This task is a part of epic: #1523 

### Enabler description

As a user I want to have a walkthrough Z Trial scenario that incorporates ZOAU wheel installation and uses the most current ping playbook available.

### Tasks
- [x] pull the latest version of the playbook
- [x] run the playbook in the dev environment
- [x] write/update the guide
- [x] take the screenshots

**Comment by richp405** [comment]
This was accidentally linked to an unrelated fix.  Re-opening

**Comment by richp405** [comment]
There is a character issue in zos_ping... need to check my notes on how to fix it.

**Comment by ketankelkar** [comment]
- This work will be continued in #1702
