### ISSUE TITLE
[Enabler][Z Trial] (5) Scenario 2 - Refresh data set scenario

### ISSUE THREAD

**Issue by fernandofloresg** [ansible-collections/ibm_zos_core#1579]
This task is a part of epic: #1523 

### Enabler description

Since last Z trial update there have been changes to the modules interfaces, goal is to update the Z Trial data set scenario to have the latest.
As a user I want to have the most current playbooks available for these existing walkthroughs.

### Tasks
- [x] pull the latest version of the playbook
- [x] run the playbook in the dev environment
- [x] write/update the guide
- [x] take the screenshots

**Comment by richp405** [comment]
This is basically done, ion terms of getting the playbook running on 3.1 host.  Please verify screen shots are correct (I'm pretty sure several will need updating).
