### ISSUE TITLE
[Enabler][Z Trial] (5) Scenario 3 - First Draft refresh for the job management scenario

### ISSUE THREAD

**Issue by fernandofloresg** [ansible-collections/ibm_zos_core#1581]
This task is a part of epic: #1523 

### Enabler description

Since last Z trial update there have been changes to the modules interfaces, goal is to update the Z Trial data set scenario to have the latest.
As a user I want to have the most current playbooks available for these existing walkthroughs.

### Tasks
- [x] pull the latest version of the playbook
- [x] run the playbook in the dev environment
- [x] write/update the guide
- [x] take the screenshots

**Comment by richp405** [comment]
I found a few bugs in jcl and the playbook... down to the last 3 steps, so you should have something usable mid-week.
