### ISSUE TITLE
[Enabler][Portability] [zos_volume_init] Ensure test suite portability by removing hard coded data.

### ISSUE THREAD

**Issue by fernandofloresg** [ansible-collections/ibm_zos_core#1589]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description
This issue is tracked by epic: [[Epic][Portability] Ensure test suite execution portability & parallelism.](https://github.com/ansible-collections/ibm_zos_core/issues/1585)

#### Issue:
In order to ensure test portability and parallel execution we need to remove data set names and user names that are hardcoded.
In this test the following needs to be removed:

- [ ] Use of IMSTESTL hlq data sets.

### Ansible module

zos_volume_init

**Comment by AndreMarcel99** [comment]
This item will be move for the 2.12 because the change from ZOAU came on 1.3.3
