### ISSUE TITLE
Unsupported parameters for (zos_data_set) module: record_format 

### ISSUE THREAD

**Issue by phil34130** [ansible-collections/ibm_zos_core#159]
i run this collecion playbook:
ansible-playbook zos-collection-sample.yml  -i tx9.yml -vvv
and i get a failure:
TASK [Create a PDS data set PRICHAR.SOME.DATA.SET] *************************************************************************
task path: /root/zos-collection-sample.yml:182
Using module file /root/.ansible/collections/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_data_set.py
Pipelining is enabled.
<9.212.128.238> ESTABLISH SSH CONNECTION FOR USER: prichar
<9.212.128.238> SSH: EXEC sshpass -d11 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'User="prichar"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/0f414172fb 9.212.128.238 '/bin/sh -c '"'"'ZOAU_HOME=/usr/lpp/IBM/zoautil PATH=/usr/lpp/IBM/zoautil/bin:/bin:. LIBPATH=/usr/lpp/IBM/zoautil/lib:/usr/local/rocket/py36/python-2017-04-12-py36/python36/lib:/lib:/usr/lib:. PYTHONPATH=/usr/lpp/IBM/zoautil/lib _BPXK_AUTOCVT=ON /usr/local/rocket/py36/python-2017-04-12-py36/python36/bin/python && sleep 0'"'"''
<9.212.128.238> (1, b'\n{"msg": "Unsupported parameters for (zos_data_set) module: record_format Supported parameters include: batch, data_class, format, name, record_length, replace, size, state, type, volume", "failed": true, "invocation": {"module_args": {"name": "PRICHAR.SOME.DATA.SET", "type": "pds", "size": "5M", "record_format": "fb", "record_length": 25, "replace": true}}}\n', b'')
<9.212.128.238> Failed to connect to the host via ssh: 
fatal: [9.212.128.238]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "name": "PRICHAR.SOME.DATA.SET",
            "record_format": "fb",
            "record_length": 25,
            "replace": true,
            "size": "5M",
            "type": "pds"
        }
    },
    "msg": "Unsupported parameters for (zos_data_set) module: record_format Supported parameters include: batch, data_class, format, name, record_length, replace, size, state, type, volume"
}

i would have assumed from https://ansible-collections.github.io/ibm_zos_core/modules/zos_data_set.html, that record_format was also supported...
looks like it is not.
I am using ZOAU 1.0.3 with PTF2 (using SMP/E), and i have PYTHON 3.6 on the host (from rocket): could this be the reason ? as the version of /usr/lpp/IBM/zoautil/lib/zoautil_py/python36/Datasets.so looks different from /usr/lpp/IBM/zoautil/lib/zoautil_py/python36/Datasets.so
Si need to change record_format to format to get it to work, as shown here 👍 
 https://www.ibm.com/support/knowledgecenter/SSKFYE_1.0.3/python_doc_zoautil/api/datasets.html?view=embed

Everything else in the playbook seems to work ok

**Comment by asifmahmud** [comment]
Hi @phil34130 , I think you might have an older version of the z/OS core collection. If you notice in the output:
```
Supported parameters include: batch, data_class, format, name, record_length, replace, size, state, type, volume"
```
You can try changing `record_format` to `format` in your playbook.

**Comment by bmjunior** [comment]
This works for me:

**Comment by bmjunior** [comment]
- name: Allocate remote sequential dataset
      zos_data_set:
        name: '{{ds_holdcard }}'
        type: SEQ
        space_primary: 2
        space_type: TRK
        record_format: FB
        record_length: 80
        block_size: 6080
        replace: yes

maybe because i use FB instead of fb

**Comment by phil34130** [comment]
> Hi @phil34130 , I think you might have an older version of the z/OS core collection. If you notice in the output:
> 
> ```
> Supported parameters include: batch, data_class, format, name, record_length, replace, size, state, type, volume"
> ```
> 
> You can try changing `record_format` to `format` in your playbook.

well, not quite, i have the latest one, and this is precisely why it puzzles me...
root@edf15ff66dad:~/.ansible/collections/ansible_collections/ibm/ibm_zos_core# cat MANIFEST*
{
 "collection_info": {
  "namespace": "ibm",
  "name": "ibm_zos_core",
  "version": "1.1.0",
  "authors": [
   "Asif Mahmud <asif.mahmud@ibm.com>",
   "Blake Becker <blake.becker@ibm.com>",
   "Xiao Yuan Ma <bjmaxy@cn.ibm.com>",
   "Demetrios Dimatos <ddimatos@us.ibm.com>",
   "Jack Ho <jack.ho@ibm.com>",
   "Lu Zhao <zlbjlu@cn.ibm.com>",
   "Ping Xiao <xiaoping@cn.ibm.com>",
   "Behnam Al Kajbaf <behnam@ibm.com>",
   "Andrew Nguyen <andy.nguyen@ibm.com>",
   "Radha Varadachari <radha.varadachari@ibm.com>"
  ],

**Comment by bmjunior** [comment]
JFYI:
i'm running
 "collection_info": {
  "namespace": "ibm",
  "name": "ibm_zos_core",
  "version": "1.2.0-beta.1",

**Comment by asifmahmud** [comment]
Yes, I believe there have been some updates to `zos_data_set` API since v1.2. Hence, the documentation site reflects the latest version.

**Comment by blakeinate** [comment]
@phil34130 you may need to run the following command to install the latest beta version of the collection
```
ansible-galaxy collection install ibm.ibm_zos_core:1.2.0-beta.1 --force
```

**Comment by phil34130** [comment]
Installing ibm.ibm_zos_core:1.2.0-beta.1 did make a difference, thank you ;-)

**Comment by phil34130** [comment]
installing ibm.ibm_zos_core:1.2.0-beta.1 solved the problem
