### ISSUE TITLE
[Enabler][Portability] [zos_job_query] Ensure test suite portability by removing hard coded data.

### ISSUE THREAD

**Issue by fernandofloresg** [ansible-collections/ibm_zos_core#1591]
### Enabler description
This issue is tracked by epic: [[Epic][Portability] Ensure test suite execution portability & parallelism.](https://github.com/ansible-collections/ibm_zos_core/issues/1585)

#### Issue:
There is one test that uses an started task that should not be there, we need to review this is the case for other systems. idqresults = hosts.all.zos_job_query(job_id="STC00002").

### Ansible module

zos_job_query

**Comment by ddimatos** [comment]
Relates to duplicate #1329
