### ISSUE TITLE
[Enabler] Create and add new GDG playbooks into the playbook repository

### ISSUE THREAD

**Issue by fernandofloresg** [ansible-collections/ibm_zos_core#1618]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

With the release of ibm_zos_core v1.11.0-beta.1, support for ZOAU 1.3.1 will be available, introducing numerous enhancements for using collection modules with Generation Data Groups (GDG) and GDG relative name support.

The objective is to create two scenarios demonstrating the use of multiple modules, illustrating a complete use case with GDG from start to finish. These playbooks must adhere to the sample repository standards and be added to the repository to complete the task.

### Ansible module

zos_apf, zos_archive, zos_backup_restore, zos_blockinfile, zos_copy, zos_data_set, zos_encode, zos_fetch, zos_find, zos_job_submit, zos_lineinfile, zos_mount, zos_mvs_raw, zos_operator, zos_tso_command, zos_unarchive, zos_volume_init

**Comment by AndreMarcel99** [comment]
https://github.com/IBM/z_ansible_collections_samples/pull/277
