### ISSUE TITLE
[Enabler][z/os 3.1] Create a zVM master image for adoption

### ISSUE THREAD

**Issue by fernandofloresg** [ansible-collections/ibm_zos_core#1620]
Goal is to complete the configuration of a zVM image that meets the pipeline needs that includes an auto IPL and necessary open ports and services, eg SSH

**Comment by ddimatos** [comment]
As of 8/8/24, the zVMs on order have not fully arrived. This just be delayed.

**Comment by ddimatos** [comment]
50% of the zVMs will be migrated to z/OS 3.1 , its pending some auto ipl issues that DevIT is reviewing so I can not change those zVMs till the support ticket closes, its about an 2 hours of work to migrate to z/OS 3.1
