### ISSUE TITLE
[Documentation] Add zos_mvs_raw base 64 issue to known issues section

### ISSUE THREAD

**Issue by fernandofloresg** [ansible-collections/ibm_zos_core#1622]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Documentation issue description

Add issue #1619 to known issues section.

### IBM z/OS Ansible core Version

v1.12.0-beta.1

### Ansible module

zos_mvs_raw

**Comment by ddimatos** [comment]
Issue #1619 will resolve this and thus no doc/known issue would be need, there is good progress on #1619 so I will move this to the end of the quarter to allow for the fix to be completed.
