### ISSUE TITLE
"Copied file does not match the expected checksum. Transfer failed"  when executing TASK [Create shell script /tmp/date.sh  in playbook zos-collection-sample-v2.yaml 

### ISSUE THREAD

**Issue by phil34130** [ansible-collections/ibm_zos_core#165]
TASK [Create shell script /tmp/date.sh on target zvm] **********************************************************************
task path: /root/ibm_zos_core/playbooks/zos-collection-sample-v2.yaml:322
fatal: [zvm]: FAILED! => {"changed": false, "checksum": "53739b955aacbfa94f209721b9b3aebdb6b9b6de", "expected_checksum": "a975c295ddeab5b1a5323df92f61c4cc9fc88207", "msg": "Copied file does not match the expected checksum. Transfer failed."}

**Comment by phil34130** [comment]
vvv returns the following:

{"msg": "Unsupported parameters for (copy) module: is_binary, validate_checksum Supported parameters include: _original_basename, attributes, backup, checksum, content, delimiter, dest, directory_mode, follow, force, group, local_follow, mode, owner, regexp, remote_src, selevel, serole, setype, seuser, src, unsafe_writes, validate", 

see below the full trace:

TASK [Create shell script /tmp/date.sh on target zvm] **********************************************************************
task path: /root/ibm_zos_core/playbooks/zos-collection-sample-v2.yaml:323
<9.212.128.238> ESTABLISH SSH CONNECTION FOR USER: prichar
<9.212.128.238> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o 'IdentityFile="/root/.ssh/mykey"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="prichar"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/4356cca0a9 9.212.128.238 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /tmp `"&& mkdir /tmp/ansible-tmp-1597414809.0141287-15301-106459566580118 && echo ansible-tmp-1597414809.0141287-15301-106459566580118="` echo /tmp/ansible-tmp-1597414809.0141287-15301-106459566580118 `" ) && sleep 0'"'"''
<9.212.128.238> (0, b'ansible-tmp-1597414809.0141287-15301-106459566580118=/tmp/ansible-tmp-1597414809.0141287-15301-106459566580118\n', b'')
Using module file /usr/lib/python3/dist-packages/ansible/modules/files/stat.py
Pipelining is enabled.
<9.212.128.238> ESTABLISH SSH CONNECTION FOR USER: prichar
<9.212.128.238> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o 'IdentityFile="/root/.ssh/mykey"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="prichar"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/4356cca0a9 9.212.128.238 '/bin/sh -c '"'"'_BPXK_AUTOCVT=ON ZOAU_HOME=/usr/lpp/IBM/zoautil PYTHONPATH=/usr/lpp/IBM/zoautil/lib LIBPATH=/usr/lpp/IBM/zoautil/lib:/usr/local/rocket/py36/python-2017-04-12-py36/python36/lib:/lib:/usr/lib:. PATH=/usr/lpp/IBM/zoautil/bin:/usr/local/rocket/py36/python-2017-04-12-py36/python36/bin:/bin:/var/bin:/usr/lpp/java/J8.0/bin _CEE_RUNOPTS='"'"'"'"'"'"'"'"'FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)'"'"'"'"'"'"'"'"' _TAG_REDIR_ERR=txt _TAG_REDIR_IN=txt _TAG_REDIR_OUT=txt LANG=C tgt_tmp_dir=/tmp ctl_tmp_dir=/tmp /usr/local/rocket/py36/python-2017-04-12-py36/python36/bin/python && sleep 0'"'"''
<9.212.128.238> (0, b'\n{"changed": false, "stat": {"exists": false}, "invocation": {"module_args": {"path": "/tmp/date.sh", "follow": false, "get_checksum": true, "checksum_algorithm": "sha1", "get_md5": false, "get_mime": true, "get_attributes": true}}}\n', b'')
<9.212.128.238> PUT /root/.ansible/tmp/ansible-local-15179z2xg3r4w/tmpemah2xdg TO /tmp/ansible-tmp-1597414809.0141287-15301-106459566580118/source
<9.212.128.238> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o 'IdentityFile="/root/.ssh/mykey"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="prichar"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/4356cca0a9 '[9.212.128.238]'
<9.212.128.238> (0, b'sftp> put /root/.ansible/tmp/ansible-local-15179z2xg3r4w/tmpemah2xdg /tmp/ansible-tmp-1597414809.0141287-15301-106459566580118/source\n', b'')
<9.212.128.238> ESTABLISH SSH CONNECTION FOR USER: prichar
<9.212.128.238> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o 'IdentityFile="/root/.ssh/mykey"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="prichar"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/4356cca0a9 9.212.128.238 '/bin/sh -c '"'"'chmod u+x /tmp/ansible-tmp-1597414809.0141287-15301-106459566580118/ /tmp/ansible-tmp-1597414809.0141287-15301-106459566580118/source && sleep 0'"'"''
<9.212.128.238> (0, b'', b'')
Using module file /usr/lib/python3/dist-packages/ansible/modules/files/copy.py
Pipelining is enabled.
<9.212.128.238> ESTABLISH SSH CONNECTION FOR USER: prichar
<9.212.128.238> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o 'IdentityFile="/root/.ssh/mykey"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="prichar"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/4356cca0a9 9.212.128.238 '/bin/sh -c '"'"'_BPXK_AUTOCVT=ON ZOAU_HOME=/usr/lpp/IBM/zoautil PYTHONPATH=/usr/lpp/IBM/zoautil/lib LIBPATH=/usr/lpp/IBM/zoautil/lib:/usr/local/rocket/py36/python-2017-04-12-py36/python36/lib:/lib:/usr/lib:. PATH=/usr/lpp/IBM/zoautil/bin:/usr/local/rocket/py36/python-2017-04-12-py36/python36/bin:/bin:/var/bin:/usr/lpp/java/J8.0/bin _CEE_RUNOPTS='"'"'"'"'"'"'"'"'FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)'"'"'"'"'"'"'"'"' _TAG_REDIR_ERR=txt _TAG_REDIR_IN=txt _TAG_REDIR_OUT=txt LANG=C tgt_tmp_dir=/tmp ctl_tmp_dir=/tmp /usr/local/rocket/py36/python-2017-04-12-py36/python36/bin/python && sleep 0'"'"''
<9.212.128.238> (1, b'\n{"msg": "Unsupported parameters for (copy) module: is_binary, validate_checksum Supported parameters include: _original_basename, attributes, backup, checksum, content, delimiter, dest, directory_mode, follow, force, group, local_follow, mode, owner, regexp, remote_src, selevel, serole, setype, seuser, src, unsafe_writes, validate", "failed": true, "invocation": {"module_args": {"dest": "/tmp/date.sh", "owner": "prichar", "mode": "0755", "force": true, "validate_checksum": false, "is_binary": false, "src": "/tmp/ansible-tmp-1597414809.0141287-15301-106459566580118/source", "_original_basename": "tmpemah2xdg", "follow": false, "checksum": "a975c295ddeab5b1a5323df92f61c4cc9fc88207"}}}\n', b'')
<9.212.128.238> Failed to connect to the host via ssh: 
<9.212.128.238> ESTABLISH SSH CONNECTION FOR USER: prichar
<9.212.128.238> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o 'IdentityFile="/root/.ssh/mykey"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="prichar"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/4356cca0a9 9.212.128.238 '/bin/sh -c '"'"'rm -f -r /tmp/ansible-tmp-1597414809.0141287-15301-106459566580118/ > /dev/null 2>&1 && sleep 0'"'"''
<9.212.128.238> (0, b'', b'')
fatal: [zvm]: FAILED! => {
    "changed": false,
    "checksum": "a975c295ddeab5b1a5323df92f61c4cc9fc88207",
    "diff": [],
    "invocation": {
        "module_args": {
            "_original_basename": "tmpemah2xdg",
            "checksum": "a975c295ddeab5b1a5323df92f61c4cc9fc88207",
            "dest": "/tmp/date.sh",
            "follow": false,
            "force": true,
            "is_binary": false,
            "mode": "0755",
            "owner": "prichar",
            "src": "/tmp/ansible-tmp-1597414809.0141287-15301-106459566580118/source",
            "validate_checksum": false
        }
    },
    "msg": "Unsupported parameters for (copy) module: is_binary, validate_checksum Supported parameters include: _original_basename, attributes, backup, checksum, content, delimiter, dest, directory_mode, follow, force, group, local_follow, mode, owner, regexp, remote_src, selevel, serole, setype, seuser, src, unsafe_writes, validate"
}

**Comment by blakeinate** [comment]
Hi @phil34130 , can you try to add `scp_if_ssh = False` to your ansible.cfg file under the `ssh_connection` section? The final result should look like this:

```
[ssh_connection]
pipelining = True
scp_if_ssh = False
```

**Comment by phil34130** [comment]
no luck. 
i replaced back zos_copy to copy, and updated ansible.cfg with "scp_if_ssh = False", but still get the same error as before

fatal: [zvm]: FAILED! => {
    "changed": false,
    "checksum": "53739b955aacbfa94f209721b9b3aebdb6b9b6de",
    "diff": [],
    "expected_checksum": "a975c295ddeab5b1a5323df92f61c4cc9fc88207",
    "invocation": {
        "module_args": {
            "_original_basename": "tmp87fzv5bh",
            "attributes": null,
            "backup": false,
            "checksum": "a975c295ddeab5b1a5323df92f61c4cc9fc88207",
            "content": null,
            "delimiter": null,
            "dest": "/tmp/date.sh",
            "directory_mode": null,
            "follow": false,
            "force": true,
            "group": null,
            "local_follow": null,
            "mode": "0755",
            "owner": "prichar",
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": "/tmp/ansible-tmp-1597773000.852992-19688-222876474760640/source",
            "unsafe_writes": null,
            "validate": null
        }
    },
    "msg": "Copied file does not match the expected checksum. Transfer failed."

**Comment by ddimatos** [comment]
@phil34130 - Hi Phil, it seems this might have fallen of our radar or was addressed already.

Some thoughts come to mind. Is your playbook setting the `copy` modules [checksum](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html#parameter-checksum) option with a value? Maybe share the updated version of the playbook if this is still an issue. 

From what I can tell is that the checksum is being obtained via the option I linked above via this [line](https://github.com/ansible/zuul-test-repo/blob/525f78853c223f34399ae7e8b47b26b6908aef55/lib/ansible/modules/files/copy.py#L332) of code and if I recall the original sample playbook snippet looked like:
```
    - name: Create shell script {{ tgt_tmp_dir }}/date.sh on
        target {{ inventory_hostname }}
      copy:
        dest: "{{ tgt_tmp_dir }}/date.sh"
        content: |
          date
        owner: "{{ ansible_user }}"
        mode: "0755"
        force: yes
```
Which is not using a `src` but instead dynamically creating the file with the noted `content`, thus if you edited this with a checksum of your own it would cause that linked code to start comparing checksums yet this file is created dynamically thus the checksum is not a valid option. I don't know how the checksum would be valid for a file that is not actually copied but created on dynamically on the target. 

I see this in your error making me think the checksum was added:

<9.212.128.238> (1, b'\n{"msg": "Copied file does not match the expected checksum. Transfer failed.", "checksum": "53739b955aacbfa94f209721b9b3aebdb6b9b6de", "expected_checksum": 

Another thought is to ensure your `/tmp` has enough space although I doubt in this case this is the issue as its a tiny date shell script being created. 

Could you also check that the file is not on the target as well; if it is, i may have to look over the code differently.

**Comment by ddimatos** [comment]
Closing since due to inactivity, feel free to reopen.
