### ISSUE TITLE
zos-collection-sample-v3.yaml:100 fatal: [zvm]: FAILED! => {"changed": false, "msg": "SubmitJCLError(\"SUBMIT JOB FAILED:  Stderr :FSUMB408 submit: data set 'PRICHAR.SOME.DATA.SET(PSA)' Not accepted by JES.\\n\",)"}

### ISSUE THREAD

**Issue by phil34130** [ansible-collections/ibm_zos_core#166]
root@edf15ff66dad:~/ibm_zos_core/playbooks# ansible-playbook -i inventory zos-collection-sample-v3.yaml -vv
ansible-playbook 2.9.9
  config file = /root/ibm_zos_core/playbooks/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.5 (default, Jul 20 2020, 18:32:44) [GCC 9.3.0]
Using /root/ibm_zos_core/playbooks/ansible.cfg as config file

PLAYBOOK: zos-collection-sample-v3.yaml ************************************************************************************
1 plays in zos-collection-sample-v3.yaml

PLAY [zvm] *****************************************************************************************************************
META: ran handlers

TASK [Copy local directory /root/ibm_zos_core/playbooks/files to PRICHAR.SOME.DATA.SET] ************************************
task path: /root/ibm_zos_core/playbooks/zos-collection-sample-v3.yaml:60
prichar@9.212.128.238's password: 
changed: [zvm] => {"changed": true, "dest": "PRICHAR.SOME.DATA.SET", "is_binary": false, "src": "/root/ibm_zos_core/playbooks/files"}

TASK [Response for copy local directory /root/ibm_zos_core/playbooks/files to PRICHAR.SOME.DATA.SET.] **********************
task path: /root/ibm_zos_core/playbooks/zos-collection-sample-v3.yaml:69
ok: [zvm] => {
    "result_copy_dir": {
        "changed": true,
        "dest": "PRICHAR.SOME.DATA.SET",
        "failed": false,
        "is_binary": false,
        "src": "/root/ibm_zos_core/playbooks/files"
    }
}

TASK [Copy PDS member PRICHAR.SOME.DATA.SET(UPTIME) to a new PDS member PRICHAR.SOME.DATA.SET(PSA)] ************************
task path: /root/ibm_zos_core/playbooks/zos-collection-sample-v3.yaml:73
changed: [zvm] => {"changed": true, "dest": "PRICHAR.SOME.DATA.SET(PSA)", "is_binary": false, "src": "PRICHAR.SOME.DATA.SET(UPTIME)"}

TASK [Edit JCL PSA job card on z/OS managed node.] *************************************************************************
task path: /root/ibm_zos_core/playbooks/zos-collection-sample-v3.yaml:79
ok: [zvm] => {"changed": 0, "cmd": "dsedhelper -d -c IBM-1047 ///UPTIME    JOB (T043JM,JM00,1,0,0,0),'UPTIME - JRM',/c\\//PSA    JOB (T043JM,JM00,1,0,0,0),'PSA - JRM',/$ PRICHAR.SOME.DATA.SET(PSA) ", "found": 0}

TASK [Edit JCL PSA step-name on z/OS managed node.] ************************************************************************
task path: /root/ibm_zos_core/playbooks/zos-collection-sample-v3.yaml:86
ok: [zvm] => {"changed": 0, "cmd": "dsedhelper -d -c IBM-1047 ///UPTIME  EXEC PGM=BPXBATCH/c\\//PSA  EXEC PGM=BPXBATCH/$ PRICHAR.SOME.DATA.SET(PSA) ", "found": 0}

TASK [Edit JCL PSA USS command on z/OS managed node.] **********************************************************************
task path: /root/ibm_zos_core/playbooks/zos-collection-sample-v3.yaml:93
ok: [zvm] => {"changed": 0, "cmd": "dsedhelper -d -c IBM-1047 /SH uptime/c\\SH ps -A/$ PRICHAR.SOME.DATA.SET(PSA) ", "found": 0}

TASK [Submit the JCL PRICHAR.SOME.DATA.SET(PSA)] ***************************************************************************
task path: /root/ibm_zos_core/playbooks/zos-collection-sample-v3.yaml:100
fatal: [zvm]: FAILED! => {"changed": false, "msg": "SubmitJCLError(\"SUBMIT JOB FAILED:  Stderr :FSUMB408 submit: data set 'PRICHAR.SOME.DATA.SET(PSA)' Not accepted by JES.\\n\",)"}

PLAY RECAP *****************************************************************************************************************
zvm                        : ok=6    changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0  

if i look at the content of  the DATASET member UPTIME submitted to JES2, it is clearly not EBCDIC for JES2 to interpret.

 BROWSE    PRICHAR.SOME.DATA.SET(UPTIME)            Line 0000000000 Col 001 080 
 Command ===>                                                  Scroll ===> CSR  
********************************* Top of Data **********************************
aa\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
.aa\@Ã.....€..@£..@...@....@.¢@......k@..¢£@......@..]¦...@......£..¢@..£...aa\@
.......@...£...@...z.aa\@ÃÓÁââz@ä¢..@£.@.....¥.@.@.......@..£¦...@........£@£]..
¢@..@...¢@...@.¥....aa\@@@@@@@@...£..£...@..£¦...@...¢@£..£@€¢.@£..@¢...@..¢.€..
.¢K.aa\@ÔâÇÓÅåÅÓz@...£...¢@..¦@£..@......£...@..¢¢...¢@...@£......£...@..¢¢...¢@
....aa\@@@@@@@@@@@....£..@..@£..@...}¢@.€£.€£@..¢£...@MâèâÖäã¨K.aa\@ÔâÇÃÓÁââz@.¢
¢...@..@.€£.€£@...¢¢@...@].€.@.€£.€£@..¢£...@MâèâÖäã¨.aa\\\\\\\\\\\\\\\\\\\\\\\\
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\.aaä×ãÉÔÅ@@@@ÑÖÂ@MãðôóÑÔkÑ
Ôððkñkðkðkð¨k}ä×ãÉÔÅ@`@ÑÙÔ}k.aa@@@@@@@@@@@@@ÔâÇÃÓÁââ~çkÔâÇÓÅåÅÓ~ñkÕÖãÉÆè~PâèâäÉÄ
kÙÅÇÉÖÕ~ôÔ.aa\.aa\@×ÙÉÕã@äââ@ÃÖÔÔÁÕÄ@ÖÕ@ÑÖÂ@Öäã×äã.aa\.aaä×ãÉÔÅ@@ÅçÅÃ@×ÇÔ~Â×çÂÁã
ÃÈ.aaâãÄ×ÁÙÔ@ÄÄ@\.âÈ@€.£....aaâãÄÉÕ@@ÄÄ@ÄäÔÔè.aaâãÄÖäã@ÄÄ@âèâÖäã~\.aaâãÄÅÙÙ@ÄÄ@â
èâÖäã~\.aa......................................................................

**Comment by phil34130** [comment]
i fixed it by commenting out the encoding section:
    - name: "Copy local directory {{ playbook_dir }}/files to {{ ansible_user | upper }}.SOME.DATA.SET"
      zos_copy:
        src: "{{ playbook_dir }}/files"
        dest: "{{ ansible_user | upper }}.SOME.DATA.SET"
#        encoding:
#          from: ISO8859-1
#          to: IBM-1047

i would recommend removing that block (not sure if encoding is done automatically with module zos_copy  with collection  ibm.ibm_zos_core:1.2.0-beta.1...)

**Comment by phil34130** [comment]
`    - name: "Copy local directory {{ playbook_dir }}/files to {{ ansible_user | upper }}.SOME.DATA.SET"
      zos_copy:
        src: "{{ playbook_dir }}/files"
        dest: "{{ ansible_user | upper }}.SOME.DATA.SET"
#        encoding:
#          from: ISO8859-1
#          to: IBM-1047`

**Comment by phil34130** [comment]
`   - name: "Copy local directory {{ playbook_dir }}/files to {{ ansible_user | upper }}.SOME.DATA.SET"
      zos_copy:
        src: "{{ playbook_dir }}/files"
        dest: "{{ ansible_user | upper }}.SOME.DATA.SET"
 #        encoding:
 #          from: ISO8859-1
 #          to: IBM-1047`

**Comment by asifmahmud** [comment]
I ran the sample playbooks on my end and they seem to be running fine. I am using `1.2.0-beta.2`, which has just been released to Galaxy. There are quite a few bugfixes in this release. You might want to give that a try.

**Comment by asifmahmud** [comment]
> not sure if encoding is done automatically with module zos_copy

If encoding is not specified, no encoding conversion will take place.

**Comment by phil34130** [comment]
same problem after installing beta2. 
TASK [Submit the JCL PRICHAR.SOME.DATA.SET(PSA)] ***************************************************************************
task path: /root/ibm_zos_core/playbooks/zos-collection-sample-v3.yaml:100
fatal: [zvm]: FAILED! => {"changed": false, "msg": "SubmitJCLError(\"SUBMIT JOB FAILED:  Stderr :FSUMB408 submit: data set 'PRICHAR.SOME.DATA.SET(PSA)' Not accepted by JES.\\n\",)"}

I think the sample playbook should not include the "encoding" block; if i comment out that block, then the playbook runs successfully...
`#        encoding:
#          from: ISO8859-1
#          to: IBM-1047`

**Comment by phil34130** [comment]
I think the sample playbook should not include the "encoding" block; if i comment out that block, then the playbook runs successfully...
# encoding:
# from: ISO8859-1
# to: IBM-1047
