### ISSUE TITLE
[Enabler] Adapts utils.py to test suites job submit and fetch

### ISSUE THREAD

**Issue by AndreMarcel99** [ansible-collections/ibm_zos_core#1666]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

As the PR [1664](https://github.com/ansible-collections/ibm_zos_core/pull/1664) introduce utils.py the function get random qualifier once is merged the test suites job submit and fetch will required rework

**Comment by fernandofloresg** [comment]
Fixed by #1664
