### ISSUE TITLE
[Enabler][pipeline][z/os 3.1] Configure 3.1 to work in testing VMs

### ISSUE THREAD

**Issue by fernandofloresg** [ansible-collections/ibm_zos_core#1724]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

This task represents the effort spent into getting ready the ECs with z/OS 3.1.

**Comment by ddimatos** [comment]
This is completed, I modified the zVMs ATI scripts and included 3 other Jobs to aid in correcting the TCPIP 3.1 issues. Its been deployed to the Mini A disks.

**Comment by ddimatos** [comment]
This spanned more than 1 sprint, will adjust points from 5 pts to 12 pts.
