### ISSUE TITLE
[Enhancement] Enhancement for zos_operator to not wait the full wait_time_s  and leverage the updated zoau wait bool

### ISSUE THREAD

**Issue by sjwar455** [ansible-collections/ibm_zos_core#1752]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enhancement or feature description

It would be nice if the `ibm_zos_core.zos_operator` module had an option to bypass waiting the full `wait_time_s` value. 

I have a playbook that defines a bunch of mini disk for testing. I have several tasks that loop and issue `zos_operator` module commands. For example, here's the task I use to vary all my mini disk online: 

```
    - name: Vary Mini Disk Online  
      ibm.ibm_zos_core.zos_operator: 
        cmd: 'v {{ vol.value.vaddr }},online'
        verbose: true 
      loop: "{{ volumes.minidisk | dict2items }}"
      loop_control:
          loop_var: vol
      register: output 
```

I am seeing that for each operator command, the `elapsed` wait time is ~1 second (aligning with the default mentioned in the documentation https://ibm.github.io/z_ansible_collections_doc/ibm_zos_core/docs/source/modules/zos_operator.html).   

```
  msg:
    changed: true
    msg: All items completed
    results:
    - ansible_loop_var: vol
      changed: true
      cmd: v E00,online
      content:
      - SYSTEM1    2024276  09:55:57.00             ISF031I CONSOLE IBMU0000 ACTIVATED
      - 'SYSTEM1    2024276  09:55:57.00            -V E00,ONLINE '
      - SYSTEM1    2024276  09:55:57.00             IEE302I 0E00     ONLINE
      - BGYSC0804I Using timeout of 100 centiseconds.
      - 'BGYSC0801I CONSBUFPGNUM=128 - Console command output buffer memory size to be allocated: 131072 bytes.'
      - BGYSC0806I Using console name of IBMU0000.
      - BGYSC0805I Using CART of ZOAU6904.
      - BGYSC0802I Console command returned output string size of 24 bytes.
      elapsed: 1.02 <--- this value!! 
      failed: false
      invocation:
        module_args:
          cmd: v E00,online
          verbose: true
          wait_time_s: 1
      rc: 0
      vol:
        key: JRNL01
        value:
          cyls: 500
          sms: false
          vaddr: E00
      wait_time_s: 1
```

I explored this possible enhancement with Demetrios Dimatos, and made some code changes to zos_operator.py so that the underlying ZOAU python function for opercmd is called with wait = false. 

I have attached two different playbooks. One that uses `ansible.builtin.command` to issue a series of ZOAU `opercmd` shell commands and a second playbook that uses `zos_operator`. There are three logs attached: One for each playbook (without any code changes) and an additional one for the zos_operator playbook which tests the above described code change. 

Overal conclusion - either using `ansible.builtin.command` or `zos_operator` with code changes is a significant improvement.  (down to 1 sec per command from 2 seconds). 

Not shown in the logs are the runs I did with `ansible-playbook -vvv` - from those runs I can see that a big time eater is re-establishing the ssh connection to my managed node for each command in my loop.

[volumes_ansible_builtin_command.log](https://github.com/user-attachments/files/17404598/volumes_ansible_builtin_command.log)
[volumes_zos_operator_no_wait.log](https://github.com/user-attachments/files/17404599/volumes_zos_operator_no_wait.log)
[volumes_zos_operator_wait.log](https://github.com/user-attachments/files/17404600/volumes_zos_operator_wait.log)
[volumes_ansible_builtin_command.yaml.txt](https://github.com/user-attachments/files/17404612/volumes_ansible_builtin_command.yaml.txt)
[volumes_zos_operator.yaml.txt](https://github.com/user-attachments/files/17404613/volumes_zos_operator.yaml.txt)

Some added info, this is the version of ibm_zos_core collection I am currently using: 
```
$ ansible-galaxy collection list ibm.ibm_zos_core

# /Users/sam/.ansible/collections/ansible_collections
Collection       Version
---------------- -------
ibm.ibm_zos_core 1.10.0 
```

Originally asked a question about this on the IBM Z Enthusiast Discord - you can see the full discussion here: https://discord.com/channels/880322471608344597/1291085161462501469

### Ansible module

zos_operator

**Comment by fernandofloresg** [comment]
It was validated that it isn't a program bug, but a bad doc explanation. Closing this issue since work will be tracked in #1754
