### ISSUE TITLE
The latest release of zos_copy module failed to copy local dir/files into PDS.

### ISSUE THREAD

**Issue by jameszhengxin** [ansible-collections/ibm_zos_core#177]
I installed ibm.ibm_zos_core with 'ansible-galaxy collection install ibm.ibm_zos_core' command but the installed package doesn't include 'zos_copy' module. 
So I cloned git repository and replaced the installed collection and it can be searched but failed when I tried to copy whole local dir or one file to a PDS in remote HOST.
 
##### SUMMARY
I call the module like this:
  - name: Copy XXX configuration files
    zos_copy: 
      src: ./templates/
      dest: XXXX.XXXX.ANSIBLE.CONTROL
And when the module execution, it asked me about the password and I input the correct password for execition. 
Then the module failed:

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ibm.ibm_zos_core/plugins/module/zos_copy.py

##### ANSIBLE VERSION
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/james/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.16 (default, Jun  5 2020, 22:59:21) [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-

##### CONFIGURATION
james@jamess-mbp ansible % ansible-config dump --only-changed
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 25
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = /u/xzhen/python

##### OS / ENVIRONMENT
zOS 2.2

##### STEPS TO REPRODUCE
  - name: Copy XXX configuration files
    zos_copy: 
      src: ./templates/
      dest: XXXX.XXXX.ANSIBLE.CONTROL

##### EXPECTED RESULTS
All local files under ./templates/ are copied into dest PDS library on remote zOS system. 

##### ACTUAL RESULTS
TASK [Copy zDlA configuration files] *******************************************
xzhen@x.xx.xxx.xx's password: 
fatal: [x.xx.xxx.xx]: FAILED! => {"changed": false, "msg": "Error transfering source '/Users/james/Documents/XXX/ansible/templates' to remote z/OS system", "rc": 0, "stderr": "IBM's business or for purposes authorized by IBM management.Use is subject to audit at any time by IBM Management.Connected to x.xx.xxx.xx.", "stderr_lines": ["IBM's business or for purposes authorized by IBM management.Use is subject to audit at any time by IBM Management.Connected to x.xx.xxx.xx."]}

PLAY RECAP *********************************************************************
x.xx.xxx.xx                : ok=2    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

I replaced the real host name/ip address to x.xx.xxx.xx.

**Comment by blakeinate** [comment]
I think this may be related to #150

**Comment by blakeinate** [comment]
Based on the result of #150 , I believe you may have success by specifying `ignore_sftp_stderr: true` when using *zos_copy*

**Comment by jameszhengxin** [comment]
Thanks Blake, 
I put the 'ignore_sftp_stderr: true'  as parameter of 'zos_copy' or put it in 'environment' but all didn't make zos_copy works. 

Here is example:

  - name: Copy  JCL control files from USS to control DS
    zos_copy: 
      src: /u/xzhen/XXXXX/RUN
      dest: XZHEN.V3R1M0.ANSIBLE.CONTROL(RUN)
      remote_src: true
      ignore_sftp_stderr: true


And the response shows:

fatal: [sysg]: FAILED! => {"msg": "Unable to import ibm.ibm_zos_core.zos_copy due to invalid syntax"}

Any comments for this?

Thanks a lot

**Comment by jameszhengxin** [comment]
Hello Blake:
Please let me describe my purpose to use zos_copy module. 
I plan to copy all or part of files from USS directory to a PDS. 
The USS directory and PDS are in the same zOS system. 
I tried many of ways to use 'zos_copy' but all failed.
I am also wondering if 'zos_copy' support 'with_filelob' parameter to go through all files under USS directory. 

Can you give me an working example for this scenario?

Thank you very much

**Comment by blakeinate** [comment]
Based on your error messages, I believe your method of installing the collection may not have been sufficient. Can you please try to install the latest beta version of our collection with the following command:

```
ansible-galaxy collection install ibm.ibm_zos_core:1.2.0-beta.3 --force
```

**Comment by jameszhengxin** [comment]
I ran the instruction you gave to me and update the collection to the 1.2.0-beta.3 release. 
But the issue still here:

TASK [Copy control files from USS to control DS] *********************************************
fatal: [kanplex_sysg]: FAILED! => {"msg": "Unable to import ibm.ibm_zos_core.zos_copy due to invalid syntax"}

**Comment by jameszhengxin** [comment]
If I point 'src:' to USS directory then the 'zos_copy' default use this directory as local one.  To avoid this, I added 'remote_src = true' then the module responsed the 'invalid dyntax'. 
I think that's the problem.

**Comment by asifmahmud** [comment]
Would it be possible to give us the entire terminal log when you execute the playbook with increased verbosity? `-vvv`
Also, do you experience `invalid syntax` error with any other module?

**Comment by asifmahmud** [comment]
Hi @jameszhengxin , are you still experiencing this issue with the latest version of our collection? I know this issue has been open for a while, so just wanted to check in and see if the problem persists on your end.

**Comment by zhengxin88** [comment]
Hi @asifmahmud  asifmahmud, I have no more experienced this issue anymore. Thank you for asking.

**Comment by asifmahmud** [comment]
Great! I will go ahead and close this issue then. Thank you for reporting back!
