### ISSUE TITLE
General question on variable usage

### ISSUE THREAD

**Issue by WladyslawBorysow** [ansible-collections/ibm_zos_core#178]
Hello Developers:)

I am installing / learning Ansible with z/OS. I don't have previous experience with YAML and ANSIBLE. My question is regarding vars usage, which is causing me some problems.
Let's assume I want to issue command and after it capture response to vars and use some of these vars.

---
- hosts: MINE
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"
  tasks:
   - name: issue TSO command
     zos_tso_command:
      commands: 
       - LU USERID
     register: some_output
   - name: some_output
     debug: 
      msg :  "{{ some_output}}"

when done I receive list of all variables and their value...

But what if I want to just see one value from this array (some_output)?
Let's assume I just want to see/use 4th line of the content of the response from my command. How to specify it?

I tried with:
msg :  "{{ some_output.output.content[4}}"
but not working.

Many Thanks
Wladyslaw

**Comment by blakeinate** [comment]
Hi @WladyslawBorysow , you should be able to access content from variables using Python syntax, based on your attempt above, the equivalent would be:

```
 msg : "{{ some_output.get('output').get('content')[4]}}"
```

**Comment by WladyslawBorysow** [comment]
Hi Blake,
many thanks for your support - I am an ansible newbie so I really appreciate it!
I did modifications acc. to your post above
---
- hosts: AAA
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"
  tasks:
   - name: issue TSO command
     zos_tso_command:
      commands: 
       - LU xxxxxx
     register: some_output
   - name: some_output
     debug: 
      msg :  "{{ some_output.get('output').get('content')[4] }}"

I got this error:

TASK [some_output] **************************************************************************************************************************************************************************************************************
fatal: [TET2]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'list object' has no attribute 'get'\n\nThe error appears to be in '/etc/ansible/playbooks/test16.yaml': line 13, column 6, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n     register: some_output\n   - name: some_output\n     ^ here\n"}

Thanks once again

**Comment by WladyslawBorysow** [comment]
Hi Blake,
thank you.
I did some tests and find out what was the problem.

I used this statement:
msg : "{{ some_output.output.content[4}}"

but should have used:
msg : "{{ some_output.output[0].content[4}}"

It seems that all data from command is put into output[0] variable.
