### ISSUE TITLE
JSONDecodeError when executing zos_job_output

### ISSUE THREAD

**Issue by ce70wn** [ansible-collections/ibm_zos_core#203]
##### SUMMARY

zos_job_output throws JSONDecodeError for certain JOBLOGS that output EREP listings using PGM=IFCEREP1.
Problem occurs when EREP data includes HEX DUMP data.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

zos_job_output 

##### ANSIBLE VERSION

```paste below
[ansible@osazpdt-x3100 host]$ ansible --version
ansible 2.9.11
  config file = /home/ansible/users/host/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Mar 20 2020, 17:08:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
[ansible@osazpdt-x3100 host]$ ansible-config dump --only-changed
ANSIBLE_PIPELINING(/home/ansible/users/host/ansible.cfg) = True
DEFAULT_FORKS(/home/ansible/users/host/ansible.cfg) = 25
[ansible@osazpdt-x3100 host]$
```

##### OS / ENVIRONMENT

z/OS V2.3+Python 3.8.3 

##### STEPS TO REPRODUCE

Please refer to OK and NG JOBLOGS 
https://gist.github.com/ce70wn/093a4fedf7cf8be66caef4762126e030#file-ok-case
https://gist.github.com/ce70wn/093a4fedf7cf8be66caef4762126e030#file-ng-case

```yaml
    - name: JES Job output with all ddnames
      zos_job_output:
        job_name: "MVSEREP"
      register: result

```

##### EXPECTED RESULTS

For OK case, the zos_job_output ends normally:

TASK [JES Job output with all ddnames] *****************************************************************************************************************************************************************
ok: [hot2]

##### ACTUAL RESULTS

TASK [JES Job output with all ddnames] *****************************************************************************************************************************************************************
task path: /home/ansible/users/host/hot2/tmp.yaml:4
Using module file /home/ansible/.ansible/collections/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_job_output.py
Pipelining is enabled.
<xxx.com> ESTABLISH SSH CONNECTION FOR USER: ansible
<xxx.com> SSH: EXEC sshpass -d8 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o 'User="ansible"' -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/893e9f1594 xxx.com '/bin/sh -c '"'"'_BPXK_AUTOCVT=ON LANG=C _TAG_REDIR_IN=txt ZOAU_HOME=/usr/lpp/IBM/zoautil PYTHONPATH=/usr/lpp/IBM/zoautil/lib _TAG_REDIR_OUT=txt _CEE_RUNOPTS='"'"'"'"'"'"'"'"'FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)'"'"'"'"'"'"'"'"' PATH=/usr/lpp/IBM/zoautil/bin:/usr/lpp/python/usr/lpp/IBM/cyp/v3r8/pyz/bin:/bin:/var/bin:/usr/lpp/java/J8.0/bin LIBPATH=/usr/lpp/IBM/zoautil/lib:/usr/lpp/python/usr/lpp/IBM/cyp/v3r8/pyz/lib:/lib:/usr/lib:. _TAG_REDIR_ERR=txt /usr/bin/python && sleep 0'"'"''
<xxx.com> (1, '\n{"msg": "JSONDecodeError(\'Invalid \\\\\\\\escape: line 3409 column 71 (char 147644)\')", "failed": true, "exception": "  File \\"/tmp/ansible_zos_job_output_payload_apjqxgan/ansible_zos_job_output_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_job_output.py\\", line 356, in run_module\\n  File \\"/tmp/ansible_zos_job_output_payload_apjqxgan/ansible_zos_job_output_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/module_utils/job.py\\", line 54, in job_output\\n    job_detail_json = _get_job_output(job_id, owner, job_name, dd_name)\\n  File \\"/tmp/ansible_zos_job_output_payload_apjqxgan/ansible_zos_job_output_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/module_utils/job.py\\", line 87, in _get_job_output\\n    job_detail_json = json.loads(out, strict=False)\\n  File \\"/usr/lpp/python/usr/lpp/IBM/cyp/v3r8/pyz/lib/python3.8/json/__init__.py\\", line 370, in loads\\n    return cls(**kw).decode(s)\\n  File \\"/usr/lpp/python/usr/lpp/IBM/cyp/v3r8/pyz/lib/python3.8/json/decoder.py\\", line 337, in decode\\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\\n  File \\"/usr/lpp/python/usr/lpp/IBM/cyp/v3r8/pyz/lib/python3.8/json/decoder.py\\", line 353, in raw_decode\\n    obj, end = self.scan_once(s, idx)\\n", "invocation": {"module_args": {"job_name": "MVSEREP", "job_id": null, "owner": null, "ddname": null}}}\n', 'OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 58: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 8636\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\n')
<xxx.com> Failed to connect to the host via ssh: OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 58: Applying options for *
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 8636
debug3: mux_client_request_session: session request sent
debug1: mux_client_request_session: master session id: 2
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 1
The full traceback is:
  File "/tmp/ansible_zos_job_output_payload_apjqxgan/ansible_zos_job_output_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_job_output.py", line 356, in run_module
  File "/tmp/ansible_zos_job_output_payload_apjqxgan/ansible_zos_job_output_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/module_utils/job.py", line 54, in job_output
    job_detail_json = _get_job_output(job_id, owner, job_name, dd_name)
  File "/tmp/ansible_zos_job_output_payload_apjqxgan/ansible_zos_job_output_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/module_utils/job.py", line 87, in _get_job_output
    job_detail_json = json.loads(out, strict=False)
  File "/usr/lpp/python/usr/lpp/IBM/cyp/v3r8/pyz/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lpp/python/usr/lpp/IBM/cyp/v3r8/pyz/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lpp/python/usr/lpp/IBM/cyp/v3r8/pyz/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
fatal: [hot2]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ddname": null,
            "job_id": null,
            "job_name": "MVSEREP",
            "owner": null
        }
    },
    "msg": "JSONDecodeError('Invalid \\\\escape: line 3409 column 71 (char 147644)')"
}

PLAY RECAP *********************************************************************************************************************************************************************************************
hot2                       : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```paste below

```

**Comment by blakeinate** [comment]
This appears to be an issue with the way we are retrieving job logs. We will need to make some revisions to our parsing to improve handling of special characters.
