### ISSUE TITLE
Docs: Module template shows omitted type

### ISSUE THREAD

**Issue by andy-maier** [ansible-collections/ibm_zos_core#217]
##### SUMMARY

In the [zhmc collection](https://github.com/zhmcclient/zhmc-ansible-modules), the return values have pretty long lists of resource properties that we are not documenting one by one because they are documented in the Web Services API book of the HMC. In our descriptions of the return values, we have "generic" properties named `{property}` whose description references the section in the WS-API book that describes the properties. For such generic properties it does not make sense of course to call out a specific type.

Our current solution is to omit the `type` field in the return value docstring. Omitting the type field causes the module.rst.j2 template to generate a "type:" text in the output without a value.

We would like to have the "type:" text in the output to be conditional on the presence of the type field in the return value docstring.

I can bring a PR for this forward.

Note: We open this issue here because this repo has the master version of the module.rst.j2 file, across the IBM collections.

##### ISSUE TYPE
- Documentation Bug Report

##### COMPONENT NAME

* docs/templates/module.rst.j2

##### ANSIBLE VERSION

```paste below
N/A
```

##### CONFIGURATION

```paste below
N/A
```

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

* Build documentation of [zhmc collection](https://github.com/zhmcclient/zhmc-ansible-modules) which can be seen at https://zhmcclient.github.io/zhmc-ansible-modules/.
* Look at this return value to see the effect (2 occurrences): https://zhmcclient.github.io/zhmc-ansible-modules/modules/zhmc_adapter.html#return-values

##### EXPECTED RESULTS

We would like to have the "type:" text in the output to be conditional on the presence of the type field in the return value docstring.

##### ACTUAL RESULTS

See above

**Comment by andy-maier** [comment]
Addressed n PR #221.

**Comment by ddimatos** [comment]
See the [PR comments](https://github.com/ansible-collections/ibm_zos_core/pull/221) as to why this will not be changed and is marked as a "Do not Merge"
