### ISSUE TITLE
Docs: Maintain source order for module parameters

### ISSUE THREAD

**Issue by andy-maier** [ansible-collections/ibm_zos_core#219]
##### SUMMARY

Right now, the modules.rst.j2 template sorts the input parameters by name. For projects that want to maintain a more logical order of input properties, it would be helpful to provide a way to disable the sorting.

I can bring forward a PR that does that.

Note: We open this issue here because this repo has the master version of the module.rst.j2 file, across the IBM collections.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

* docs/templates/mpdule.rst.j2

##### ADDITIONAL INFORMATION

See PR, once submitted.

**Comment by andy-maier** [comment]
Addressed with PR #220.

**Comment by ddimatos** [comment]
Issue has been resolved. As a future enhancement that I will work on would be to have the make file manage the boolean on if ordering should preserved or follow lexicographical order.
