### ISSUE TITLE
[Bug] zos_operator cannot run command containing quotes

### ISSUE THREAD

**Issue by petelouis** [ansible-collections/ibm_zos_core#262]
##### SUMMARY
I have zos_operator working for any "simple" command.  However, now I'm trying to use it to issue the following:
SETSSI ADD,S=DBC3,I=DSN3INI,P='DSN3EPX,-DBC3,S'

But, when I specify this command in my playbook, I can't seem to find any combination of quotes and escape characters that allows Ansible to parse it correctly.  I've tried the following and other variations, but all fail with one error or another:
- name: define db2 subsystem
  zos_operator:
    cmd: "'SETSSI ADD,S=DBC1,I=DSN3INI,P=\\'DSN3EPX,-DBC1,S\\''"

##### COMPONENT NAME
zos_operator

##### ANSIBLE VERSION

```
Ansible version output:
ansible 2.9.15
  config file = /home/plouis/ansible/ansible.cfg
  configured module search path = ['/home/plouis/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Aug 18 2020, 08:33:21) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

```

##### SPECIFY ANSIBLE COLLECTION VERSION

"version": "1.3.0-beta.1",

##### SPECIFY THE Z OPEN AUTOMATION UTILITIES VERSION

2020/07/07 14:54:31 CUT V1.0.3  

##### ENVIRONMENT

Ansible running on RHEL 8.3, z/OS is 2.4 at RSU2009

**Comment by petelouis** [comment]
Here's another command that zos_operator can't seem to run:
-DBC1 START DB2
One or more of Ansible/Python/ZOAU is unable to handle the '-' as the subsystem command prefix.  If there's a magical sequence of escape characters to make it work, I could use some help figuring out what it is.

**Comment by petelouis** [comment]
I've fixed the DB2 start command using the following syntax, suggested by the zoau opercmd doc:
  zos_operator:
    cmd: "-- '-DBC1 START DB2'"

Still struggling with the SETSSI command.

**Comment by ddimatos** [comment]
@richp405 - can you help out here given you recently overhauled zos_operator. Can you run some of his commands, get a sense of if we need to do some pre-processing to determine if this is a bug or an enhancement so we can get it into plan.

**Comment by richp405** [comment]
I don't think you need the quotes in the setssi command.  I ran a manual version of operator, and it kept complaining about the comma around position 50.  What I ran that 'seemed' to work was: "SETSSI ADD,S=DBC1,I=DSN3INI,P=DSN3EPX,-DBC1,S".  I bvelieve that the comma after the X in P=DSN3EPX is a parameter separator, which doesn't need quoted.  
If I'm reading correctly, you are running 1.3 beta 1, and may need to update to 1.3 beta 2 for the newer rexx script.

**Comment by petelouis** [comment]
If I remove the quotes from this command I get the following:
SETSSI ADD,S=DBC1,I=DSN3INI,P=DSN3EPX,-DBC1,S  
ASA100I SYNTAX ERROR: CONSNAME 286             
EXPECTED BEFORE -DBC1.                         
DETECTING MODULE IS IEFJSMSG

**Comment by ddimatos** [comment]
@petelouis - please upgrade to 1.3.0-beta.2 where we have [rewritten zos_operator module](https://github.com/ansible-collections/ibm_zos_core/pull/255) and try your commands with that version. There is logistical reasons for the rewrite and to not patch older versions. 

You can review the changes in 1.3.0-beta.2 [here](https://ibm.github.io/z_ansible_collections_doc/ibm_zos_core/docs/source/release_notes.html#version-1-3-0-beta-2) , it should be very simple update for you as  1.3.0-beta.2 still relies on the same version of ZOAU 1.1.0.

`ansible-galaxy collection install --force ibm.ibm_zos_core`

**Comment by petelouis** [comment]
Upgraded to 1.3.0-beta.2; now I get different errors.  Now this:
  zos_operator:
    cmd: "SETSSI ADD,S=DBC1,I=DSN3INI,P=\\'DSN3EPX,-DBC1,S\\'"
returns this:
2021-04-12 16:55:01,546 p=33361 u=plouis n=ansible | TASK [define db2 subsystem cmd=SETSSI ADD,S=DBC1,I=DSN3INI,P=\'DSN3EPX,-DBC1,S\', verbose=True] ***
2021-04-12 16:55:05,501 p=33361 u=plouis n=ansible | fatal: [tvt5033.svl.ibm.com]: FAILED! => {"changed": false, "msg": "OperatorCmdError(' 0 \"SETSSI ADD,S=DBC1,I=DSN3INI,P=\\\\\\'DSN3EPX,-DBC1,S\\\\\\'\" VERB WAIT', 12, ['====================', 'result code:  12', '====================', '', 'Action messages', '', '', 'ISF050I USER=SYSADM GROUP= PROC=REXX TERMINAL=0941D0FB', 'ISF051I SAF Access allowed SAFRC=0 ACCESS=READ CLASS=SDSF RESOURCE=GROUP.ISFSPROG.SDSF', 'ISF050I USER=SYSADM GROUP=ISFSPROG PROC=REXX TERMINAL=0941D0FB', 'ISF051I SAF No decision    SAFRC=4 ACCESS=READ CLASS=SDSF RESOURCE=ISFCMD.FILTER.PREFIX', 'ISF053I COMMAND=PREFIX Access allowed', 'ISF051I SAF Access allowed SAFRC=4 ACCESS=READ CLASS=SDSF RESOURCE=ISFCMD.FILTER.OWNER', 'ISF051I SAF No decision    SAFRC=4 ACCESS=READ CLASS=SDSF RESOURCE=ISFOPER.DEST.JES2', 'ISF051I SAF No decision    SAFRC=4 ACCESS=READ CLASS=SDSF RESOURCE=ISFOPER.ANYDEST.JES2', 'ISF302E \",\" was seen in command position 50 where one of the following was expected: (, END-OF-STMT, QUOTED-STRING, UNQUOTED-STRING.', 'ISF767I Request completed.', '', '', 'Ran:  0 \"SETSSI ADD,S=DBC1,I=DSN3INI,P=\\\\\\'DSN3EPX,-DBC1,S\\\\\\'\" VERB WAIT'])"}

**Comment by petelouis** [comment]
in the cmd statement above, the single back slashes are actually double back slashes

**Comment by richp405** [comment]
I think I understand what's going on... this is a bit convoluted, but here's what I got to look succeeessful on my EC:

"SETSSI ADD,S=DBC1,I=DSN3INI,P=''DSN3EPX,-DBC1,S''"

The confusion involves dealing with quotes and apostrophes.  The Rexx script takes in 'command' and wraps it in single-quotes (apostrophes)... the code looks like this:

 address SDSF "ISFEXEC '/"command"'" verbose

So, when the command includes apostrophes, things get a little wonky.  For apostrophes, like to wrap the 'P' parameters, you need to use double-apostrophes (capital thing by the enter key)... that tells Rexx to treat it as a single apostrophe, even though it's inside another apostrophe.

I will be back later today and put this in a playbook, just to double-check...I've been running a copy of the rexx script used by ansible manually, just so I could try things more quickly.

**Comment by petelouis** [comment]
That worked, thanks.  I thought I had tried that before, but maybe not that exact combination, or maybe it didn't work on the earlier version of zos_operator.  Anyway, I think we can go ahead and close this.

**Comment by richp405** [comment]
I'm glad it worked.  I will close this ticket, but I'll see if I can tweak the documentation so that other people don't run afoul of that issue.
