### ISSUE TITLE
Be sure the collection is tested against 2.11 and contains sanity/ignore-2.12.txt if applicable #37

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/ibm_zos_core#264]
##### SUMMARY
https://github.com/ansible-collections/overview/issues/45#issuecomment-813821100

If everything is OK, feel free to close the issue

**Comment by ddimatos** [comment]
Thanks @Andersson007 - same day you posted that, I asked the same question to @thedoubl3j :). Its on my todo list.

**Comment by Andersson007** [comment]
@ddimatos thanks you !

**Comment by ddimatos** [comment]
I went ahead and added it seeing as Ansible 2.12 is targeted for 3Q.
https://github.com/ansible-collections/ibm_zos_core/pull/271

**Comment by Andersson007** [comment]
@ddimatos ignore-2.12.txt is needed to test against Ansible `devel` branch, so if you have ignore-2.11.txt, we should copy it to ignore-2.12.txt so that sanity tests won't fail.
Ok, I see that you added it, thanks!
