### ISSUE TITLE
Trying to run a playbook to test zos ansible, but it says zoautil.so was not found, though $LIBPATH is correct

### ISSUE THREAD

**Issue by rinaldou** [ansible-collections/ibm_zos_core#281]
##### SUMMARY

Trying to run a simple playbook just to test, but it says zoautil.so was not found.

Playbook dataset.yaml

- hosts: zos
  collections:
    - ibm.ibm_zos_core
  gather_facts: yes
  vars:
    tgt_tmp_dir: "/tmp"
    ctl_tmp_dir: "/tmp"
    job_name: "HELLO"
  connection: ibm.ibm_zos_core.zos_ssh
  remote_user: xxxxxxx

  tasks:
    - name: Create a PDS data set
      zos_data_set:
        name: "K4120.SU09849.TESTE01"
        type: pds
        size: 5M
        format: fb
        record_length: 80
        replace: yes
      register: result

    - name: Response for create a PDS data set {{ data_set_name }}
      debug:
        msg: "{{ result }}"

And it returns the following error. 

TASK [Create a PDS data set] ***********************************************************************************************************************
fatal: [zostcpip02]: FAILED! => {"changed": false, "module_stderr": "Shared connection to x.x.x.x closed.\r\n", "module_stdout": "CEE3501S The module zoautil.so was not found.\r\n         From compile unit TOROLABA:./Python/dynload_shlib.c at entry point _PyImport_FindSharedFuncptr at statement 100 at compile unit offset +000000003814C798 at entry offset +0000000000000290 at address 000000003814C798.\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 137}

When I ssh to zos, I checked all env variables, and it looks OK.
/u/user> echo $_BPXK_AUTOCVT
ON
/u/user> echo $ZOAU_HOME
/usr/lpp/PRODUTOS/zoau/v1r1
/u/user> echo $PATH
/usr/lpp/java/J8.0_64/bin:/bin:/usr/lpp/PRODUTOS/python/v3r9/pyz/bin:/usr/lpp/PRODUTOS/zoau/v1r1/bin
/u/user> echo $LIBPATH
/lib:/usr/lpp/internet/bin:/usr/lpp/ctg/bin:/usr/lib:.:/usr/lpp/PRODUTOS/python/v3r9/pyz/lib:/usr/lpp/PRODUTOS/zoau/v1r1/lib
/u/user> echo $CLASSPATH
/usr/lpp/ctg/classes/ctgclient.jar:/usr/lpp/ctg/classes/ctgserver.jar:/serpro/batch:/usr/lpp/PRODUTOS/zoau/v1r1/lib/*
/u/user> echo $PYTHONPATH
/usr/lpp/PRODUTOS/zoau/v1r1/lib

Also running some zoau commands seems fine:

home/usr> zoaversion
2021/03/26 15:44:32 CUT V1.1.1

So, I don't know why python can find zoautil.so it is located in /usr/lpp/PRODUTOS/zoau/v1r1/lib, and it is defined in $LIBPATH.

##### ANSIBLE VERSION

```
Ansible version output:
```

##### STEPS TO REPRODUCE

```yaml
Reproduction playbook/yaml
```

##### ACTUAL RESULTS

```
Playbook output:
```

#### Ansible.cfg

```
'ansible-config dump --only-changed' output:
```

#### Inventory

```
Inventory content:
```

#### Vars

```
'group_vars' or 'host_vars' content:
```

**Comment by richp405** [comment]
@rinaldou : 
The error you mention means that the ansible core is calling zoau, and either the core, or zoau itself can't find the needed extension.  I can duplicate this behavior if I eliminate or mistype some environment variables.

We may need to double-check other things, but let's start with the following:

1 - Make sure you have zoau installed on the target: run 'zoaversion' at a command prompt, and it should return the version number.
2 - you have the following environment values configured:
ZOAU_HOME: (main folder where zoau is installed)
ZOAU: (main folder)/bin
PYTHONPATH: (main folder where zoau is installed)/lib
you can see the values by entering SET at a command prompt, although you may have to scroll or grep to find these values.

The one that always zinged me early on was 'PYTHONPATH'... grammatically it looks like "where's python", but it's actually for zoau to find its library.  IF you have PYTHONPATH defined, list that directory (ls $PYTHONPATH) and see if the .so file is there.

If correcting PYTHONPATH works, great!  If not, send me that zoaversion output, and the output of the SET command.

**Comment by richp405** [comment]
@rinaldou I'm trying to check in and see if you got the issue resolved, or if I can help in any way.

**Comment by rinaldou** [comment]
Hello!
Thanks for the reply.
All the environment variables were set correctly, I could make an echo $VARIABLE in each one mentioned and it was OK.
To solve this issue, I had to insert the enviroment variables directly in the ansible playbook. Then I was able to run the playbook as expected.

**Comment by richp405** [comment]
When you said "insert environment into the playbook", could you clarify what you did?  I would have thought you would need to modify ansible.cfg, which can send environment variables, so the "in the playbook" part confuses me.  Whenever ansible runs a process on the target, it sends environment variables as part of the process.  

Let me know what you did, so I can see more clearly what happened.

**Comment by rinaldou** [comment]
Into the playbook, I did:

- hosts: zostcpip02
  collections:
    - ibm.ibm_zos_core
  gather_facts: yes
  environment: "{{ environment_vars }}"

then, in the folder host_vars/zostcpip02.yaml

PYZ: "/usr/lpp/PRODUTOS/python/v3r9/pyz"
ZOAU: "/usr/lpp/PRODUTOS/zoau/v1r1"

environment_vars:
  _BPXK_AUTOCVT: "ON"
  ZOAU_HOME: "{{ ZOAU }}"

  PYTHONPATH: "{{ ZOAU }}/lib"

  LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
  PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin:/usr/sbin:/var/bin"
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_ERR: "txt"
  _TAG_REDIR_IN: "txt"
  _TAG_REDIR_OUT: "txt"
  LANG: "C"

**Comment by ddimatos** [comment]
From what I can tell with what has been shared and commented that your configuration looks correct, albeit I have not seen your **inventory** (but that would yield a different error), zos_ansible_core **version**, a verbose stdout using`-vvvv` (ansible-playbook -i inventory myplaybook.yaml -vvvv) and formatting is off on your posts  making it a bit harder to read/validate your indentations (you can use 3 back ticks ``` around your code snippets at the top and bottom so its easier for us to read).

As far as the error you shared, the RC 137 I have seen only twice, one using IBM python with ZOAU older than v1.0.3 (which is not your case) and when Ansible calls out to ZOAU and memory is requested above the bar for ZOAU's 64 bit needs.

When Ansible executes on z/OS the amount of memory needed above the bar can vary by the operations being performed in an Ansible task. For example, a module such as `zos_copy` does use system buffers and might require a MEMLIMIT adjustment, this can be true for many of our z/OS modules as well as the Ansible modules from the community. We recommend you start with the z/OS system default of 2G, “If MEMLIMIT is not specified in SMFPRMxx, the default value for this system default is 2G”.

You can avoid the setting SMFPRMxx parameter MEMLIMIT at the system level by setting MEMLIMIT in the [field-level access for the OMVS segment](https://www.ibm.com/docs/en/zos/2.4.0?topic=uids-setting-limits-users)  of a user profile. What is set in the OMVS Segment takes precedence over SMFPRMxx.

In other words, the [SMFPRMxx limit](https://www.ibm.com/docs/en/zos/2.2.0?topic=parameters-statements-smfprmxx) has no effect if the user has a limit specified in their OMVS segment.

You might consider monitoring your syslog when this error occurs and look for an error that resembles ABEND=S000 U4093 REASON=00000224 where [x224 is defined](https://www.ibm.com/docs/en/zos/2.3.0?topic=codes-u4093-xffd) as:
```
X'224' (548)
    The 64-bit virtual limit (MEMLIMIT) was 0. This setting prevents the initialization and execution of an AMODE 64 application under Language Environment since storage above 2GB cannot be allocated. SMFPRMxx parameter MEMLIMIT, JCL JOB statement keyword MEMLIMIT, and JCL EXEC statement MEMLIMIT keyword are some of the mechanisms for setting the amount of 64-bit virtual storage that can be allocated in the address space. See z/OS MVS Programming: Extended Addressability Guide for more information on setting MEMLIMIT and how the system determines what value to use.
```

**Comment by ddimatos** [comment]
Past 30 days, closing, reopen if necessary.
