### ISSUE TITLE
IBM User Mapper

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/ibm_zos_core#295]
Hi, 
Sorry for abusing this Issue Tracker.

@balkajbaf I've received a request to approve `IBM User Mapper` for github.com/ansible-collection.

Can you please explain what this is for, and why it's needed?

Kind regards,
John "gundalow" Barker
Manager, Ansible Community Team

**Comment by balkajbaf** [comment]
@gundalow I sent you an email regarding your question. please follow up with me from there. Thanks!
