### ISSUE TITLE
module zos_copy is prompting for password

### ISSUE THREAD

**Issue by WladyslawBorysow** [ansible-collections/ibm_zos_core#300]
Hello,
I prepared playbook which includes also zos_copy module. Before copy stage ansible prompts for password although I provided my password in ansible.cfg

 name: Copy local binary file to ds (copy from RHEL to ZOS)
 zos_copy:
        src: /etc/ansible/playbooks/files/WWZ038.GSD##E1.FSA101.DUMPTERS.D030320.BIN
        dest: WWZ038.GSD##E1.FSA101.DUMPTERS.D030320.BIN
        force: yes
        ignore_sftp_stderr: true
        is_binary: true

I am using ansible core 1.3.1. and ZOAU CUT V1.1.1     
What could be the reason for that?
Thank You!
Wladyslaw

**Comment by adn1107** [comment]
Hi Wladyslaw, can you run the playbook again with -vvv and attach the full log of the failed play/task here?

**Comment by adn1107** [comment]
also check that the playbook is using the ansible.cfg file you are expecting.

additional discussion regarding using passing password to playbook: 
https://stackoverflow.com/questions/37004686/how-to-pass-a-user-password-in-ansible-command

**Comment by WladyslawBorysow** [comment]
Hello,

[playbook.txt](https://github.com/ansible-collections/ibm_zos_core/files/7254633/playbook.txt)
[playbook log.txt](https://github.com/ansible-collections/ibm_zos_core/files/7254634/playbook.log.txt)
[hosts.txt](https://github.com/ansible-collections/ibm_zos_core/files/7254636/hosts.txt)

Will also check the link:)
Maybe password prompt is connected with sftp transfer...

Thank You once again

**Comment by adn1107** [comment]
I re-created your problem. Looking for solution now....

**Comment by adn1107** [comment]
looks like this is a known problem: https://github.com/ansible-collections/ibm_zos_core/issues/130

@ddimatos , i am not 100% sure but sounds like to avoid this issue, SSH connection is required/recommended.

**Comment by itsBryantP** [comment]
The fix for this issue is currently available in [release 1.4.0-beta.1](https://ibm.github.io/z_ansible_collections_doc/ibm_zos_core/docs/source/release_notes.html#version-1-4-0-beta-1)

**Comment by adn1107** [comment]
@itsBryantP , Thanks. I see it in the release note:

When using the zos_copy or zos_fetch modules in earlier versions of this collection without ‘passwordless’ SSH configured such that you are using --ask-pass or passing an ansible_password in a configuration; during the playbook execution a second password prompt for SFTP would appear pausing the playbook execution. This is resolved in this release.

**Comment by adn1107** [comment]
i installed 1.4.0-beta.1 version and it worked

(base) ➜  certificate_management git:(cert_renew) ✗ ansible-galaxy collection install ibm.ibm_zos_core:1.4.0-beta.1 --force
Process install dependency map
Starting collection install process
Installing 'ibm.ibm_zos_core:1.4.0-beta.1' to '/Users/adn/.ansible/collections/ansible_collections/ibm/ibm_zos_core'
