### ISSUE TITLE
zos_copy can't copy the local file to a PDS member against the error "b'mvscmdauth" not found

### ISSUE THREAD

**Issue by hyzhang6639** [ansible-collections/ibm_zos_core#302]
Please raise issues via the [new interface](https://github.com/ansible/ansible/issues/new/choose)
zos_copy failed to copy the local file to a PDS member against the below error:

fatal: [zos_host]: FAILED! => {"changed": false, "msg": "[Errno 129] EDC5129I No such file or directory.: b'mvscmdauth'", "rc": 129, "stderr": null, "stderr_lines": [], "stdout": null, "stdout_lines": []}

Actually I have see the similar error in the below link and have confirmed that the ZOAU has been set correctly. 
https://ibm.github.io/z_ansible_collections_doc/troubleshooting/errorsandmessages.html

Env info:
ibm.ibm_zos_core    1.3.1  
ibm.ibm_zos_sysauto 1.0.0

**Comment by rchech** [comment]
I am also getting the same error. How this was resolved ? above link is no more exist. Please help on this.
