### ISSUE TITLE
[Bug] Ansible-test sanity reporting discrepancies when run on ansible-core 2.12, expanding to 2.13 and 2.14 (updated to include other versions, see comments)

### ISSUE THREAD

**Issue by fernandofloresg** [ansible-collections/ibm_zos_core#343]
##### SUMMARY
Similar to issue #330 we did an analysis based on Ansible-core 2.12.7. Running `Ansible-test sanity` get

##### ANSIBLE VERSION

```
(ansible-2.12) fernandoflores@Oscars-MacBook-Pro ibm_zos_core % ansible --version 
ansible [core 2.12.7]
  config file = None
  configured module search path = ['/Users/fernandoflores/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/fernandoflores/venvs/ansible-2.12/lib/python3.8/site-packages/ansible
  ansible collection location = /Users/fernandoflores/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/fernandoflores/venvs/ansible-2.12/bin/ansible
  python version = 3.8.9 (default, Apr 13 2022, 08:48:07) [Clang 13.1.6 (clang-1316.0.21.2.5)]
  jinja version = 3.1.2
  libyaml = True

```

##### STEPS TO REPRODUCE

First reduce the galaxy.yml build_ignore section to leave behind ingore.txt's
build_ignore:

- Jenkinsfile
- ansible.cfg
- .gitignore
- .github
- '*.tar.gz'
- docs
- collections
- docs

Then 

```
rm -rf ibm-ibm_zos_core-*.tar.gz; ansible-galaxy collection build; ansible-galaxy collection install -f ibm-ibm_zos_core-*
cd /Users/<user>/.ansible/collections/ansible_collections/ibm/ibm_zos_core
ansible-test sanity
```

##### EXPECTED RESULTS
You will see this output:

`
(ansible-2.12) fernandoflores@Oscars-MacBook-Pro ibm_zos_core % ansible-test sanity
Running sanity test "action-plugin-docs"
Running sanity test "ansible-doc"
ERROR: Output on stderr from ansible-doc is considered an error.

Command "ansible-doc -t module ibm.ibm_zos_core.zos_apf ibm.ibm_zos_core.zos_backup_restore ibm.ibm_zos_core.zos_blockinfile ibm.ibm_zos_core.zos_copy ibm.ibm_zos_core.zos_data_set ibm.ibm_zos_core.zos_encode ibm.ibm_zos_core.zos_fetch ibm.ibm_zos_core.zos_find ibm.ibm_zos_core.zos_job_output ibm.ibm_zos_core.zos_job_query ibm.ibm_zos_core.zos_job_submit ibm.ibm_zos_core.zos_lineinfile ibm.ibm_zos_core.zos_mount ibm.ibm_zos_core.zos_mvs_raw ibm.ibm_zos_core.zos_operator ibm.ibm_zos_core.zos_operator_action_query ibm.ibm_zos_core.zos_ping ibm.ibm_zos_core.zos_tso_command" returned exit status 0.
>>> Standard Error
[WARNING]: Collection ibm.ibm_zos_core does not support Ansible version 2.12.7
Running sanity test "changelog"
WARNING: Skipping sanity test "compile" on Python 2.6 because it could not be found.
WARNING: Skipping sanity test "compile" on Python 2.7 because it could not be found.
WARNING: Skipping sanity test "compile" on Python 3.5 because it could not be found.
WARNING: Skipping sanity test "compile" on Python 3.6 because it could not be found.
WARNING: Skipping sanity test "compile" on Python 3.7 because it could not be found.
Running sanity test "compile" on Python 3.8
WARNING: Skipping sanity test "compile" on Python 3.9 because it could not be found.
WARNING: Skipping sanity test "compile" on Python 3.10 because it could not be found.
Running sanity test "empty-init"
Running sanity test "future-import-boilerplate"
Running sanity test "ignores"
WARNING: Skipping sanity test "import" on Python 2.6 because it could not be found.
WARNING: Skipping sanity test "import" on Python 2.7 because it could not be found.
WARNING: Skipping sanity test "import" on Python 3.5 because it could not be found.
WARNING: Skipping sanity test "import" on Python 3.6 because it could not be found.
WARNING: Skipping sanity test "import" on Python 3.7 because it could not be found.
Running sanity test "import" on Python 3.8
WARNING: Skipping sanity test "import" on Python 3.9 because it could not be found.
WARNING: Skipping sanity test "import" on Python 3.10 because it could not be found.
Running sanity test "line-endings"
Running sanity test "metaclass-boilerplate"
Running sanity test "no-assert"
Running sanity test "no-basestring"
Running sanity test "no-dict-iteritems"
Running sanity test "no-dict-iterkeys"
Running sanity test "no-dict-itervalues"
Running sanity test "no-get-exception"
Running sanity test "no-illegal-filenames"
Running sanity test "no-main-display"
Running sanity test "no-smart-quotes"
Running sanity test "no-unicode-literals"
Running sanity test "pep8"
Running sanity test "pslint"
Running sanity test "pylint"
Running sanity test "replace-urlopen"
Running sanity test "runtime-metadata"
Running sanity test "shebang"
Running sanity test "shellcheck"
Running sanity test "symlinks"
Running sanity test "use-argspec-type-path"
Running sanity test "use-compat-six"
Running sanity test "validate-modules"
ERROR: Found 133 validate-modules issue(s) which need to be resolved:
ERROR: plugins/modules/zos_apf.py:0:0: missing-gplv3-license: GPLv3 license header not found in the first 20 lines of the module
ERROR: plugins/modules/zos_backup_restore.py:0:0: doc-choices-do-not-match-spec: Argument 'space_type' in argument_spec defines choices as ([]) but documentation defines choices as (['K', 'M', 'G', 'CYL', 'TRK'])
ERROR: plugins/modules/zos_backup_restore.py:0:0: doc-required-mismatch: Argument 'data_sets' in argument_spec is not required, but is documented as being required
ERROR: plugins/modules/zos_backup_restore.py:0:0: doc-required-mismatch: Argument 'include' in argument_spec found in data_sets is not required, but is documented as being required
ERROR: plugins/modules/zos_backup_restore.py:0:0: missing-gplv3-license: GPLv3 license header not found in the first 20 lines of the module
ERROR: plugins/modules/zos_blockinfile.py:0:0: missing-gplv3-license: GPLv3 license header not found in the first 20 lines of the module
ERROR: plugins/modules/zos_copy.py:0:0: doc-default-does-not-match-spec: Argument 'unsafe_writes' in argument_spec defines default as (False) but documentation defines default as (None)
ERROR: plugins/modules/zos_copy.py:0:0: doc-type-does-not-match-spec: Argument 'mode' in argument_spec defines type as 'raw' but documentation defines type as 'str'
ERROR: plugins/modules/zos_copy.py:0:0: doc-type-does-not-match-spec: Argument 'src' in argument_spec defines type as 'path' but documentation defines type as 'str'
ERROR: plugins/modules/zos_copy.py:0:0: invalid-ansiblemodule-schema: AnsibleModule.argument_spec.destination_dataset.options.dd_type.arg_type: extra keys not allowed @ data['argument_spec']['destination_dataset']['options']['dd_type']['arg_type']. Got 'str'
ERROR: plugins/modules/zos_copy.py:0:0: invalid-ansiblemodule-schema: AnsibleModule.argument_spec.destination_dataset.options.record_format.arg_type: extra keys not allowed @ data['argument_spec']['destination_dataset']['options']['record_format']['arg_type']. Got 'str'
ERROR: plugins/modules/zos_copy.py:0:0: invalid-ansiblemodule-schema: AnsibleModule.argument_spec.destination_dataset.options.space_primary.arg_type: extra keys not allowed @ data['argument_spec']['destination_dataset']['options']['space_primary']['arg_type']. Got 'int'
ERROR: plugins/modules/zos_copy.py:0:0: invalid-ansiblemodule-schema: AnsibleModule.argument_spec.destination_dataset.options.space_secondary.arg_type: extra keys not allowed @ data['argument_spec']['destination_dataset']['options']['space_secondary']['arg_type']. Got 'int'
ERROR: plugins/modules/zos_copy.py:0:0: invalid-ansiblemodule-schema: AnsibleModule.argument_spec.destination_dataset.options.space_type.arg_type: extra keys not allowed @ data['argument_spec']['destination_dataset']['options']['space_type']['arg_type']. Got 'str'
ERROR: plugins/modules/zos_copy.py:0:0: missing-gplv3-license: GPLv3 license header not found in the first 20 lines of the module
ERROR: plugins/modules/zos_copy.py:0:0: parameter-type-not-in-doc: Argument 'attributes' in argument_spec defines type as 'str' but documentation doesn't define type
ERROR: plugins/modules/zos_copy.py:0:0: parameter-type-not-in-doc: Argument 'copy_member' in argument_spec defines type as 'bool' but documentation doesn't define type
ERROR: plugins/modules/zos_copy.py:0:0: parameter-type-not-in-doc: Argument 'group' in argument_spec defines type as 'str' but documentation doesn't define type
ERROR: plugins/modules/zos_copy.py:0:0: parameter-type-not-in-doc: Argument 'is_mvs_dest' in argument_spec defines type as 'bool' but documentation doesn't define type
ERROR: plugins/modules/zos_copy.py:0:0: parameter-type-not-in-doc: Argument 'is_pds' in argument_spec defines type as 'bool' but documentation doesn't define type
ERROR: plugins/modules/zos_copy.py:0:0: parameter-type-not-in-doc: Argument 'is_uss' in argument_spec defines type as 'bool' but documentation doesn't define type
ERROR: plugins/modules/zos_copy.py:0:0: parameter-type-not-in-doc: Argument 'local_charset' in argument_spec defines type as 'str' but documentation doesn't define type
ERROR: plugins/modules/zos_copy.py:0:0: parameter-type-not-in-doc: Argument 'owner' in argument_spec defines type as 'str' but documentation doesn't define type
ERROR: plugins/modules/zos_copy.py:0:0: parameter-type-not-in-doc: Argument 'selevel' in argument_spec defines type as 'str' but documentation doesn't define type
ERROR: plugins/modules/zos_copy.py:0:0: parameter-type-not-in-doc: Argument 'serole' in argument_spec defines type as 'str' but documentation doesn't define type
ERROR: plugins/modules/zos_copy.py:0:0: parameter-type-not-in-doc: Argument 'setype' in argument_spec defines type as 'str' but documentation doesn't define type
ERROR: plugins/modules/zos_copy.py:0:0: parameter-type-not-in-doc: Argument 'seuser' in argument_spec defines type as 'str' but documentation doesn't define type
ERROR: plugins/modules/zos_copy.py:0:0: parameter-type-not-in-doc: Argument 'size' in argument_spec defines type as 'int' but documentation doesn't define type
ERROR: plugins/modules/zos_copy.py:0:0: parameter-type-not-in-doc: Argument 'src_member' in argument_spec defines type as 'bool' but documentation doesn't define type
ERROR: plugins/modules/zos_copy.py:0:0: parameter-type-not-in-doc: Argument 'temp_path' in argument_spec defines type as 'str' but documentation doesn't define type
ERROR: plugins/modules/zos_copy.py:0:0: parameter-type-not-in-doc: Argument 'unsafe_writes' in argument_spec defines type as 'bool' but documentation doesn't define type
ERROR: plugins/modules/zos_copy.py:0:0: undocumented-parameter: Argument 'attr' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_copy.py:0:0: undocumented-parameter: Argument 'attributes' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_copy.py:0:0: undocumented-parameter: Argument 'copy_member' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_copy.py:0:0: undocumented-parameter: Argument 'group' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_copy.py:0:0: undocumented-parameter: Argument 'is_mvs_dest' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_copy.py:0:0: undocumented-parameter: Argument 'is_pds' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_copy.py:0:0: undocumented-parameter: Argument 'is_uss' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_copy.py:0:0: undocumented-parameter: Argument 'local_charset' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_copy.py:0:0: undocumented-parameter: Argument 'owner' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_copy.py:0:0: undocumented-parameter: Argument 'selevel' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_copy.py:0:0: undocumented-parameter: Argument 'serole' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_copy.py:0:0: undocumented-parameter: Argument 'setype' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_copy.py:0:0: undocumented-parameter: Argument 'seuser' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_copy.py:0:0: undocumented-parameter: Argument 'size' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_copy.py:0:0: undocumented-parameter: Argument 'src_member' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_copy.py:0:0: undocumented-parameter: Argument 'temp_path' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_copy.py:0:0: undocumented-parameter: Argument 'unsafe_writes' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_data_set.py:0:0: doc-choices-do-not-match-spec: Argument 'record_format' in argument_spec defines choices as ([]) but documentation defines choices as (['FB', 'VB', 'FBA', 'VBA', 'U'])
ERROR: plugins/modules/zos_data_set.py:0:0: doc-choices-do-not-match-spec: Argument 'record_format' in argument_spec found in batch defines choices as ([]) but documentation defines choices as (['FB', 'VB', 'FBA', 'VBA', 'U'])
ERROR: plugins/modules/zos_data_set.py:0:0: doc-choices-do-not-match-spec: Argument 'space_type' in argument_spec defines choices as ([]) but documentation defines choices as (['K', 'M', 'G', 'CYL', 'TRK'])
ERROR: plugins/modules/zos_data_set.py:0:0: doc-choices-do-not-match-spec: Argument 'space_type' in argument_spec found in batch defines choices as ([]) but documentation defines choices as (['K', 'M', 'G', 'CYL', 'TRK'])
ERROR: plugins/modules/zos_data_set.py:0:0: doc-choices-do-not-match-spec: Argument 'type' in argument_spec defines choices as ([]) but documentation defines choices as (['KSDS', 'ESDS', 'RRDS', 'LDS', 'SEQ', 'PDS', 'PDSE', 'LIBRARY', 'BASIC', 'LARGE', 'MEMBER', 'HFS', 'ZFS'])
ERROR: plugins/modules/zos_data_set.py:0:0: doc-choices-do-not-match-spec: Argument 'type' in argument_spec found in batch defines choices as ([]) but documentation defines choices as (['KSDS', 'ESDS', 'RRDS', 'LDS', 'SEQ', 'PDS', 'PDSE', 'LIBRARY', 'BASIC', 'LARGE', 'MEMBER', 'HFS', 'ZFS'])
ERROR: plugins/modules/zos_data_set.py:0:0: doc-default-does-not-match-spec: Argument 'record_format' in argument_spec defines default as (None) but documentation defines default as ('FB')
ERROR: plugins/modules/zos_data_set.py:0:0: doc-default-does-not-match-spec: Argument 'record_format' in argument_spec found in batch defines default as (None) but documentation defines default as ('FB')
ERROR: plugins/modules/zos_data_set.py:0:0: doc-default-does-not-match-spec: Argument 'space_primary' in argument_spec defines default as (None) but documentation defines default as (5)
ERROR: plugins/modules/zos_data_set.py:0:0: doc-default-does-not-match-spec: Argument 'space_primary' in argument_spec found in batch defines default as (None) but documentation defines default as (5)
ERROR: plugins/modules/zos_data_set.py:0:0: doc-default-does-not-match-spec: Argument 'space_secondary' in argument_spec defines default as (None) but documentation defines default as (3)
ERROR: plugins/modules/zos_data_set.py:0:0: doc-default-does-not-match-spec: Argument 'space_secondary' in argument_spec found in batch defines default as (None) but documentation defines default as (3)
ERROR: plugins/modules/zos_data_set.py:0:0: doc-type-does-not-match-spec: Argument 'space_primary' in argument_spec defines type as 'raw' but documentation defines type as 'int'
ERROR: plugins/modules/zos_data_set.py:0:0: invalid-ansiblemodule-schema: AnsibleModule.argument_spec.state.dependencies: extra keys not allowed @ data['argument_spec']['state']['dependencies']. Got ['batch']
ERROR: plugins/modules/zos_data_set.py:0:0: missing-gplv3-license: GPLv3 license header not found in the first 20 lines of the module
ERROR: plugins/modules/zos_data_set.py:0:0: no-log-needed: Argument 'key_length' in argument_spec could be a secret, though doesn't have `no_log` set
ERROR: plugins/modules/zos_data_set.py:0:0: no-log-needed: Argument 'key_length' in argument_spec could be a secret, though doesn't have `no_log` set found in batch
ERROR: plugins/modules/zos_data_set.py:0:0: no-log-needed: Argument 'key_offset' in argument_spec could be a secret, though doesn't have `no_log` set
ERROR: plugins/modules/zos_data_set.py:0:0: no-log-needed: Argument 'key_offset' in argument_spec could be a secret, though doesn't have `no_log` set found in batch
ERROR: plugins/modules/zos_data_set.py:0:0: undocumented-parameter: Argument 'data_class' found in batch is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_data_set.py:0:0: undocumented-parameter: Argument 'data_class' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_data_set.py:0:0: undocumented-parameter: Argument 'format' found in batch is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_data_set.py:0:0: undocumented-parameter: Argument 'format' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_data_set.py:0:0: undocumented-parameter: Argument 'size' found in batch is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_data_set.py:0:0: undocumented-parameter: Argument 'size' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_encode.py:0:0: missing-gplv3-license: GPLv3 license header not found in the first 20 lines of the module
ERROR: plugins/modules/zos_fetch.py:0:0: missing-gplv3-license: GPLv3 license header not found in the first 20 lines of the module
ERROR: plugins/modules/zos_fetch.py:0:0: parameter-type-not-in-doc: Argument 'local_charset' in argument_spec defines type as 'str' but documentation doesn't define type
ERROR: plugins/modules/zos_fetch.py:0:0: undocumented-parameter: Argument 'local_charset' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_find.py:0:0: missing-gplv3-license: GPLv3 license header not found in the first 20 lines of the module
ERROR: plugins/modules/zos_find.py:0:0: parameter-list-no-elements: Argument 'excludes' in argument_spec defines type as list but elements is not defined
ERROR: plugins/modules/zos_find.py:0:0: parameter-list-no-elements: Argument 'patterns' in argument_spec defines type as list but elements is not defined
ERROR: plugins/modules/zos_find.py:0:0: parameter-list-no-elements: Argument 'pds_patterns' in argument_spec defines type as list but elements is not defined
ERROR: plugins/modules/zos_find.py:0:0: parameter-list-no-elements: Argument 'volume' in argument_spec defines type as list but elements is not defined
ERROR: plugins/modules/zos_job_output.py:0:0: missing-gplv3-license: GPLv3 license header not found in the first 20 lines of the module
ERROR: plugins/modules/zos_job_output.py:0:0: return-syntax-error: RETURN.jobs.contains.ddnames.contains.content.type: not a valid value for dictionary value @ data['jobs']['contains']['ddnames']['contains']['content']['type']. Got 'list[str]'
ERROR: plugins/modules/zos_job_query.py:0:0: missing-gplv3-license: GPLv3 license header not found in the first 20 lines of the module
ERROR: plugins/modules/zos_job_submit.py:0:0: doc-default-does-not-match-spec: Argument 'wait' in argument_spec defines default as (None) but documentation defines default as (False)
ERROR: plugins/modules/zos_job_submit.py:0:0: doc-required-mismatch: Argument 'location' in argument_spec is not required, but is documented as being required
ERROR: plugins/modules/zos_job_submit.py:0:0: missing-gplv3-license: GPLv3 license header not found in the first 20 lines of the module
ERROR: plugins/modules/zos_job_submit.py:0:0: parameter-type-not-in-doc: Argument 'temp_file' in argument_spec defines type as 'path' but documentation doesn't define type
ERROR: plugins/modules/zos_job_submit.py:0:0: return-syntax-error: RETURN.jobs.contains.ddnames.contains.content.type: not a valid value for dictionary value @ data['jobs']['contains']['ddnames']['contains']['content']['type']. Got 'list[str]'
ERROR: plugins/modules/zos_job_submit.py:0:0: undocumented-parameter: Argument 'temp_file' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_lineinfile.py:0:0: missing-gplv3-license: GPLv3 license header not found in the first 20 lines of the module
ERROR: plugins/modules/zos_mount.py:0:0: doc-default-does-not-match-spec: Argument 'unsafe_writes' in argument_spec defines default as (False) but documentation defines default as (None)
ERROR: plugins/modules/zos_mount.py:0:0: missing-gplv3-license: GPLv3 license header not found in the first 20 lines of the module
ERROR: plugins/modules/zos_mount.py:0:0: parameter-list-no-elements: Argument 'comment' in argument_spec found in persistent defines type as list but elements is not defined
ERROR: plugins/modules/zos_mount.py:0:0: parameter-type-not-in-doc: Argument 'attributes' in argument_spec defines type as 'str' but documentation doesn't define type
ERROR: plugins/modules/zos_mount.py:0:0: parameter-type-not-in-doc: Argument 'group' in argument_spec defines type as 'str' but documentation doesn't define type
ERROR: plugins/modules/zos_mount.py:0:0: parameter-type-not-in-doc: Argument 'mode' in argument_spec defines type as 'raw' but documentation doesn't define type
ERROR: plugins/modules/zos_mount.py:0:0: parameter-type-not-in-doc: Argument 'owner' in argument_spec defines type as 'str' but documentation doesn't define type
ERROR: plugins/modules/zos_mount.py:0:0: parameter-type-not-in-doc: Argument 'selevel' in argument_spec defines type as 'str' but documentation doesn't define type
ERROR: plugins/modules/zos_mount.py:0:0: parameter-type-not-in-doc: Argument 'serole' in argument_spec defines type as 'str' but documentation doesn't define type
ERROR: plugins/modules/zos_mount.py:0:0: parameter-type-not-in-doc: Argument 'setype' in argument_spec defines type as 'str' but documentation doesn't define type
ERROR: plugins/modules/zos_mount.py:0:0: parameter-type-not-in-doc: Argument 'seuser' in argument_spec defines type as 'str' but documentation doesn't define type
ERROR: plugins/modules/zos_mount.py:0:0: parameter-type-not-in-doc: Argument 'unsafe_writes' in argument_spec defines type as 'bool' but documentation doesn't define type
ERROR: plugins/modules/zos_mount.py:0:0: undocumented-parameter: Argument 'attr' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_mount.py:0:0: undocumented-parameter: Argument 'attributes' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_mount.py:0:0: undocumented-parameter: Argument 'group' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_mount.py:0:0: undocumented-parameter: Argument 'mode' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_mount.py:0:0: undocumented-parameter: Argument 'owner' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_mount.py:0:0: undocumented-parameter: Argument 'selevel' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_mount.py:0:0: undocumented-parameter: Argument 'serole' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_mount.py:0:0: undocumented-parameter: Argument 'setype' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_mount.py:0:0: undocumented-parameter: Argument 'seuser' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_mount.py:0:0: undocumented-parameter: Argument 'unsafe_writes' is listed in the argument_spec, but not documented in the module documentation
ERROR: plugins/modules/zos_mvs_raw.py:0:0: doc-required-mismatch: Argument 'content' in argument_spec found in dds -> dd_concat -> dds -> dd_input is required, but is not documented as being required
ERROR: plugins/modules/zos_mvs_raw.py:0:0: doc-required-mismatch: Argument 'content' in argument_spec found in dds -> dd_input is required, but is not documented as being required
ERROR: plugins/modules/zos_mvs_raw.py:0:0: doc-required-mismatch: Argument 'data_set_name' in argument_spec found in dds -> dd_concat -> dds -> dd_data_set is not required, but is documented as being required
ERROR: plugins/modules/zos_mvs_raw.py:0:0: doc-required-mismatch: Argument 'data_set_name' in argument_spec found in dds -> dd_data_set is not required, but is documented as being required
ERROR: plugins/modules/zos_mvs_raw.py:0:0: missing-gplv3-license: GPLv3 license header not found in the first 20 lines of the module
ERROR: plugins/modules/zos_mvs_raw.py:0:0: no-log-needed: Argument 'encryption_key_1' in argument_spec could be a secret, though doesn't have `no_log` set found in dds -> dd_concat -> dds -> dd_data_set
ERROR: plugins/modules/zos_mvs_raw.py:0:0: no-log-needed: Argument 'encryption_key_1' in argument_spec could be a secret, though doesn't have `no_log` set found in dds -> dd_data_set
ERROR: plugins/modules/zos_mvs_raw.py:0:0: no-log-needed: Argument 'encryption_key_2' in argument_spec could be a secret, though doesn't have `no_log` set found in dds -> dd_concat -> dds -> dd_data_set
ERROR: plugins/modules/zos_mvs_raw.py:0:0: no-log-needed: Argument 'encryption_key_2' in argument_spec could be a secret, though doesn't have `no_log` set found in dds -> dd_data_set
ERROR: plugins/modules/zos_mvs_raw.py:0:0: no-log-needed: Argument 'key_label' in argument_spec could be a secret, though doesn't have `no_log` set found in dds -> dd_concat -> dds -> dd_data_set
ERROR: plugins/modules/zos_mvs_raw.py:0:0: no-log-needed: Argument 'key_label' in argument_spec could be a secret, though doesn't have `no_log` set found in dds -> dd_data_set
ERROR: plugins/modules/zos_mvs_raw.py:0:0: no-log-needed: Argument 'key_length' in argument_spec could be a secret, though doesn't have `no_log` set found in dds -> dd_concat -> dds -> dd_data_set
ERROR: plugins/modules/zos_mvs_raw.py:0:0: no-log-needed: Argument 'key_length' in argument_spec could be a secret, though doesn't have `no_log` set found in dds -> dd_data_set
ERROR: plugins/modules/zos_mvs_raw.py:0:0: no-log-needed: Argument 'key_offset' in argument_spec could be a secret, though doesn't have `no_log` set found in dds -> dd_concat -> dds -> dd_data_set
ERROR: plugins/modules/zos_mvs_raw.py:0:0: no-log-needed: Argument 'key_offset' in argument_spec could be a secret, though doesn't have `no_log` set found in dds -> dd_data_set
ERROR: plugins/modules/zos_operator.py:0:0: missing-gplv3-license: GPLv3 license header not found in the first 20 lines of the module
ERROR: plugins/modules/zos_operator_action_query.py:0:0: missing-gplv3-license: GPLv3 license header not found in the first 20 lines of the module
ERROR: plugins/modules/zos_ping.py:0:0: missing-gplv3-license: GPLv3 license header not found in the first 20 lines of the module
ERROR: plugins/modules/zos_tso_command.py:0:0: missing-gplv3-license: GPLv3 license header not found in the first 20 lines of the module
See documentation for help: https://docs.ansible.com/ansible-core/2.12/dev_guide/testing/sanity/validate-modules.html
Running sanity test "yamllint"
ERROR: The 2 sanity test(s) listed below (out of 46) failed. See error output above for details.
ansible-doc
validate-modules
`

**Comment by ddimatos** [comment]
I have expanded this work item to include validating `ansible-core` 2.12 and 2.13

**Comment by ddimatos** [comment]
I have expanded this now to ansible versions: `['2.14.1', '2.13.7', '2.12.10', '2.11.12', '2.9.27', 'LATEST']`, this work item only covers the sanity testing not full regression (unit testing).

**Comment by ddimatos** [comment]
Pipeline ansible-test runs:
![Image](https://user-images.githubusercontent.com/25803172/214723876-8ee1d8fb-183d-4d87-abe7-6e6caa4c5ea7.png)

Corresponding jenkins builds with details for the above image:


![Image](https://user-images.githubusercontent.com/25803172/214724163-aba4a77f-ee38-4753-b9df-df24a7de8c38.png)
