### ISSUE TITLE
[Enhancement][zos_job_query] Include new return fields

### ISSUE THREAD

**Issue by cdmichalik** [ansible-collections/ibm_zos_core#347]
##### Enhancement
Module zos_job_query could benefit by providing more fields to the client such as job class, service class, priority, asid, queue, status, and job creation date.

##### USE CASE
System programmer wants to cycle a CICS region based on a developers request. A service ticket will kick of an Ansible playbook to determine if the CICS region is running and if so, cycle it, and determine if it started back up successfully. The ability to interrogate the status and queue fields allows the playbook to know if a region is up, down, or held.

System programmer wants to run a playbook to cycle CICS regions that have run for x number of days in service class y. Using the field job creation date and service class allows them to interrogate the fields to accomplish this task.

##### SUMMARY
Enhance module zos_job_query to provide more fields to the client such as job class, service class, priority, asid, queue, status, and job creation date. There are a large number of fields that can be attained and by adding these fields will give system programmers more flexibility and more use cases when automating.

##### DESIGN
I do not have any at this time but I assume (and I know I shouldn't) that when the job is queried, this information is available it just hasn't been coded to return. So hopefully it would not be too difficult to add the new fields.

**Comment by roded** [comment]
Hi, we specifically require the jobs' ASID for being able to signal the correct address space using operator commands.
If the ASID is an easy field to get from JES using the new C API, we'd very much appreciate it being implemented sooner rather than later.
Much obliged.

**Comment by ddimatos** [comment]
@cdmichalik - thank you , I did peek at some of the source, I brought forward to others what I discovered to have them weigh in on their thoughts. Depending on the outcome, if it is accepted, you will be able to track progress here in Git. 

The use cases help quite a bit, helps strengthen the value and need, thank you for putting effort into writing them, anytime someone spends time writing a complete JIRA it saves time for everyone and ensures clarity.

**Comment by ddimatos** [comment]
@cdmichalik - team is evaluating the APIs and macros available, soonest we would expect this could be completed is Q2 of 2022, please keep an eye on it, for now I am moving it to the backlog and will track it there.

**Comment by ddimatos** [comment]
Current target is 1.8.0-beta.1, this could come sooner (1.7.0-beta.1) but because these new attributes would impact our job.py in module_utils, our common parsing code, we allow for more time to evaluate this. This also depends on ZOAU changes yet to be released, so better to target 1.8.0-beta.1 (likely release start of Q4).

**Comment by storfibm** [comment]
@cdmichalik Could you please clarify what queue field information you are looking for specifically? Are any of the queue fields you are interested in listed on this page? https://www.ibm.com/docs/en/zos/2.4.0?topic=sp-status-panel-st

**Comment by richp405** [comment]
Validation interrupted by server upgrade issues.  Should be able to put this to PR this week.

**Comment by richp405** [comment]
Build now passes, code has gotten through one reviewer already.

**Comment by cdmichalik** [comment]
Thank you! I have been on child bonding leave so I am just now seeing these updates. I will let the client know this change is moving through the pipeline.

**Comment by ddimatos** [comment]
Congratulations @cdmichalik , its a wonderful time. 

The fields will be in our doc but for reference, using zoau 1.2.3:
```
job_class
svc_class
priority
asid
creation_date
creation_time
queue_position
```
Using zoau 1.2.4 adds `program_name`

**Comment by cdmichalik** [comment]
Perfect! Thank you. This will definitely help clients with more use cases
