### ISSUE TITLE
[Bug] [zos_job_query] failed when the `job_name` was null or not found

### ISSUE THREAD

**Issue by adn1107** [ansible-collections/ibm_zos_core#381]
`- name: Check CTL Up
        zos_job_query:
          job_name: "{{ DFS_IMS_SSID }}CTL"
        register: ctl_output`

`TypeError: Value of unknown type: <class 'RuntimeError'>, List FAILED! no such job was found.
fatal: [zosendpoint]: FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to api.apps.z-stack-int.cp.fyre.ibm.com closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_zos_job_query_payload_8yzfa7vq/ansible_zos_job_query_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_job_query.py\", line 165, in run_module\r\n  File \"/tmp/ansible_zos_job_query_payload_8yzfa7vq/ansible_zos_job_query_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_job_query.py\", line 211, in query_jobs\r\nRuntimeError: List FAILED! no such job was found.\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/u/ibmuser/.ansible/tmp/ansible-tmp-1660311444.913656-9146-196003178089563/AnsiballZ_zos_job_query.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/u/ibmuser/.ansible/tmp/ansible-tmp-1660311444.913656-9146-196003178089563/AnsiballZ_zos_job_query.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/u/ibmuser/.ansible/tmp/ansible-tmp-1660311444.913656-9146-196003178089563/AnsiballZ_zos_job_query.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.ibm.ibm_zos_core.plugins.modules.zos_job_query', init_globals=dict(_module_fqn='ansible_collections.ibm.ibm_zos_core.plugins.modules.zos_job_query', _modlib_path=modlib_path),\r\n  File \"/usr/lpp/IBM/cyp/v3r9/pyz/lib/python3.9/runpy.py\", line 210, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lpp/IBM/cyp/v3r9/pyz/lib/python3.9/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lpp/IBM/cyp/v3r9/pyz/lib/python3.9/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_zos_job_query_payload_8yzfa7vq/ansible_zos_job_query_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_job_query.py\", line 261, in <module>\r\n  File \"/tmp/ansible_zos_job_query_payload_8yzfa7vq/ansible_zos_job_query_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_job_query.py\", line 257, in main\r\n  File \"/tmp/ansible_zos_job_query_payload_8yzfa7vq/ansible_zos_job_query_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_job_query.py\", line 168, in run_module\r\n  File \"/tmp/ansible_zos_job_query_payload_8yzfa7vq/ansible_zos_job_query_payload.zip/ansible/module_utils/basic.py\", line 1533, in fail_json\r\n  File \"/tmp/ansible_zos_job_query_payload_8yzfa7vq/ansible_zos_job_query_payload.zip/ansible/module_utils/basic.py\", line 1506, in _return_formatted\r\n  File \"/tmp/ansible_zos_job_query_payload_8yzfa7vq/ansible_zos_job_query_payload.zip/ansible/module_utils/common/parameters.py\", line 887, in remove_values\r\n  File \"/tmp/ansible_zos_job_query_payload_8yzfa7vq/ansible_zos_job_query_payload.zip/ansible/module_utils/common/parameters.py\", line 461, in _remove_values_conditions\r\nTypeError: Value of unknown type: <class 'RuntimeError'>, List FAILED! no such job was found.\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1`

**Comment by ddimatos** [comment]
@adn1107 
- Which version of the ibm_zos_core collection
- Which version of ZOAU
- Did you print the value for {{ DFS_IMS_SSID }} such that it was empty or it evaluated to something?
- What was the value for DFS_IMS_SSID we currently support this pattern
`job_id_pattern = re.compile("(JOB|TSU|STC)[0-9]{5}|(J|T|S)[0-9]{7}$")`
       - JOB<5 int>
       - TSU<5 int> 
       - STC<5 int> 
       - J<7 int> 
       - T<7 int> 
       - S<7 int>

**Comment by ddimatos** [comment]
Based on the line numbers it looks like you are using v1.3.1; I tried to recreate with 1.3.1 and 1.4.0-beta.1 and not able to, below is my playbook. There is a differnce in behavior between 1.3.1 and 1.4.0-beta.1 where the latter is more verbose. I do think we could do a better job and list the data set that is not being found in the response.

My playbook:
```
---
- hosts: zvm
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  vars:
    DFS_IMS_SSID: None
  environment: "{{ environment_vars }}"

  tasks:
    - name: Get job output job
      zos_job_output:
        job_name: "{{ DFS_IMS_SSID }}CTL"
      register: job_output_result

    - name: Result for job id job output
      debug:
        msg: "{{ job_output_result }}"
```

Version 1.3.1:
```
TASK [Result for job id job output] ********************************************************************************************************************************************************************************************
ok: [zvm] => {
    "msg": {
        "changed": false,
        "failed": false,
        "jobs": []
    }
}
```

Version 1.4.0-beta.1
```
TASK [Result for job id job output] ********************************************************************************************************************************************************************************************
ok: [zvm] => {
    "msg": {
        "changed": false,
        "failed": false,
        "jobs": [
            {
                "class": "",
                "content_type": "",
                "ddnames": [
                    {
                        "byte_count": "0",
                        "ddname": "notused",
                        "id": "",
                        "procstep": "",
                        "record_count": "0",
                        "stepname": null
                    }
                ],
                "job_id": "",
                "job_name": "",
                "owner": null,
                "ret_code": {
                    "code": null,
                    "msg": "JOB NOT FOUND",
                    "msg_code": "NOT FOUND",
                    "msg_txt": "The job could not be found"
                },
                "subsystem": null,
                "system": null
            }
        ]
    }
}

```

**Comment by ddimatos** [comment]
Thus far the only work I see is to update the response with the data set name as it would have been helpful to know it was not blank
