### ISSUE TITLE
[Feature] Update modules readability for option tmp_hlq

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#386]
During a code review in #341  it was commented that it might be helpful if the modules had used a different variable  names than the option used in the module to ease future development and readability. This was not addressed in the PR  and instead opened as a git issue because we did not want to disrupt pull request progress given this was not a bug and only enhances readability.

@richp405 and @fernandofloresg can decide if this needs to be done or it can be closed out. 

My review found the option `tmp_hlq` was the option added which later mapped to a var named `tmphlq` which is fine but later the code used a dictionary with the name `tmp_hlq` to pass to the better arg parser.  I did not think it was that confusing but can see it requiring a careful review. 

It would be these modules that would need updates:
zos_encode
zos_apf
zos_blockinfile
zos_lineinfile
zos_mount
zos_copy
zos_mvs_raw
zos_fetch

**Comment by fernandofloresg** [comment]
This should be covered, all uses of tmphlq are for string values and parameters, whereas all uses of tmp_hlq are for dict and module options. 
Use of tmphlq: 
https://github.com/ansible-collections/ibm_zos_core/search?q=tmphlq
 
Use of tmp_hlq:
https://github.com/ansible-collections/ibm_zos_core/search?q=tmp_hlq

**Comment by ddimatos** [comment]
@fernandofloresg - I agree, i wanted to record the review but am fine with out i was written.
