### ISSUE TITLE
[Bug] [zos_operator] Module documentaion examples are incorrect

### ISSUE THREAD

**Issue by adn1107** [ansible-collections/ibm_zos_core#390]
- name: Execute an operator command to show active jobs
  zos_operator:
    cmd: 'd u,all'

- name: Execute an operator command to show active jobs with verbose information
  zos_operator:
    cmd: 'd u,all'
    verbose: true

- name: Execute operator command to show jobs, waiting up to 5 seconds for response
  zos_operator:
    cmd: 'd u,all'
    wait_time_s: 5
    wait: false

- name: Execute operator command to show jobs, always waiting 7 seconds for response
  zos_operator:
    cmd: 'd u,all'
    wait_time_s: 7
    wait: true

the command should be 'd a,all' not 'd u,all'

**Comment by ddimatos** [comment]
Moving to Q4 - iter3 as a result of #376 taking longer than expected

**Comment by ddimatos** [comment]
Thank you @adn1107
