### ISSUE TITLE
[Bug] [zos_operator] Returns RC 0 in the Ansible result yet the content has a differnt RC value

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#398]
##### SUMMARY
In the latest `dev` branch the zos_operator module in the case that the module runs a command that fails, in my example its a long running command that exceeds the allocated time. It returned an RC=0 yet the content was an RC=0C RSN=00.

I have suspicion the RSN was truncated but that is not the issue I am reporting. 

Command is sanitized because its a development only command. Once the time reached 50 seconds it returned with an RC=0 and yet the content had an  RC=OC, RSN=00. Looking at other commands in Ansible, they all return what the managed node returns unless an invalid arg is passed which then returns a 256. 

- I think we have to decide on a RC and document because Ansible expects an integer and we can't convert an OC to a int. 
- The next thing we can do is consider adopting (interface change) the `ret_code` complex type we use in other zos_ansible commands which looks like:
```
       "ret_code": {
          "code": null,
          "msg_code": "0C",
          "msg_txt": "",
          "msg": "Error retrieving operator message RC=0C,RSN=00""
        },
```

Some added context around the ret_code block:
- msg
   - would would be the job error such as: "JCL ERROR" | "ABEND(S|U)xxxx" | "CONV ABEND" | "SEC ERROR" | "SYS FAIL"| CANCELED"| "CC xxxx"
- msg_code 
   - The string value of the job error reduced down to something more consumable such as "00" ("00" | "04" | "08" | "S0C4"
- msg_txt 
   - if we can deduce from the msg_code some advice as to what might have gone wrong
        - "The target is unreachable"
        - "Error code xxxx received, please check yyyy is installed and configured"
- code - if and only if we can convert msg_code into an integer value we return it otherwise we return None
    - Something like msg_code :"00" can be converted to type int: code : 00
    - Something like msg_code :"ABEND", msg_code :"ABEND(S1234)", msg_code :"CANCELED", can not convert thus return None

Below is the output of a long running command that has an RC=0C and RC=0 in the response. 
```
ok: [zvm] => {
    "result": {
        "changed": true,
        "cmd": "DISPLAY ...........................................",
        "content": [
            "EC33017A   2022244  20:41:25.00             ISF031I CONSOLE OMVS0000 ACTIVATED",
            "EC33017A   2022244  20:41:25.00            -DISPLAY ..................................................... ",
            "EC33017A   2022244  20:41:25.00             Error retrieving operator message RC=0C,RSN=00",
            "",
            ""
        ],
        "deprecations": [
            {
                "collection_name": "ibm.ibm_zos_core",
                "date": "2022-09-01",
                "msg": "Support for configuring wait has been deprecated.Configuring wait is now managed by setting 'wait_time_s'"
            }
        ],
        "elapsed": 51.53,
        "failed": false,
        "rc": 0,
        "wait_time_s": 50
    }
}
```

A good start would be to ensure that the task fails rather than succeeds.

##### ANSIBLE VERSION

```
Ansible version output:
```

##### STEPS TO REPRODUCE

```yaml
  tasks:
    - name: Execute operator command
      zos_operator:
        #cmd: 'd u,all'
        wait_time_s: 1
        cmd: 'DISPLAY A LONG RUNNING COMMAND'
        verbose: false
      register: result

    - name: Response
      debug:
        var: result
```

##### EXPECTED RESULTS
Proper Return codes or at least that the ansible task failed

##### ACTUAL RESULTS

See summary section above

**Comment by rexemin** [comment]
I was able to replicate using the `dev` branch at the [last commit of Sep 1](https://github.com/ansible-collections/ibm_zos_core/tree/2dd4072c8adffba3229add6b9d17667ad083fa2d). However, this issue was fixed by [the next commit on Sep 2](https://github.com/ansible-collections/ibm_zos_core/commit/72ffbca315899802d9dab88e0124ca795954db74), via merging of #391.
The bug originated from this part of the code:
```
for linetocheck in short_str:
    if "INVALID" in linetocheck:
        result["exception"] = "Invalid detected: " + linetocheck
        result["changed"] = False
        module.fail_json(msg=result["exception"], **result)
    elif "ERROR" in linetocheck:
        result["exception"] = "Error detected: " + linetocheck
        result["changed"] = False
        module.fail_json(msg=result["exception"], **result)
    elif "UNIDENTIFIABLE" in linetocheck:
        result["exception"] = "Unidentifiable detected: " + linetocheck
        result["changed"] = False
        module.fail_json(msg=result["exception"], **result)
```
Because the output returned by the operator command didn't fit exactly what was expected in the module (the command returned "Error" instead of "ERROR"), the module didn't exit with a failure. The updated code handles this case and does return a failure.
