### ISSUE TITLE
[Enabler][ 1 ] Execution Environments pipeline update that can support building and certifying EE for ibm_zos_core

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#421]
### Enabler description

This task covers only the work needed to update  the z/OS Ansible Core pipeline work to create EE's and certify them. Since it is undetermined what our overall RHACC strategy will be, its safe to assume we will minimally need and EE for `ibm_zos_core` and need to start looking into what changes need to be done to support this. 

When doing this work, please raise a discussion or present some options to the architects because it would be helpful we choose the best option meaning a dedicated new pipeline that can build any or all collections EEs as individual or as one EE or we write it such its a state that can be copied and pasted into other pipelines with minimal to little edits so they can also create EEs.

Relates to issue #474

**Comment by richp405** [comment]
Closing, since we had the meeting.  I have to update Jenkins.  Next ticket will be to test the new pipeline branch.
