### ISSUE TITLE
[Enhancement] [zos_blockinfile] Support files as variables in block content such that file content is inserted to src

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#422]
### Enhancement description

Enhance `zos_blockinfile` such that a user can specify a file in the block content where the file is a {{ variable }} , the result should be that the content inside the file be inserted into the `src` set in the `zos_blockfile` module. In other words, a file be represented as a var in the block content and the contents be inserted to the `src`.

Original JIRA issue comment that I created this issue from:
```
A user can use a variable with a sourced file as block argument and expect the file content to be inserted into the src document with the zos_blockinfile module specified behaviour.
```

Relates to issue #430 
### Ansible module

zos_blockinfile

**Comment by fernandofloresg** [comment]
Retested this and with latest ZOAU 1.2.1 which contains a fix to increase the limit of insertion using dmod (hence zos_blockinfile) and works fine(with the proper record length). Fix is not in our scope and depends on ZOAU version only.

We can close this issue and proceed with #430.

**Comment by ddimatos** [comment]
Thank you @fernandofloresg !!!
