### ISSUE TITLE
[Enhancement] [zos_copy]  Support Data Set member Aliases

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#423]
### Enhancement description

This is an enhancement because aliases were not intentionally supported.

# Enhancement

The `zos_copy` module does not copy any aliases, take for example the snippet below:
```
zos_copy:
 src: SYS2.MQMM001.SCSQSNLE(*)
 dest: SYS2.MQM.LPALIB.ANS
 remote_src: true
```

Where the data set  `SYS2.MQMM001.SCSQSNLE` when browsed has:
```
Name Prompt Alias-of Size
_________ CSQNL28E 00000A28
_________ CSQ3ECMX CSQNL28E 00000A28
```

In this case, only the member would be copied to the dest and not the alias.

## Source Problem
`zos_copy` uses ZOAU to list the members with source similar to `members = list(map(str.strip, datasets.list_members(src)))`  only no Aliases are returned which results in `zos_copy` not knowing about the alias and passing the listing `zos_copy` handler `copy_to_member` which ultimately invokes `datasets._copy(new_src, dest)` on a list does not include an alias.

# Notes
- The issue originally was in internal archive `C01E25VTZ3L/p1622058177044000`
- There are a number of ways to handle this, requesting ZOAU `mls` and `dls` support reading aliases
- An alias is like a *nix symlink, we would not want to copy an alias such that it results in a physical copy, that would defeat the purpose. We would want to ensure/check if something is an alias and make another alias, this should either be done by zos_copy or zoau methods (ensure we don't make another physical copy)
- Some ideas if we want to do this solely in zos_copy is to remove the `datasets.list_members(src) `call and insert our own commands or REXX that would check if a member is an Alias before doing a copy, basically separating members from aliases and then for the Aliases we could run a command like so in TSO to create the Alias for the `zos_copy` function `RENAME 'IMSTESTL.DIMATO.JCLCOPY(DATA)' 'IMSTESTL.DIMATO.JCLCOPY(DATAX)' ALIAS` and to list the members and Aliases `LISTDS 'IMSTESTL.DIMATO.JCLCOPY' MEMBERS`

<img width="1946" alt="image" src="https://user-images.githubusercontent.com/25803172/191558278-86e4c203-f12d-46fb-8390-6b64eb0f8986.png">

# Comments
## From @adn1107 
IEBCOPY COPYGROUP option [can be used to copy aliases](https://www.ibm.com/docs/en/zos/2.1.0?topic=program-copying-objects-copygrp-copygroup-statements) 

It is recommended that you use the COPYGRP or COPYGROUP statement to copy PDS load modules or PDSE program objects and their aliases from or to a PDSE data set. Program objects can have aliases that are longer than eight characters. Using the COPYGRP or COPYGROUP statement will ensure that these longer aliases are copied along with their member.

Use the COPYGRP or COPYGROUP statement to begin a group copy, unload, or load. A group consists of a member and all of its aliases. COPYGRP or COPYGROUP treats the group as a single entity.

COPYGRP can be used to copy a data set when either the input data set or the output data set, or both, are PDSE:
PDSE to PDSE
PDSE to PDS
PDS to PDSE
COPYGROUP can be used to copy a data set when either the input data set or the output data set, or both, are PDS or PDSE:
PDSE to PDSE
PDSE to PDS
PDS to PDSE
PDS to PDS
For unloading groups:
Using COPYGRP: PDSE to PS
Using COPYGROUP: PDSE to PS, or PDS to PS
For loading groups:
Using COPYGRP: PS to PDSE
Using COPYGROUP: PS to PDSE, or PS to PDS
If neither data set is a PDSE, the request is treated the as a COPY operation subject to the syntax requirements of COPYGRP.

When using the COPYGRP or COPYGROUP statement:

    All aliases in a group will be copied with the member or neither the aliases or the member in a group will be copied.
    There can be only one INDD per copy operation.
    You can use the SELECT statement to selectively copy members. Either the member name or an alias can be specified to copy the member and all of its aliases.
    Do not indicate replace (R) on the SELECT statement.
    The EXCLUDE statement is not supported.

### Ansible module

zos_copy

**Comment by ddimatos** [comment]
Interestingly is that issue #621 claims that this worked in IBM z/OS core 1.3.x and stopped working in 1.4.x. No further investigation has been done on issue #621 and likely will be closed as `zos_copy` did not intentionally support `aliases`. 
Requirements were put on ZOAU that recently became available and more specifically zos_copy must implement this and note it in docs and add test cases. 

I could be that it worked in 1.3.x because USS `cp` might have been providing some default our courtesy behaviors.

**Comment by ddimatos** [comment]
Relies on ZOAU 9421

**Comment by storfibm** [comment]
Completed by ZOAU in 1.2.4

**Comment by ketankelkar** [comment]
https://github.com/ansible-collections/ibm_zos_core/pull/804#issuecomment-1665754009

**Comment by ketankelkar** [comment]
Regarding the link to the comment above, there is now plenty of alias testing
