### ISSUE TITLE
[Enabler] [pipeline][Research] Consider adding code coverage analysis to our pipelines

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#424]
### Task description

See link [here](https://docs.ansible.com/ansible/2.3/dev_guide/testing_units.html#code-coverage) for coverage tooling

Consider and evaluate how code coverage would work if we added it to our pipeline. `ansilbe-test --coverage` offers this function which appears to call [Coverage.py](https://coverage.readthedocs.io/en/coverage-5.2). 
I am uncertain how this would work when the modules run off platform but worth investigating.

The results seem to be written out to a file, what could we do with the results besides a manual inspection? Would we want to parse/grep the contents and expect certain coverage and raise a flag when below X% ?

### Ansible module

zos_apf, zos_backup_restore, zos_blockinfile, zos_copy, zos_data_set, zos_encode, zos_fetch, zos_find, zos_gather_facts, zos_job_output, zos_job_query, zos_job_submit, zos_lineinfile, zos_mount, zos_mvs_raw, zos_operator, zos_operator_action_query, zos_ping, zos_tso_command

**Comment by richp405** [comment]
Got the prototype working in the pipeline



![Image](https://github.com/ansible-collections/ibm_zos_core/assets/39140439/4cea102e-08c6-44b4-8802-ae7cc10b2569)

**Comment by richp405** [comment]
Code solution, now in Jenkinsfile5g:

 if (CODE_COVERAGE.toBoolean()) {
                            inout = sh(script: 'pip3 install coverage==6.5.0 || true', returnStdout: true)
                        }

                        if (CODE_COVERAGE.toBoolean()) {
                            scr_cmd = "ansible-test sanity --coverage 2>&1 || true"
                        }
                        else {
                            scr_cmd = "ansible-test sanity 2>&1 || true"
                        }

                        out = sh(script: scr_cmd, returnStdout: true)

                        if (VERBOSITY.toBoolean()) {
                            echo '\n----------------------------- Sanity output ------------------------------'
                            echo out
                            echo '\n--------------------------------------------------------------------------'
                        }
                        /* Need to generate coverage to different var so as not to trip up test
                        */
                        if (CODE_COVERAGE.toBoolean()) {
                            scr_cmd = 'ansible-test coverage report 2>&1 || true'
                            alt_out = sh(script: scr_cmd, returnStdout: true)
                            echo '\n----------------------------- Coverage output ------------------------------'
                            echo alt_out
                            echo '\n--------------------------------------------------------------------------'
                        }

**Comment by richp405** [comment]
This is completed, but it will be 1st week of 6th iteration before i get it propagated to all the pipelines.
