### ISSUE TITLE
[Module][3][Volume] [ Playbook] Ensure a playbook is written and contributed to the playbook repository

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#436]
### Module description

The volume module is a cross team effort (inner-source) collaboration, ensure that the development team leading the volume module with the assistance of a dedicated developer from ibm_zos_core support them and assist in creating a playbook for the playbook repository demonstrating the volume module. 

This playbook could  be placed under the `basics` section of the repository, no need for a complex use case as it is a foundational step to first create a volume before a data set.

**Comment by ketankelkar** [comment]
I have a simple playbook which takes a volume offline, re-initializes it, brings it back online, creates a ZFS data set and mounts ZOAU to it and then calls and prints the results of zoaversion. 

In addition to polishing it up and adding comments/descriptions, I think validating that this is a valuable use case remains.

**Comment by ketankelkar** [comment]
PR - https://github.com/IBM/z_ansible_collections_samples/pull/182
