### ISSUE TITLE
[Enhancement] [zos_data_set] add support for fixed length records (F)

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#439]
### Enhancement description

It was brought to our intention that supporting F in the `zos_data_set` is desired. 

Currently there is no function in ZOAU, thus ticket `8832` has been opened. 

You can review the documentation for Fixed length records here under [topic RECFM(A,B,D,F,M,S,T,U,V)](https://www.ibm.com/docs/en/zos/2.5.0?topic=parameters-optional) and [here](https://www.ibm.com/docs/en/zos/2.1.0?topic=options-record-format-recfm).

Internal discussion occurred in archive `CSLEJ8VGV/p1635777448025100`

This is associated to ZOAU tracker `8832`

Note:
- A test case will be needed evaluate the usage of RECFM `F`
- Module doc will need updating

**Comment by ddimatos** [comment]
Support for F , fixed data lengths comes in ZOAU v1.2.3, we can start this permitting planning has capacity.

**Comment by richp405** [comment]
The change appears straightforward... my only question is whether WE should put in a version check (i.e. error if zoau < 1.2.3 and request is 'F') or is that already available in zoau?  I'll set up a test to see how 1.2.1/1.2.2 handle it.

**Comment by richp405** [comment]
zoau latest (1.2.3.2), documents it supports 'F' format.  will test the pass-through of the value today.

**Comment by richp405** [comment]
Just got it to PR, and included the changelog fragment.
