### ISSUE TITLE
[Enabler] [CI/CD] Design a process into our pipeline that allows for a `latest` version of ZOAU to be run

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#466]
### Enabler description

This is work item is to update our pipeline (multipath) with the ability to run the latest builds of ZOAU without any manual efforts to do so. In other words, our pipeline should continuously watch or via a hook/trigger be instructed a new zoau build is available, in that case the process should get the build, put it into a share (super share) that is can be later run by our pipelne either manually or as a nightly process. 

Some ideas are that we put the ZOAU build into a RW mount (i can be RO) only that more work has to be done to ensure its RO. Multipath is already capable of dynamically seeing versions in the mounts. 

Update:
Some additional thoughts, we create a new pipeline or update ours (think its better to have a separate new one) that will monitor artifactory with the [UrlTrigger](https://plugins.jenkins.io/urltrigger/) or equivalent plugin, where now we run a few scripts that scp/sftp (BIN) the pax down to the jenkins node  and then copy it over to our RW mount point called /latest, from there we can decided what to do , email, slack post and/or trigger regression.

**Comment by richp405** [comment]
Share is created in the IMSCN2 volume within RHACC2.zoau.latest.zfs.  Will loop in anthony once it survives the weekend IPL.
