### ISSUE TITLE
[Bug] [zos_copy] Omitting a traling '/' on a source directory does not copy the directory itself

### ISSUE THREAD

**Issue by rexemin** [ansible-collections/ibm_zos_core#496]
### Bug description

When copying a source directory to another directory, if omitting a trailing '/' on its path, the directory does not get copied into `dest`, just the contents of it. The built-in `copy` module behaves differently depending on how the `src` path is specified (documentation [here](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html#parameter-src)):

> If path is a directory, it is copied recursively. In this case, if path ends with “/”, only inside contents of that directory are copied to destination. Otherwise, if it does not end with “/”, the directory itself with all contents is copied. This behavior is similar to the rsync command line tool.

This issue is to align the behavior present in `zos_copy` with what the built-in module does.

### Ansible version

```shell
ansible [core 2.11.12] 
  config file = /Users/iamorenosoto/Documents/IBM/Development/nazare/9389/ansible.cfg
  configured module search path = ['/Users/iamorenosoto/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/iamorenosoto/.pyenv/versions/3.8.12/envs/nazare-9389/lib/python3.8/site-packages/ansible
  ansible collection location = /Users/iamorenosoto/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/iamorenosoto/.pyenv/versions/nazare-9389/bin/ansible
  python version = 3.8.12 (default, Jan 17 2022, 16:02:56) [Clang 13.0.0 (clang-1300.0.27.3)]
  jinja version = 3.1.2
  libyaml = True
```

### IBM z/OS Ansible core Version

v1.3.6

### IBM ZOAU version

v1.2.0

### z/OS version

2.3

### Ansible module

zos_copy

**Comment by ddimatos** [comment]
Good we leave this work item in Validation mode so we are sure to include it in 1.4.0-beta.2, otherwise this work item was completed (and very well so :) )
