### ISSUE TITLE
[Enhancement][zos_tso_command] Override the maximum return code for tso commands?

### ISSUE THREAD

**Issue by billpereira** [ansible-collections/ibm_zos_core#565]
### Enhancement or featture description

Sometimes the RC 4 may be acceptable, for example when we are issuing a list RACF command to list a certificate and it's not present. It will give back the answer saying certificate is not present, but that may not be an issue as i may use that to handle some situations on the playbook.
Can we override the rc 0 through a max_rc parm like zos_job_submit?

            if cmd.get("rc") != 0:
                module.fail_json(
                    msg='The TSO command "'
                    + cmd.get("command", "")
                    + '" execution failed.',
                    **result
                )

### Ansible module
zos_tso_command

**Comment by fernandofloresg** [comment]
Interesting. 

@billpereira Do you have other samples were return code being other than 0 is acceptable? I think we rather have it as an option so when that option is on instead of failing having a level of tolerance for some return codes.

**Comment by billpereira** [comment]
Well i have not noticed yet.. probably other commands to racf should act like this.... i found that cause i was working in one situation and i saw that i was getting a good response but as the RC was not 0 it was stopping the execution, i managed to implement a block to don't stop it, but would be better to have this option to add instead of creating a block just to handle the CC

**Comment by ddimatos** [comment]
This is a reasonable request, it very similar to the option we have for module `zos_job_submit` option `max_rc` [here](https://github.com/ansible-collections/ibm_zos_core/blob/release-v1.5.0-beta.1/docs/source/modules/zos_job_submit.rst) , note this is from our 1.5.0-beta.1 soon to release doc, function has been around for a while but the docs were updated in 1.5.

```
max_rc

    Specifies the maximum return code allowed for any job step for the submitted job.
    required: False
    type: int

```

**Comment by richp405** [comment]
I've put up basic code for this, and changelog.  My only afterthought for now is that this all assumes decimal integers, and there are some higher RC's which are, I believe, hex.  I'll go back to the books to see if this matters before committing to a PR.

Also need to add a test case.

**Comment by richp405** [comment]
Test case added last week (March 1st/2nd), but had build issues going into the weekend.

**Comment by richp405** [comment]
Forgot to include reference to PR: ansible-collections/ibm_zos_core/pull/666
