### ISSUE TITLE
[Bug] [zos_find] zos_find return the filtered_data_sets list once BGYSC1103E (dataset not found) returned by dls.

### ISSUE THREAD

**Issue by snowind** [ansible-collections/ibm_zos_core#574]
### Bug description

zos_find: vall versions

Reproduce the problems with playbooks:

On z/OS, PDS "IMSTEST.USER.A" contains 2 members, "IMSTEST.USER.B" also cantains 3 members.  "IMSTEST.DS.NOTEXIST " is not existed. 

Test case #1: 
- name: Find all members in a given list of PDS patterns
  zos_find:
    patterns: '.*'
    pds_patterns:
      - IMSTEST.DS.NOTEXIST 
      - IMSTEST.USER.A
      - IMSTEST.USER.B
   register: pds_members

Test case #2: 
- name: Find all members in a given list of PDS patterns
  zos_find:
    patterns: '.*'
    pds_patterns:
      - IMSTEST.USER.A
      - IMSTEST.DS.NOTEXIST 
      - IMSTEST.USER.B
   register: pds_members

Tese case #1 failed and matched 0 returned. 
Test case #2 return the members in IMSTEST.USER.A only, no members in the "IMSTEST.USER.B" returns. 

In the zos_find logic, once the "BGYSC1103E" message is returned from dls command, the loop is ended and  the filtered_data_sets is returned, that explains why no remaining PDS in the pds_patterns list  is checked, once there is one PDS is not exist.

filtered_data_sets = dict(ps=set(), pds=dict(), searched=0)
    patterns = pds_paths or patterns
    for pattern in patterns:
        rc, out, err = _dls_wrapper(pattern, list_details=True)
        if rc != 0:
            if "BGYSC1103E" in err:
                return filtered_data_sets

### Ansible version

```shell
ansible 2.10.17
  config file = None
  configured module search path = ['/Users/ZhouHui/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ZhouHui/opt/anaconda3/lib/python3.8/site-packages/ansible
  executable location = /Users/ZhouHui/opt/anaconda3/bin/ansible
  python version = 3.8.3 (default, Jul  2 2020, 11:26:31) [Clang 10.0.0 ]
```

### IBM z/OS Ansible core Version

v1.3.1

### IBM ZOAU version

v1.1.1

### z/OS version

z/OS 2.4 

### Ansible module

zos_find

**Comment by richp405** [comment]
I've got a playbook and validated the observed bug.  Review complete.
I've made a code change that addresses the issue.  
Moving on to determining if I can make/update a unit test for this.

**Comment by richp405** [comment]
unit test done, through the build pipeline.
Pull Request opened: https://github.com/ansible-collections/ibm_zos_core/pull/668
