### ISSUE TITLE
Use environment var or module option to customize temp_path when staging payload files during invoking zos_copy module.

### ISSUE THREAD

**Issue by snowind** [ansible-collections/ibm_zos_core#580]
### Enhancement or featture description

My customer case is that the bank customer want to use Ansible Tower to streamline the CICS application change process across their change server (AIX) and the z/OS. There are three nodes here, the Ansible control node (Linux), the application change server (AIX) and the target z/OS managed node.  The ansible playbooks will retrieve (sftp) one file from AIX server (for example name it to: a.back1) , and invoke zos_copy module to copy the local temp file (a.back1) to one SEQ dataset on the remote managed z/OS node. During the dataset copying process, one temporary staging file is created under z/OS USS /tmp directory of the z/OS host LPAR (payload file). If the copying file is too big and size exceeds the available space of /tmp directory, the zos_copy module failed.

To bypass the problem, one option is to expand the /tmp filesystem , which means z/OS system change (/tmp filesystem replacement). Another option is to create one new filesystem like as OMVS.ANSIBLE.TMP.ZFS and mount it to /tmp/ansible (for example), and use one environment var to let the zos_copy action plugin to put the temporary payload file under /tmp/ansible (new temp folder), before copying it to the final target z/OS SEQ dataset.

The TMPDIR, TMP, TEMP and remote_temp environment vars only controls how the temporary python files are copying into, it is not the case where the payload files are staging in. 

Our customer are not willing to expand the existing TMP filesystem and would like to allocate a new one ZFS, which could have less impact to other subsystem potential users of /tmp directory .

Find that in the [ibm_zos_core](https://github.com/ansible-collections/ibm_zos_core/tree/v1.3.1)/[plugins](https://github.com/ansible-collections/ibm_zos_core/tree/v1.3.1/plugins)/[action](https://github.com/ansible-collections/ibm_zos_core/tree/v1.3.1/plugins/action)/zos_copy.py ,
    def _copy_to_remote(self, src, port, is_dir=False, ignore_stderr=False):
        """Copy a file or directory to the remote z/OS system """
        ansible_user = self._play_context.remote_user
        ansible_host = self._play_context.remote_addr
        temp_path = "/{0}/{1}".format(gettempprefix(), _create_temp_path_name())
        cmd = ["sftp", "-oPort={0}".format(port), ansible_user + "@" + ansible_host]
        stdin = "put -r {0} {1}".format(src.replace("#", "\\#"), temp_path)

the tempfile.gettempprefix() always returns “tmp”, no matter the envioronment var (TMPDIR, TEMP, TMP) in the z/OS host /etc/profile. That may explain why the zos_copy payload file is always created in this file: /tmp/ansible-zos-copy-payload-Dyymmdd-Thhmmss  . The action plugin does decide the tmp path which is what is returned by gettempprefix() , changes to override this have implications for the module in how it will find the file, this would need to be a coordinated change where both the action plugin and module can agree either through a agreed upon way , eg a env var or a new module option.

If the temp path can favor some environment var settings, it would bring more flexibility on z/OS side.

### Ansible module

zos_copy

**Comment by ddimatos** [comment]
@snowind - is this a duplicate to #573

**Comment by ddimatos** [comment]
Appears to be a duplicate to #573, will note it in #573 for reference and close this issue
