### ISSUE TITLE
[Bug] [zos_copy] Return error message when concurrent copy fails

### ISSUE THREAD

**Issue by rexemin** [ansible-collections/ibm_zos_core#586]
### Bug description

When `zos_copy` is trying to copy a source dataset into a destination dataset that is already in use by another program (with `DISP=SHR`), the module will report a successful task but nothing will actually be copied into the destination. This bug is related to #357, and so while the implementation of supporting other disposition modes is being explored, the module should at least return an error message when this happens.

This is also related to #559, more information about the issue is found there.

### Ansible version

```shell
ansible [core 2.13.5]
  config file = /Users/bpanyar/github/IBMZSoftware/ims-containerization/ansible.cfg
  configured module search path = ['/Users/bpanyar/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/bpanyar/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.6 (main, Aug 11 2022, 13:49:25) [Clang 13.1.6 (clang-1316.0.21.2.5)]
  jinja version = 3.1.2
  libyaml = True
```

### IBM z/OS Ansible core Version

v1.4.0-beta.2

### IBM ZOAU version

v1.1.1

### Ansible module

zos_copy

**Comment by ddimatos** [comment]
After talking to @rexemin - using `mls` from zoau won't work for all cases, there is the case that the member being copied is not a new member therefore mls will return the same before and after. 

We could check if the DS is in use with a `D GRS,RES=(*,IMSTESTL.COMNUC)` command.

With a lock on the data set:
```
00- 21.05.08           D GRS,RES=(*,IMSTESTL.COMNUC)                         
    21.05.08           ISG343I 21.05.08 GRS STATUS 830                      C
    S=SYSTEM  SYSDSN   IMSTESTL.COMNUC                                       
    SYSNAME        JOBNAME         ASID     TCBADDR   EXC/SHR    STATUS      
    EC33012A  USRT001            0057       006FEE88   SHARE      OWN      
```

Without a lock:
```
  00- 21.07.01           D GRS,RES=(*,IMSTESTL.COMNUC)                         
      21.07.01           ISG343I 21.07.01 GRS STATUS 836                      C
      NO REQUESTORS FOR RESOURCE  *        IMSTESTL.COMNUC
```

Assuming this is reasonable way to check for the lock on a data set we could use this command before performing a copy and error if we find that EXC/SHR = SHARE

**Comment by ddimatos** [comment]
Although this can be used to automate but you can help it to develop, if i split my x3270 into 2 , in the top I have entered into the PDSE with an `E` for edit, then in the bottom half of the x3270 session i find the data set, put `qds` next to it.
<img width="1526" alt="image" src="https://user-images.githubusercontent.com/25803172/230446671-a1b04dad-af71-474d-9f95-eb88f33e4497.png">
Now disp=shr is user `usrt001`.

<img width="1548" alt="image" src="https://user-images.githubusercontent.com/25803172/230446778-4fe84989-c166-4b59-afe4-7fd2e8487503.png">
