### ISSUE TITLE
[Release][1.6.0-beta.1] Release Tasks

### ISSUE THREAD

**Issue by fernandofloresg** [ansible-collections/ibm_zos_core#606]
## Release Requirements Checklist
This checklist is nearly a chronological ordering of the release tasks to complete for any given version of IBM Ansible z/OS core collection. This template is for both Automation Hub and Galaxy, you may not be releasing to Hub, for those you may skip the items. You should be checking off each task as it completes.

## General workflow
This a subsequent release (not a patch) thus the `Pull Request Tasks` (below) will be merged into `main` then back into dev to allow for the meta data updates to propagate as well as the release tag. 

Its best to use a staging branch, eg `staging-v1.6.0-beta.1` with a pull request pointing at `main`. Thus it should look like:
`staging-v1.6.0-beta.1` ---> `main`--> `dev`.

### Pull Request Tasks for branch staging-v1.6.0-beta.1
- [x] Update `galaxy.yml`
- [x] Update `meta/runtime.yml`
- [x] Update `meta/ibm_zos_core_meta.yml`
- [x] Update `README.md`
- [x] Review copyrights are updated as needed, e.g. current year if changes are made
- [x] Generate module docs (restructured text - RST) and check it into the release branch
- [x] Add a change log summary fragment for this version
- [x] Generate CHANGELOG.rst
- [x] Create release notes
- [x] Review all module source imports; ensure sure no new imports are subject to license discrepancies 

### Technical Writer Tasks
- [x] Ensure all technical writer Git issues are resolved for this release

### Quality assurance
- [x] Open a pull request for `staging-v1.6.0-beta.1` against `main`
- [x] Full pipeline regression at 100% success
     - [x] Certify on IBM Enterprise Python versions 3.10 or 3.11 (with the latest ptf for env var PYTHONSTDINENCODING)
     - [x] Certify on IBM Enterprise Python and new environment var
     - [x] Certify on ZOAU 1.2.2
     - [x] Certify on `ansible-core v2.14.x
     - [x] Ensure `RUN_ALL_TESTS` is selected
- [x] Run the galaxy importer (currently a manual step as its not part of the pipeline yet)
     - [x] `python -m galaxy_importer.main ibm-ibm_zos_core-1.5.0.tar.gz`. 
     - [x] Check output log for any errors/issues. Look for the following:
     - ```Collection loading complete```
     - ```Importer processing completed successfully```

### Certification Tasks
- [x] Build the image from `staging-v1.6.0-beta.1`, upack it up, inspect the contents
- [x] Test collection quality with an upload to the IBM HCF development Galaxy Server by uploading the build from branch `staging-v1.6.0-beta.1`.
- [x] Complete the collection release task pull requests and merge the PR (`staging-v1.6.0-beta.1`)into the `main` branch
- [x] Test collection quality again with a new build from `main` and now upload to the Ansible development Galaxy Server

### Scans
- [x] Run a Mend scan and check the results into the designated repository
- [x] Run a Bandit scan and check the results into the designated repository

### Release tasks (**In this order**)
- [x] Upload to [Galaxy](https://galaxy.ansible.com/ibm/ibm_zos_core)
- [x] Git tag: Merge to main and tag else if main and release have diverged, tag the release branch, see git [workflow](https://github.com/ddimatos/git-release-workflow/blob/master/gitflow.md#create-and-deploy-a-release).
- [x] Open a Git issue in [z_ansible_collections_doc](https://github.com/IBM/z_ansible_collections_doc/issues) to have [Red Hat® Ansible Certified Content for IBM Z docs](https://ibm.github.io/z_ansible_collections_doc/index.html) generated

### Log collection
- [x] Copy any additional playbook or manual tests performed into the release folder
- [x] Copy the pipeline log from Jenkins into the release folder
- [x] Copy the Galaxy import log in the release folder
- [x] ~~Copy the Automation Hub import log into the release folder~~
- [x] Copy the git log (`git log --pretty=oneline`) into the release folder

**Comment by ddimatos** [comment]
From the `dev` branch I went ahead and created `release-1.6.0-beta.1` which is to be used for the tag and where all our final code ends up, I also create a `release-tasks-1.6.0-beta.1` branch for this current issue to have a place to put changes. 


```
ddimatos:[ ~/git/github/ibm_zos_core ]git checkout -b release-1.6.0-beta.1
Switched to a new branch 'release-1.6.0-beta.1'
ddimatos:[ ~/git/github/ibm_zos_core ]git push -u origin release-1.6.0-beta.1
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
remote:
remote: Create a pull request for 'release-1.6.0-beta.1' on GitHub by visiting:
remote:      https://github.com/ansible-collections/ibm_zos_core/pull/new/release-1.6.0-beta.1
remote:
To github.com:ansible-collections/ibm_zos_core.git
 * [new branch]        release-1.6.0-beta.1 -> release-1.6.0-beta.1
branch 'release-1.6.0-beta.1' set up to track 'origin/release-1.6.0-beta.1'.


ddimatos:[ ~/git/github/ibm_zos_core ]git checkout -b release-tasks-1.6.0-beta.1
Switched to a new branch 'release-tasks-1.6.0-beta.1'
ddimatos:[ ~/git/github/ibm_zos_core ]git push origin -u release-tasks-1.6.0-beta.1
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
remote:
remote: Create a pull request for 'release-tasks-1.6.0-beta.1' on GitHub by visiting:
remote:      https://github.com/ansible-collections/ibm_zos_core/pull/new/release-tasks-1.6.0-beta.1
remote:
To github.com:ansible-collections/ibm_zos_core.git
 * [new branch]        release-tasks-1.6.0-beta.1 -> release-tasks-1.6.0-beta.1
branch 'release-tasks-1.6.0-beta.1' set up to track 'origin/release-tasks-1.6.0-beta.1'.
```
