### ISSUE TITLE
[Bug] zos_copy at 1.4.0 or above fails if src dataset has ALIAS. 1.3.6 works fine. 

### ISSUE THREAD

**Issue by adn1107** [ansible-collections/ibm_zos_core#621]
### Bug description

TASK [ims_dataset : Copy System Datasets] **************************************
Monday 23 January 2023  14:46:08 -0800 (0:00:40.033)       0:05:01.496 ******** 
failed: [wazi] (item={'src': 'DFSF10.SDFSRESL', 'dest': 'IMSTEST.IMWZ.SDFSRESL'}) => {"ansible_loop_var": "item", "changed": false, "item": {"dest": "IMSTEST.IMWZ.SDFSRESL", "src": "DFSF10.SDFSRESL"}, "msg": "Unable to copy data set member DFSF10.SDFSRESL to data set member IMSTEST.IMWZ.SDFSRESL(ALIAS(DBFDBAC1)", "rc": 1, "stderr": "BGYSC1205E LISTCAT processing failed with pattern 66342.\nBGYSC1205E LISTCAT processing failed with pattern 50397965.\n", "stderr_lines": null, "stdout": "cp: FSUM6258 cannot open file \"//'DFSF10.SDFSRESL(ALIAS(DBFDBAC1)'\": EDC5047I An invalid file name was specified as a function parameter.\n", "stdout_lines": null}

### Ansible version

```shell
ansible --version
ansible [core 2.13.5]
  config file = None
  configured module search path = ['/Users/adn/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/adn/workspaces/nazare/venv/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/adn/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/adn/workspaces/nazare/venv/bin/ansible
  python version = 3.9.6 (default, Sep 26 2022, 11:37:49) [Clang 14.0.0 (clang-1400.0.29.202)]
  jinja version = 3.1.2
  libyaml = True
```

### IBM z/OS Ansible core Version

v1.4.0

### IBM ZOAU version

v1.2.2

### Ansible module

zos_copy

**Comment by ddimatos** [comment]
Hi @adn1107 - are you looping over a PDS or PDSE and assuming one of the members is an ALIAS, is that how you encountered this? 

Anything more you might have like the playbook or verbose output will help expedite this.

**Comment by ddimatos** [comment]
@adn1107 thank you for reporting this issue, please see issue #423 as to why this issue is being cancelled and closed. This is a good data point for us and we can use it in #423
