### ISSUE TITLE
[Bug] zos-job-query failed after upgrading to ibm_zos_core 1.5.0-beta.1

### ISSUE THREAD

**Issue by hyzhang6639** [ansible-collections/ibm_zos_core#653]
### Bug description

The below code can work properly in ibm_zos_core 1.4.0
- name: Query the status for {{ job_name }} on {{ system_name }}
   zos_job_query:
     job_name: "{{ job_name }}"
   register: result

But it failed against the below error after upgrading to 1.5.0-beta.1. The details is in the attachment.

"module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_zos_job_query_payload_f2woln5l/ansible_zos_job_query_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_job_query.py\", line 213, in run_module\r\n  File \"/tmp/ansible_zos_job_query_payload_f2woln5l/ansible_zos_job_query_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_job_query.py\", line 270, in parsing_jobs\r\nTypeError: argument of type 'NoneType' is not iterable\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/tmp/ansible-tmp-1677205940.4144113-338-61083714581192/AnsiballZ_zos_job_query.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/tmp/ansible-tmp-1677205940.4144113-338-61083714581192/AnsiballZ_zos_job_query.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/tmp/ansible-tmp-1677205940.4144113-338-61083714581192/AnsiballZ_zos_job_query.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.ibm.ibm_zos_core.plugins.modules.zos_job_query', init_globals=dict(_module_fqn='ansible_collections.ibm.ibm_zos_core.plugins.modules.zos_job_query', _modlib_path=modlib_path),\r\n  File \"/usr/lpp/IBM/cyp/v3r8/pyz/lib/python3.8/runpy.py\", line 207, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lpp/IBM/cyp/v3r8/pyz/lib/python3.8/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lpp/IBM/cyp/v3r8/pyz/lib/python3.8/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_zos_job_query_payload_f2woln5l/ansible_zos_job_query_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_job_query.py\", line 312, in <module>\r\n  File \"/tmp/ansible_zos_job_query_payload_f2woln5l/ansible_zos_job_query_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_job_query.py\", line 308, in main\r\n  File \"/tmp/ansible_zos_job_query_payload_f2woln5l/ansible_zos_job_query_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_job_query.py\", line 215, in run_module\r\n  File \"/tmp/ansible_zos_job_query_payload_f2woln5l/ansible_zos_job_query_payload.zip/ansible/module_utils/basic.py\", line 1533, in fail_json\r\n  File \"/tmp/ansible_zos_job_query_payload_f2woln5l/ansible_zos_job_query_payload.zip/ansible/module_utils/basic.py\", line 1506, in _return_formatted\r\n  File \"/tmp/ansible_zos_job_query_payload_f2woln5l/ansible_zos_job_query_payload.zip/ansible/module_utils/common/parameters.py\", line 928, in remove_values\r\n  File \"/tmp/ansible_zos_job_query_payload_f2woln5l/ansible_zos_job_query_payload.zip/ansible/module_utils/common/parameters.py\", line 471, in _remove_values_conditions\r\nTypeError: Value of unknown type: <class 'TypeError'>, argument of type 'NoneType' is not iterable\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1

### Playbook verbosity output

[job_query.txt](https://github.com/ansible-collections/ibm_zos_core/files/10820239/job_query.txt)

### Ansible version

```shell
ansible [core 2.14.2]
  config file = /root/z_ansible/tvt4124/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, May  8 2021, 07:45:39) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] (/usr/local/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### IBM z/OS Ansible core Version

v1.5.0-beta.1

### IBM ZOAU version

v1.1.1

### Ansible module

zos_job_query

**Comment by ddimatos** [comment]
@hyzhang6639 - thank you for opening an issue.

Please update your dependencies as they are not supported for `ibm_zos_core` 1.5.0-beta.1. You must have ZOAU 1.2.2  and IBM Enterprise Python 3.9 minimally. 

You can find that [doc](https://ibm.github.io/z_ansible_collections_doc/ibm_zos_core/docs/source/release_notes.html#reference) or review:

- Supported by [z/OS V2R3](https://www.ibm.com/support/knowledgecenter/SSLTBW_2.3.0/com.ibm.zos.v2r3/en/homepage.html) or later
- Supported by the [z/OS® shell](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.4.0/com.ibm.zos.v2r4.bpxa400/part1.htm)
- Supported by [IBM Open Enterprise SDK for Python](https://www.ibm.com/products/open-enterprise-python-zos) [3.9](https://www.ibm.com/docs/en/python-zos/3.9) - [3.11](https://www.ibm.com/docs/en/python-zos/3.11)
- Supported by IBM [Z Open Automation Utilities 1.2.x](https://www.ibm.com/docs/en/zoau/1.2.x)

IBM Enterprise Pytnon 3.8 went out of service as well. 

This test is one of our regular regression tests and has passed, I have also run it with 1.5.0-beta.1 and am sharing my playbook and results.

Plabyook:
```
---
- hosts: zvm
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"

  tasks:
    - name: Query submitted job name
      zos_job_query:
        job_name: HELLOPGM
      register: result
      #ignore_errors: yes

    - name: Response
      debug:
        msg: "{{ result }}"

    - name: Query submitted job id
      zos_job_query:
        job_id: JOB00503
      register: result
      #ignore_errors: yes

    - name: Response
      debug:
        msg: "{{ result }}"
```

Results:
```
ansible-doc) ddimatos:[ ~/git/github/playbooks ]ansible-playbook -i inventory zos-job-query.yaml

PLAY [zvm] ***********************************************************************************************************************************************************************************************************************************************************

TASK [Query submitted job name] **************************************************************************************************************************************************************************************************************************************
ok: [zvm]

TASK [Response] ******************************************************************************************************************************************************************************************************************************************************
ok: [zvm] => {
    "msg": {
        "changed": false,
        "failed": false,
        "jobs": [
            {
                "job_id": "JOB00503",
                "job_name": "HELLOPGM",
                "owner": "OMVSADM",
                "ret_code": {
                    "code": 0,
                    "msg": "CC 0000"
                },
                "subsystem": "STL1",
                "system": "STL1"
            },
            {
                "job_id": "JOB00428",
                "job_name": "HELLOPGM",
                "owner": "OMVSADM",
                "ret_code": {
                    "code": 0,
                    "msg": "CC 0000"
                },
                "subsystem": "STL1",
                "system": "STL1"
            }
        ],
        "message": ""
    }
}

TASK [Query submitted job id] ****************************************************************************************************************************************************************************************************************************************
ok: [zvm]

TASK [Response] ******************************************************************************************************************************************************************************************************************************************************
ok: [zvm] => {
    "msg": {
        "changed": false,
        "failed": false,
        "jobs": [
            {
                "job_id": "JOB00503",
                "job_name": "HELLOPGM",
                "owner": "OMVSADM",
                "ret_code": {
                    "code": 0,
                    "msg": "CC 0000"
                },
                "subsystem": "STL1",
                "system": "STL1"
            }
        ],
        "message": ""
    }
}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************************************
zvm                        : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by hyzhang6639** [comment]
The issue can be resolved after upgrading to Python3.9 and zoau 1.2.1. Thanks a lot!
