### ISSUE TITLE
[Bug] [zos_copy] Sometimes the record length computation throws an encoding error

### ISSUE THREAD

**Issue by rexemin** [ansible-collections/ibm_zos_core#664]
### Bug description

If a file has a different encoding other than IBM-1047, the function `get_record_length` can throw an encoding error when the file is opened and an invalid byte is read. This invalid byte corresponds to another encoding being used.

This bug was first encountered in an L2 support case, and as such, it will need to be addressed in following releases of the collection.

### Ansible version

```shell
ansible [core 2.11.12] 
  config file = /Users/iamorenosoto/Documents/IBM/Development/GitHub/553_554/playbooks/ansible.cfg
  configured module search path = ['/Users/iamorenosoto/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/iamorenosoto/.pyenv/versions/3.8.12/envs/gh-588/lib/python3.8/site-packages/ansible
  ansible collection location = /Users/iamorenosoto/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/iamorenosoto/.pyenv/versions/gh-588/bin/ansible
  python version = 3.8.12 (default, Jan 17 2022, 16:02:56) [Clang 13.0.0 (clang-1300.0.27.3)]
  jinja version = 3.1.2
  libyaml = True
```

### IBM z/OS Ansible core Version

v1.4.0, v1.5.0-beta.1

### IBM ZOAU version

v1.1.1

### z/OS version

2.3

### Ansible module

zos_copy

**Comment by ddimatos** [comment]
This is  just adding to my cp37 comment, the link i provided I did not highlight the section i as eluding to:
```
I did notice that the DB2 V8 precompiler, with C and CPP, uses 37 by
default, not 1047. (But I'm used to ??( and ??), anyway. Mental note to
self - override DB2 precompiler step with CP 1140.)
```
We don't have to do anything but just thought it was an interesting data point.
