### ISSUE TITLE
[Enhancement] [module_utils,zos_copy] Data integrity code needs to be reviewed if its needed and if not removed

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#696]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Ansible module

zos_copy

### Enhancement or feature description

Initially we had added some logic around data integrity meaning we would perform a backup any time data was involved that could be at risk should a module fail. This was likely in place while a module was in beta but since is not needed but before we simply remove function:
1) Review the code and consider if it is needed and which modules are using it. 
2) If removed, author more doc educating users on data integrity and encourage a backup be opted for. 

We do have backup capabilities, with a bit more education in terms of doc and or other avenues (eg blogs) we could encourage users to enable the function over us doing it automatically. 

As it is today, we use the dest to make the backup (emergency) copy and although that might sound reasonable when it coes to data sets they are limited in space and sometime very large in upwards of 50GB that we would be backing up and risk not having enough space or time to do this. 
We could default to USS files instead of the dest as a data set but the same problem arises, space is always a concern as is compute which in a z/OS way, compute equates to MIPS and is a direct cost. 

The code currently is in zos_copy but it may be in other modules as well.

**Comment by richp405** [comment]
Need to call a meeting to decide if there is any external need for some of the 'if not backup' logic.  If not, this is ready for PR.

**Comment by ddimatos** [comment]
This relates to issues:
https://github.com/ansible-collections/ibm_zos_core/issues/587
https://github.com/ansible-collections/ibm_zos_core/issues/588
