### ISSUE TITLE
[Enabler] [zos_archive,zos_unarchive] Create playbooks and supporting content

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#704]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

This issue focuses on creating playbooks and supporting content for the zos_archive and zos_unarchive modules.

**Comment by ddimatos** [comment]
Moving this to Q3 iteration 2 to continue and have visibility

**Comment by fernandofloresg** [comment]
Created PR https://github.com/IBM/z_ansible_collections_samples/pull/230 no approval is needed to merge but want some feedback.
