### ISSUE TITLE
[Enabler] Evaluate setting `ansible_ssh_transfer_method: sftp` to see if it helps the binary reads

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#708]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

- [x] Test setting `ansible_ssh_transfer_method: sftp`, by default Ansible uses scp where on z/OS this becomes a transfer that is auto converted to the z/OS locale, by switching to SFTP as the transport protocol it will ensure a binary transfer and encodings don't change. This will break zos_ibm_core modules but that is ok for now, point is try to understand if there is a community work around.

**Comment by ketankelkar** [comment]
some docs - https://docs.ansible.com/ansible/latest/collections/ansible/builtin/ssh_connection.html#parameter-ssh_transfer_method
