### ISSUE TITLE
[Enabler] [zos_volume] video

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#713]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

Issue allocates time to assist the media team with assistance to record content for the volume module.

**Comment by ketankelkar** [comment]
upon further discussion with Dan and Demetrios, we've established that the scope of work is larger than initially expected. We want the demo to be run from AAP which will require some research on my part to learn how to set up and drive playbooks from AAP and create a template, etc.

**Comment by ketankelkar** [comment]
We got a successful run of the [playbook](https://github.com/IBM/z_ansible_collections_samples/blob/demo-volume-init/zos_concepts/volume_management/volume_initialization/init_dasd_vol_and_run_sample_jcl/init_dasd_vol_and_run_sample_jcl.yml) on the samples repository through Ansible Automation Platform. 


![Image](https://github.com/ansible-collections/ibm_zos_core/assets/10567394/46ae6ec3-6ad7-46f3-9357-317d9efb66a0)



![Image](https://github.com/ansible-collections/ibm_zos_core/assets/10567394/bd40fa3f-9d77-4704-aec7-ce8dcc963f50)


The next steps are to put together slides, draft a script, and then record/edit the video

**Comment by ketankelkar** [comment]
A version of the video was presented at the Z Ansible Guild Call Wednesday May 8. 
Feedback was positive, customers asked for a copy of the video.
One common suggestion for improvement was to speed up the narration. A fresh recording of the audio has been created and edited in with the visuals. 

Only steps remaining are to share it to the content team and get it published, and possibly write a blog around this video (which will be encompassed in a different work item). 

Given this, I am closing the work item.
