### ISSUE TITLE
[Bug] Source data set does not exist

### ISSUE THREAD

**Issue by derald-rogers** [ansible-collections/ibm_zos_core#745]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Are the dependencies a supported version?

- [X] The dependencies are supported.

### IBM Z Open Automation Utilities

v1.2.1

### IBM Enterprise Python

v3.10.x

### IBM z/OS Ansible core Version

v1.5.0

### ansible-version

v2.9.x

### z/OS version

v2.5

### Ansible module

zos_copy

### Bug description

When I attempt to run zos_copy, I receive the following error:
Source data set <data set here> does not exist.
I have confirmed the dataset exists using a second mainframe display application tool ( BlueZone Mainframe Display )

### Playbook verbosity output.

ansible-playbook 2.9.27
  config file = /tmp/bwrap_7578_j6anllqu/awx_7578_jol40pci/project/ansible.cfg
  configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, May 27 2022, 11:27:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Using /tmp/bwrap_7578_j6anllqu/awx_7578_jol40pci/project/ansible.cfg as config file
SSH password: 
host_list declined parsing /tmp/bwrap_7578_j6anllqu/awx_7578_jol40pci/tmp2oo5njb1 as it did not pass its verify_file() method
[WARNING]: Invalid characters were found in group names but not replaced, use
-vvvv to see details
Parsed /tmp/bwrap_7578_j6anllqu/awx_7578_jol40pci/tmp2oo5njb1 inventory source with script plugin
Skipping callback 'actionable', as we already have a stdout callback.
Skipping callback 'awx_display', as we already have a stdout callback.
Skipping callback 'counter_enabled', as we already have a stdout callback.
Skipping callback 'debug', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'full_skip', as we already have a stdout callback.
Skipping callback 'json', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'null', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
Skipping callback 'selective', as we already have a stdout callback.
Skipping callback 'skippy', as we already have a stdout callback.
Skipping callback 'stderr', as we already have a stdout callback.
Skipping callback 'unixy', as we already have a stdout callback.
Skipping callback 'yaml', as we already have a stdout callback.
PLAYBOOK: MoveMembers.yml ******************************************************
1 plays in MainframeAutomation/MoveMembers.yml
PLAY [all] *********************************************************************
META: ran handlers
TASK [Debug env vars] **********************************************************
task path: /tmp/bwrap_7578_j6anllqu/awx_7578_jol40pci/project/MainframeAutomation/MoveMembers.yml:8
Tuesday 18 April 2023  14:07:23 +0000 (0:00:00.100)       0:00:00.100 ********* 
Tuesday 18 April 2023  14:07:23 +0000 (0:00:00.102)       0:00:00.102 ********* 
ok: [xa1.bcbst.com] => {
    "msg": {
        "LANG": "C", 
        "LIBPATH": "/usr/lpp/IBM/zoautil/lib:/usr/lpp/IBM/cyp/v3r10/pyz/bin/python3/lib:/lib:/usr/lib:.", 
        "PATH": "/usr/lpp/IBM/zoautil/bin:/usr/lpp/IBM/cyp/v3r10/pyz/bin/python3/bin:/bin:/var/bin:/usr/lpp/java/J8.0/bin", 
        "ZOAU_HOME": "/usr/lpp/IBM/zoautil", 
        "_BPXK_AUTOCVT": "ON", 
        "_CEE_RUNOPTS": "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)", 
        "_TAG_REDIR_ERR": "txt", 
        "_TAG_REDIR_IN": "txt", 
        "_TAG_REDIR_OUT": "txt"
    }
}
TASK [Loop through move playbook for each listed member] ***********************
task path: /tmp/bwrap_7578_j6anllqu/awx_7578_jol40pci/project/MainframeAutomation/MoveMembers.yml:11
Tuesday 18 April 2023  14:07:24 +0000 (0:00:00.103)       0:00:00.203 ********* 
Tuesday 18 April 2023  14:07:24 +0000 (0:00:00.107)       0:00:00.209 ********* 
included: /tmp/bwrap_7578_j6anllqu/awx_7578_jol40pci/project/MainframeAutomation/NonpackageMove.yml for xa1.bcbst.com
included: /tmp/bwrap_7578_j6anllqu/awx_7578_jol40pci/project/MainframeAutomation/NonpackageMove.yml for xa1.bcbst.com
included: /tmp/bwrap_7578_j6anllqu/awx_7578_jol40pci/project/MainframeAutomation/NonpackageMove.yml for xa1.bcbst.com
included: /tmp/bwrap_7578_j6anllqu/awx_7578_jol40pci/project/MainframeAutomation/NonpackageMove.yml for xa1.bcbst.com
included: /tmp/bwrap_7578_j6anllqu/awx_7578_jol40pci/project/MainframeAutomation/NonpackageMove.yml for xa1.bcbst.com
included: /tmp/bwrap_7578_j6anllqu/awx_7578_jol40pci/project/MainframeAutomation/NonpackageMove.yml for xa1.bcbst.com
TASK [Move member] *************************************************************
task path: /tmp/bwrap_7578_j6anllqu/awx_7578_jol40pci/project/MainframeAutomation/NonpackageMove.yml:5
Tuesday 18 April 2023  14:07:24 +0000 (0:00:00.197)       0:00:00.401 ********* 
Tuesday 18 April 2023  14:07:24 +0000 (0:00:00.194)       0:00:00.404 ********* 
included: /tmp/bwrap_7578_j6anllqu/awx_7578_jol40pci/project/MainframeAutomation/CopyMember.yml for xa1.bcbst.com
TASK [Debug member name] *******************************************************
task path: /tmp/bwrap_7578_j6anllqu/awx_7578_jol40pci/project/MainframeAutomation/CopyMember.yml:1
Tuesday 18 April 2023  14:07:24 +0000 (0:00:00.041)       0:00:00.442 ********* 
Tuesday 18 April 2023  14:07:24 +0000 (0:00:00.039)       0:00:00.443 ********* 
ok: [xa1.bcbst.com] => {
    "msg": "ZT306S85"
}
TASK [Copy member from source library to destination library] ******************
task path: /tmp/bwrap_7578_j6anllqu/awx_7578_jol40pci/project/MainframeAutomation/CopyMember.yml:4
Tuesday 18 April 2023  14:07:24 +0000 (0:00:00.129)       0:00:00.572 ********* 
Tuesday 18 April 2023  14:07:24 +0000 (0:00:00.135)       0:00:00.578 ********* 
<xa1.bcbst.com> ESTABLISH SSH CONNECTION FOR USER: d16875r
<xa1.bcbst.com> SSH: EXEC sshpass -d8 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'User="d16875r"' -o ConnectTimeout=10 -o ControlPath=/tmp/bwrap_7578_j6anllqu/awx_7578_jol40pci/cp/791d1644c3 xa1.bcbst.com '/bin/sh -c '"'"'echo ~d16875r && sleep 0'"'"''
<xa1.bcbst.com> (0, '/u/D16875R\n', "Warning: Permanently added 'xa1.bcbst.com,10.32.7.13' (RSA) to the list of known hosts.\r\n")
<xa1.bcbst.com> ESTABLISH SSH CONNECTION FOR USER: d16875r
<xa1.bcbst.com> SSH: EXEC sshpass -d8 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'User="d16875r"' -o ConnectTimeout=10 -o ControlPath=/tmp/bwrap_7578_j6anllqu/awx_7578_jol40pci/cp/791d1644c3 xa1.bcbst.com '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /u/D16875R/.ansible/tmp `"&& mkdir "` echo /u/D16875R/.ansible/tmp/ansible-tmp-1681826844.94-22-163525825759854 `" && echo ansible-tmp-1681826844.94-22-163525825759854="` echo /u/D16875R/.ansible/tmp/ansible-tmp-1681826844.94-22-163525825759854 `" ) && sleep 0'"'"''
<xa1.bcbst.com> (0, 'ansible-tmp-1681826844.94-22-163525825759854=/u/D16875R/.ansible/tmp/ansible-tmp-1681826844.94-22-163525825759854\n', '')
Using module file /tmp/bwrap_7578_j6anllqu/awx_7578_jol40pci/requirements_collections/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_copy.py
<xa1.bcbst.com> PUT /var/lib/awx/.ansible/tmp/ansible-local-3Emlxjw/tmp5mcy9_ TO /u/D16875R/.ansible/tmp/ansible-tmp-1681826844.94-22-163525825759854/AnsiballZ_zos_copy.py
<xa1.bcbst.com> SSH: EXEC sshpass -d8 sftp -o BatchMode=no -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'User="d16875r"' -o ConnectTimeout=10 -o ControlPath=/tmp/bwrap_7578_j6anllqu/awx_7578_jol40pci/cp/791d1644c3 '[xa1.bcbst.com]'
<xa1.bcbst.com> (0, 'sftp> put /var/lib/awx/.ansible/tmp/ansible-local-3Emlxjw/tmp5mcy9_ /u/D16875R/.ansible/tmp/ansible-tmp-1681826844.94-22-163525825759854/AnsiballZ_zos_copy.py\n', '')
<xa1.bcbst.com> ESTABLISH SSH CONNECTION FOR USER: d16875r
<xa1.bcbst.com> SSH: EXEC sshpass -d8 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'User="d16875r"' -o ConnectTimeout=10 -o ControlPath=/tmp/bwrap_7578_j6anllqu/awx_7578_jol40pci/cp/791d1644c3 xa1.bcbst.com '/bin/sh -c '"'"'chmod u+x /u/D16875R/.ansible/tmp/ansible-tmp-1681826844.94-22-163525825759854/ /u/D16875R/.ansible/tmp/ansible-tmp-1681826844.94-22-163525825759854/AnsiballZ_zos_copy.py && sleep 0'"'"''
<xa1.bcbst.com> (0, '', '')
<xa1.bcbst.com> ESTABLISH SSH CONNECTION FOR USER: d16875r
<xa1.bcbst.com> SSH: EXEC sshpass -d8 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'User="d16875r"' -o ConnectTimeout=10 -o ControlPath=/tmp/bwrap_7578_j6anllqu/awx_7578_jol40pci/cp/791d1644c3 -tt xa1.bcbst.com '/bin/sh -c '"'"'_BPXK_AUTOCVT=ON LANG=C _TAG_REDIR_IN=txt ZOAU_HOME=/usr/lpp/IBM/zoautil _TAG_REDIR_OUT=txt _CEE_RUNOPTS='"'"'"'"'"'"'"'"'FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)'"'"'"'"'"'"'"'"' PATH=/usr/lpp/IBM/zoautil/bin:/usr/lpp/IBM/cyp/v3r10/pyz/bin/python3/bin:/bin:/var/bin:/usr/lpp/java/J8.0/bin LIBPATH=/usr/lpp/IBM/zoautil/lib:/usr/lpp/IBM/cyp/v3r10/pyz/bin/python3/lib:/lib:/usr/lib:. _TAG_REDIR_ERR=txt /usr/lpp/IBM/cyp/v3r10/pyz/bin/python3 /u/D16875R/.ansible/tmp/ansible-tmp-1681826844.94-22-163525825759854/AnsiballZ_zos_copy.py && sleep 0'"'"''
<xa1.bcbst.com> (1, '\r\n{"msg": "Source data set SYS1.WORKJCL(ZT306S85) does not exist", "failed": true, "exception": "  File \\"/tmp/ansible_ibm.ibm_zos_core.zos_copy_payload_68yt3qcj/ansible_ibm.ibm_zos_core.zos_copy_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_copy.py\\", line 2117, in run_module\\n", "invocation": {"module_args": {"remote_src": true, "is_pds": false, "src_member": true, "local_charset": "UTF-8", "dest": "SYS1.USERJCL(ZT306S85)", "is_src_dir": false, "is_uss": false, "temp_path": null, "src": "SYS1.WORKJCL(ZT306S85)", "copy_member": true, "is_mvs_dest": false, "is_binary": false, "backup": false, "local_follow": true, "ignore_sftp_stderr": false, "validate": false, "force": false, "follow": false, "unsafe_writes": false, "encoding": null, "content": null, "backup_name": null, "volume": null, "dest_data_set": null, "size": null, "mode": null, "tmp_hlq": null, "owner": null, "group": null, "seuser": null, "serole": null, "selevel": null, "setype": null, "attr…
<xa1.bcbst.com> Failed to connect to the host via ssh: Shared connection to xa1.bcbst.com closed.
<xa1.bcbst.com> ESTABLISH SSH CONNECTION FOR USER: d16875r
<xa1.bcbst.com> SSH: EXEC sshpass -d8 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'User="d16875r"' -o ConnectTimeout=10 -o ControlPath=/tmp/bwrap_7578_j6anllqu/awx_7578_jol40pci/cp/791d1644c3 xa1.bcbst.com '/bin/sh -c '"'"'rm -f -r /u/D16875R/.ansible/tmp/ansible-tmp-1681826844.94-22-163525825759854/ > /dev/null 2>&1 && sleep 0'"'"''
<xa1.bcbst.com> (0, '', '')
fatal: [xa1.bcbst.com]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "dest": "SYS1.USERJCL(ZT306S85)", 
            "remote_src": true, 
            "src": "SYS1.WORKJCL(ZT306S85)"
        }
    }, 
    "msg": "Source data set SYS1.WORKJCL(ZT306S85) does not exist", 
    "rc": null, 
    "stderr": null, 
    "stderr_lines": null, 
    "stdout": null, 
    "stdout_lines": null
}

### Ansible configuration.

```YAML
# config file for ansible -- https://ansible.com/
# ===============================================

# nearly all parameters can be overridden in ansible-playbook
# or with command line flags. ansible will read ANSIBLE_CONFIG,
# ansible.cfg in the current working directory, .ansible.cfg in
# the home directory or /etc/ansible/ansible.cfg, whichever it
# finds first

[defaults]
verbosity = 0

inventory      = ./inventory

gathering = implicit
gather_subset = !facter,!ohai,all,min

host_key_checking = True

stdout_callback = yaml
callback_whitelist = timer, yaml, profile_tasks, profile_roles
bin_ansible_callbacks = True

deprecation_warnings = True

command_warnings = True

retry_files_enabled = False

# Installs collections into [current dir]/ansible_collections/namespace/collection_name
COLLECTIONS_PATHS = './collections'
# Installs roles into [current dir]/roles/namespace.rolename
roles_path = ./roles

[privilege_escalation]
#become=True
#become_method=sudo
#become_user=root
#become_ask_pass=False
```

### Contents of `group_vars` or `host_vars`

```YAML
---
ansible_port: 22
ansible_python_interpreter: /usr/lpp/IBM/cyp/v3r10/pyz/bin/python3
PYZ: /usr/lpp/IBM/cyp/v3r10/pyz/bin/python3
ZOAU: /usr/lpp/IBM/zoautil
environment_vars:
  _BPXK_AUTOCVT: "ON"
  ZOAU_HOME: "{{ ZOAU }}"
  LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
  PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin:/var/bin:/usr/lpp/java/J8.0/bin"
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_ERR: "txt"
  _TAG_REDIR_IN: "txt"
  _TAG_REDIR_OUT: "txt"
  LANG: "C"
```

**Comment by ddimatos** [comment]
@derald-rogers thank you for opening up an issue. We will look into this soon.

**Comment by ddimatos** [comment]
Giving a quick glance, i see this is 1.5.0-beta.1 and its throwing an exception on line [2117 raise NonExistentSourceError(src)](https://github.com/ansible-collections/ibm_zos_core/blob/e3dd3b796dcd215c4cc7af0eb84d4057f912d18f/plugins/modules/zos_copy.py#L2117).

Not to be confused with line 2113 where this would throw the same exception if we found that the data set existed (code below)
```
                if src_member and not data_set.DataSet.data_set_member_exists(src):
                    raise NonExistentSourceError(src)
```

This falls into 2117 where we could not find the data set, I don't recall without looking at the code in more detail if we will try to catalog for the user, but to do a `attempt_catalog_if_necessary` we would need the volume and that is not part of the args: 
```
"module_args": {
"dest": "SYS1.USERJCL(ZT306S85)",
"remote_src": true,
"src": "SYS1.WORKJCL(ZT306S85)"
}```

So, @derald-rogers - can you tell us if the data set `SYS1.WORKJCL(ZT306S85)` was cataloged. 

@rexemin - i bet we could do a bit more in that class exception and check if a data set is cataloged and maybe provide more details. Ill let you think about that and we could open a new git issue for that.

**Comment by derald-rogers** [comment]
@ddimatos Workcjl and userjcl return in the listc command
"listc": {
        "failed": false,
        "changed": true,
        "output": [
            {
                "content": [
					<...>
                    "NONVSAM ------- SYS1.GDC.USERJCL",
                    "     IN-CAT --- BCBST.ICFMCAT",
					<...>
                    "NONVSAM ------- SYS1.WORKJCL",
                    "     IN-CAT --- BCBST.ICFMCAT",
                    <...>
                ],
                "lines": 2641,
                "command": "LISTC LVL('SYS1')",
                "rc": 0
            }
        ]
    },
    "_ansible_no_log": false
}

The _<...>_ is my edit to make it more legible.

**Comment by ddimatos** [comment]
Ill want to triage this with @rexemin but could you share the attributes for `SYS1.WORKJCL` so when we can look more into this we can use those attributes for a recreate. If you want, feel free to include `SYS1.USERJCL`

**Comment by ddimatos** [comment]
There have been some offline discussions, thus Ill update this issue with them.
To obtain the attributes it was suggested to use ISPF or `dls` where `dls` was selected eg
```
    - name: List data set details
      ansible.builtin.shell: dls -l -a -b -s -u SYS1.WORKJCL
      register: result
```
This uncovered an error reported `BGYSC0236E Unable to call authorized program idcams from mvscmd. Use mvscmdauth.` where then focus was shifted to ZOAU and checked that:
- [x] ZOAU had all 9 APF attributes on required utilities
       - All APF bits are applied correctly
- [x] ZOAU had correct RACF configuration for OPERCMDS
       - No way to validate but user responded such the RACF is correctly been set for the omvs segement
- [x] Provided user with instructions to run ZOAU utilities from shell with a `.profile` according to their Ansible Env vars configuration
       - Resulted in a BGYSC0236E Unable to call authorized program idcams from mvscmd. Use mvscmdauth. for the ansible user but when the same diagnostics was done for root user , one could see that the temporary data sets created for `dls` to place the SYSIN (from stdin) too failed to be created, which constitutes more success as root than the ansible user but also suggests this is a ZOAU/System configuration issue. 
- [x] checked the zoau version (it is 2022/09/07 15:26:50 CUT V1.2.1 d2f6557 1880)

RACF commands:
```
RDEFINE OPERCMDS MVS.MCSOPER.DDIMATO
SETROPTS RACLIST(OPERCMDS) REFRESH
PERMIT MVS.MCSOPER.DDIMATO CLASS(OPERCMDS) ID(DDIMATO) ACCESS(READ)
SETROPTS RACLIST(OPERCMDS) REFRESH
```

**Comment by ddimatos** [comment]
This appears to be a ZOAU system configuration issue,  ZOAU is a dependency that is required by `ibm_zos_core`, this community will make its best attempt to assist wit ZOAU configuration issues but beyond that, it is recommended they seek  S&S via entitlement from Ansible Automation Platform that would allow a ZOAU support case be opened to IBM. The other option is to try to engage the [ZOAU community](https://github.com/IBM/zoau-samples) if no S&S is present.
