### ISSUE TITLE
[Enhancement] [zos_job_query] Include new pgm-name field

### ISSUE THREAD

**Issue by storfibm** [ansible-collections/ibm_zos_core#760]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Ansible module

zos_job_query

### Enhancement or feature description

**Ansible module**
zos_job_query

**Enhancement or feature description**
ZOAU 1.2.4 delivered a new `pgm-name` attribute flag in the detailed job listing utility via `jls -l`. This column should be properly pulled in whenever detailed job attributes are being requested by Ansible users.

**Acceptance Criteria**
Given the z/os Core Collection
When a user invokes zos_job_query
Then job listings include the program name attribute

**Requirements**
-Leverage new pgm-name attribute in job details

**Comment by storfibm** [comment]
Completed by ZOAU in 1.2.4

**Comment by ddimatos** [comment]
pgm-name has performance implications, we would not be able to simply include it as part of our query, we would need to likely have an option that enables and displaying of pgm-name.

**Comment by richp405** [comment]
completed in rerun of 839
