### ISSUE TITLE
[Collaboration] z/OS Gather facts version detection fails.

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#784]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Support and service?

- [X] Yes, support and service is involved.
- [ ] No, support and service is involved.

### Are the dependencies a supported?

- [X] Yes, the dependencies are supported.
- [ ] Not applicable to this collaboration.

### IBM Z Open Automation Utilities

v1.2.3

### IBM Enterprise Python

v3.9.x

### IBM z/OS Ansible core Version

v1.5.0

### ansible-version

v2.14.x

### z/OS version

v2.5

### Ansible module

zos_gather_facts

### Collaboration description

Version checker failing, see reference 77f41816901910b7df10f9d11642a369.
See issue #783

**Comment by ketankelkar** [comment]
a hotfix was provided to the customer as well as an alternative solution
