### ISSUE TITLE
[Enabler] Update pipeline to include Ansible 2.15

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#785]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

`ansible-core` 2.15 has GA'd, our pipeline was using 2.15 from devel as pipeline option latest, likely now that is pointing to 2.16, we have a gap with no option for 2.15 , the pipeline needs an update to use 2.15 so we can certify and GA on it by June.

**Comment by richp405** [comment]
Have a script including 2.15.0, but it is generating 'module not found' error.  I will track this down on Tuesday.

**Comment by richp405** [comment]
been dealing with an error that ONLY shows up starting in Ansible 2.15... it appears that older behavior was finally locked out in March 2023 (2.15.0 release).

Error is: 
    from ansible_collections.ibm.ibm_zos_core.plugins.module_utils.data_set import (
E   ModuleNotFoundError: No module named 'ansible_collections'

I found adding pythonpath back to the environment has moved the error, so I think I'm close to getting this resolved.

All work so far is on Jenkinsfile5b, so it doesn't interfere with normal builds (which use Jenkinsfile5)

**Comment by ddimatos** [comment]
Will move this to Q3:sprint 6 so we can clean up and prepare for next quarter

**Comment by richp405** [comment]
Created -Experimental link, connected to Jenkinsfile5d in rep.  Showed it to Marcel today
