### ISSUE TITLE
[Documentation] Documentation for `zos_copy` `remote_src` parameter does not specify the default

### ISSUE THREAD

**Issue by stewartfrancis** [ansible-collections/ibm_zos_core#817]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Are the dependencies a supported version?

- [X] The dependencies are supported.

### IBM Z Open Automation Utilities

v1.2.3

### IBM Enterprise Python

v3.14.x

### IBM z/OS Ansible core Version

v1.9.0

### ansible-version

v2.14.x

### z/OS version

v2.5

### Ansible module

zos_copy

### Bug description

Documentation for `zos_copy` module states that `remote_src` is a `required: false` `type: bool` but does not explain what the default is when not supplied

>remote_src
>If set to false, the module searches for src at the local machine.
>
>If set to true, the module goes to the remote/target machine for src.
>
>required: False
>type: bool

**Comment by stewartfrancis** [comment]
Sorry didn't spot the documentation category when I raised this one!

**Comment by ddimatos** [comment]
@stewartfrancis thank you for this suggestion. I agree, I think we should be explicit in all cases even though the parser does not require it. With ansible-lint as an upcoming certification requirement, such things are going to become lint errors.

**Comment by ddimatos** [comment]
This is had been resolved , in fact it was an issue for all collections who adopted the jinja template for ibm_zos_core where defaults were not being shown.

<img width="602" alt="image" src="https://github.com/ansible-collections/ibm_zos_core/assets/25803172/c863ae9c-aa44-4936-a960-9e2082f897d0">

See change here during a release task: https://github.com/ansible-collections/ibm_zos_core/pull/1207/files#diff-8b9437868392ebd2dd80948f106a2fc1ec2cd3b6a902a34a3eba49113805f60d
