### ISSUE TITLE
[Documentation] Documentation for `zos_copy` `backup` parameter states the parameter is an optional `bool` but does not state what the default is if unsupplied

### ISSUE THREAD

**Issue by stewartfrancis** [ansible-collections/ibm_zos_core#819]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Documentation issue description

>backup
>Specifies whether a backup of the destination should be created before copying data.
>
>When set to true, the module creates a backup file or data set.
>
>The backup file name will be returned on either success or failure of module execution such that data can be retrieved.
>
>required: False
>type: bool

### IBM z/OS Ansible core Version

v1.5.0

### Ansible module

zos_copy

**Comment by ddimatos** [comment]
@stewartfrancis - I agree, really all of our modules should state the obvious its what we prefer and as I noted in other corrections you suggested, ansible-lint will likely start picking up on these soon enough.

**Comment by rexemin** [comment]
We fixed this issue during the course of this year, if you take a look at [our updated documentation](https://ibm.github.io/z_ansible_collections_doc/ibm_zos_core/docs/source/modules/zos_copy.html) you'll see the default value for all bool optional options. You can also now see this inside the documentation of the module if you browse it through the Ansible CLI.
