### ISSUE TITLE
[Enabler]  [zos_copy] Evaluate existing support for ASA in commands and programs

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#884]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Ansible module

zos_copy

### Enabler description

This issue is for evaluating how 'asa' content is handled by programs:
- `cp`
- `dcp`
- `idcams`

The idea is to use the test cases (USS and data set) containing ASA encoded data and try to find a solution that will retain the control chars. 

Special considered will need to be considered with regard to where the ASA data is located. For example, consider the flows:
1) MVS --> USS
2) USS --> MVS
3) Data leaving and coming back into USS or MVS with consideration for (1) and (2)

For `cp`:
When reading the docs, it appears there is some form of support if you review the below snippets;
MVS --> USS as text (-T)
```
When you copy MVS data sets to text files in the z/OS® UNIX file system, a <newline> character is appended to the end of each record. If trailing blanks exist in the record, the <newline> character is appended after the trailing blanks. If the file format option is specified or the target file has the file format set, that file format is used as the end-of-line delimiter instead of <newline>.
```

MVS --> USS as Binary (-B)
```
When you copy MVS data sets to UNIX binary files, the <newline> character is not appended to the record.
```

USS --> MVS as text (-T)
```
For text files, all <newline> characters are stripped during the copy. Each line in the file ending with a <newline> character is copied into a record of the MVS data set. If text file format is specified or already exists for the source file, that file format will be used for end-of-line delimiter instead of <newline>. Note that cp looks for IBM-1047 end-of-line delimiters in data. 
```

USS --> MVS as Binary (-B)
```
For binary files, all copied data is preserved.
For an MVS data set in fixed record format, data is cut into chunks of size equal to the record length. Each chunk is put into one record. The last record is padded with blanks.
```

From reading this, it is obvious we will need to carefully capture the results and it appears that the results could even vary depending on how the file is `tagged` , so please capture this.

With `cp` there is also the` -F format` which will allow control of the trailing line. My understanding is if an ASA file is copied as text data (-T) MVS --> USS, the ASA control chars (start of a line) **might** be preserved but, I appears the newline is removed unless -F is used to  "specify the following text data delimiters":
```
Or, you can specify the following text data delimiters:

nl
    Newline character.
cr
    Carriage return.
lf
    Line feed.
crlf
    Carriage return followed by line feed.
lfcr
    Line feed followed by carriage return.
crnl
    Carriage return followed by new line. 
```

In this issue we need to completely grasp the various scenarios so we can code to them in zos_copy and have a recommended path using zos_copy.

For `dcp`, i am not sure how much of `cp` flows through and is supported but worth noting.

For `idcams` , some added research should be done, especially if there is no successful path using `cp` or `dcp`. If `idcams` is needed we can consider its execution in the modules code.

See issues:
#835 
#883
#884
#885 
#886

**Comment by rexemin** [comment]
I investigated and tried a couple of things. So just running `cp dataset file` will make the program process all the ASA chars and put the result in the destination file. Doing this has the effect of breaking `asa`, but if you do a `cat`, you will see the output you'd expect. Although if you open the file either through vi or in Python, the ASA control chars are nowhere to be found. For some reason, copying back the file to the dataset will copy all the ASA chars, so it's probably handled at the system level and becomes more transparent to a user. `dcp` behaves the same.

Using a binary copy corrupts the file and messes up the ASA control chars.

Using ZOAU's Python API, ASA chars are already handled without doing anything at all. Just calling `datasets.copy(dataset, file)` or `datasets.copy(file, dataset)` will handle ASA chars. This works too when using `zos_copy` with a remote source, but breaks down the moment you use a local file.
