### ISSUE TITLE
[Enabler] [zos_copy] Evaluate `zos_copy` capabilities when interacting with ASA

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#885]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Ansible module

zos_copy

### Enabler description

This issue is to evaluate `zos_copy` capabilities when interacting with ASA data.

- Does ASA work with out any module options?
- Does zos_copy require `is_binary=true` for ASA?
   - Are all options added to support BINARY=true for ASA such as -F?
- Although,these are not likely all use cases, its good to evaluate them with:
        - `remote_src = true`
           - [X] MVS to USS
           - [X] USS to MVS
        - `remote_src = false`
           - [X] to USS
           - [X] to MVS

See issues:
#835 
#883
#884
#885 
#886

**Comment by rexemin** [comment]
Leaving a comment on this issue to document the results so far:
- In some cases, the module can handle ASA files correctly without any special options like `is_binary`. These cases are when copying between data sets with record formats FBA/VBA, and when copying from an ASA data set to a USS file and back (when the file came from a similar data set).
- ASA files do not require a binary copy. In most cases, using a binary copy ends up corrupting the records and the control chars on the destination data set. Same goes with the use of `cp -F`.
- For copying files from USS to an ASA data set, `OGET` preserves control chars as the first byte of a record
