### ISSUE TITLE
[Documentation] [zos_copy] destination doc is refering to src as binary as if it knows its binary, should be is_binary.

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#923]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Documentation issue description

The zos_copy doc has a minor error I believe , in the `dest` it reads 'If **C(src)** is binary, C(dest) will have a Fixed Block (FB) record format' , error is it says if the src is binary, i feel like it should have been "  If I(is_binary=true), C(dest) will have a Fixed Block (FB) record format" , meaning if the option `is_binary` is set to true, then .... , we don't really know if src is binary or not nor do we inspect it, we need `is_binary` to be set to true, this is why i feel its a doc bug. 

From:
```
  If C(src) is binary, C(dest) will have a Fixed Block (FB) record format
        with a record length of 80, block size of 32760, and the remaining
        attributes will be computed.
```

To:
```
        If I(executable=true),C(dest) will have a Undefined (U)record format
        with a record length of 0, block size of 32760, and the remaining
        attributes will be computed.
```

### IBM z/OS Ansible core Version

v1.6.0

### Ansible module

zos_copy

**Comment by ketankelkar** [comment]
We get this one for free! It was already addressed in PR #804
