### ISSUE TITLE
[Bug] zos_tso_command fails to unallocate dataset where running the unalloc command from ISPF succeeds

### ISSUE THREAD

**Issue by slpahle** [ansible-collections/ibm_zos_core#938]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Are the dependencies a supported version?

- [X] The dependencies are supported.

### IBM Z Open Automation Utilities

v1.1.1

### IBM Enterprise Python

v3.8.x

### IBM z/OS Ansible core Version

v1.6.0

### ansible-version

v2.14.x

### z/OS version

v2.4

### Ansible module

zos_tso_command

### Bug description

I realize ZOAU 1.2.2 is required for version 1.6.0. I have requested my version be updated, but at the same time I've been assured that `zos_tso_command` doesn't actually use ZOAU so it shouldn't make a difference in this case.

1. Allocate a dataset, either manually from the ISPF Command Shell or via the `zos_data_set` module:
    - ```
        name: Allocate dataset
        ibm.ibm_zos_core.zos_data_set:
        name: 'XXXXXX.YYYYYY.ZZZZZZ'
        state: present
        space_type: TRK
        space_primary: 500
        space_secondary: 50
        block_size: 3120
        directory_blocks: 100
        ``` 
    - ```
        alloc da('XXXXXX.YYYYYY.ZZZZZZ') new keep tracks space(500,50) lrecl(80) dsntype(pds) dsorg(po) recfm(f,b) blksize(3120) dir(100) NEW
        ```
2. Unallocate that dataset from the ISPF Command Shell with the TSO command `unalloc da('XXXXXX.YYYYYY.ZZZZZZ')`
3. Observe that the above command worked correcly
4. Either delete the dataset entirely and re-allocate, or run a simple allocation command again (ex. `alloc da('XXXXXX.YYYYYY.ZZZZZZ')`
5. Run the unallocate command using `zos_tso_command`
    - ```
        - name: Unallocate installation dataset to give others access
          ibm.ibm_zos_core.zos_tso_command:
            commands:
              - "unalloc da('XXXXXX.YYYYYY.ZZZZZZ')"
        ```
6. Observe that the above command fails with a return code of 12 and an error: "IKJ56247I DATA SET XXXXXX.YYYYYY.ZZZZZZ NOT FREED, IS NOT ALLOCATED"
7. Repeat step 3 to run the unalloc command manually from the ISPF Command Shell and observe that it runs successfully

This is consistent. If the dataset in question is in a state where the `unalloc` command should work, when run with `zos_tso_command` the command **always** fails with the error code of 12 and the above error message.

I was informed that the suggested workaround is to just use `tsocmd` directly in a shell instead of using `zos_tso_command` but the results are the same. `tsocmd` always fails with exact same return code and error.

It was suggested that I open an issue here. It's been proven that this is not necessarily a issue directly with this collection (`tsocmd` doesn't work either) but there may be some difference between how you/it are running TSO commands as opposted to ISPF that could maybe be addressed.

Another example, if it helps, the following command run from ISPF succeeds:
`%@@1REXX 'XXXXXX.YYYYYY.ZZZZZZ' @@MACRO`
```
 Processing 61 members ...
 Processing complete!     
 ***         
```

But run with `zos_tso_command`:
```
                {
                    "command": "%@@1REXX 'XXXXXX.YYYYYY.ZZZZZZ' @@2MACRO",
                    "content": [
                        ""
                    ],
                    "failed": false,
                    "lines": 1,
                    "rc": 255,
                    "stderr": ""
                },
```

And run with `tsocmd`:
```
%@@1REXX 'XXXXXX.YYYYYY.ZZZZZZ' @@2MACRO
FSUMB451 tsocmd: TSO/E command "%@@1REXX 'XXXXXX.YYYYYY.ZZZZZZ' @@2MACRO" not found.
$ echo ?$
255
```

### Playbook verbosity output.

Only the output of the failing task, with some mildly redacted information. I hope that's enough. From our previous conversation I think you have a good understanding of the failure already.

[playbook_partial_output.txt](https://github.com/ansible-collections/ibm_zos_core/files/12381936/playbook_partial_output.txt)


### Ansible configuration.

```YAML
[defaults]
roles_path = roles
interpreter_python = /usr/lpp/IBM/cyp/v3r8/pyz/bin/python3
```

### Contents of `group_vars` or `host_vars`

```YAML
PYZ: "/usr/lpp/IBM/cyp/v3r8/pyz"
ZOAU: "/usr/lpp/IBM/zoautil"
```

```YAML
environment_vars:
  _BPXK_AUTOCVT: "ON"
  ZOAU_HOME: "{{ ZOAU }}"
  PYTHONPATH: "{{ ZOAU }}/lib"
  LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
  PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin:/var/bin"
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_ERR: "txt"
  _TAG_REDIR_IN: "txt"
  _TAG_REDIR_OUT: "txt"
  LANG: "C"
  PYTHONSTDINENCODING: "cp1047"
```

**Comment by slpahle** [comment]
Updated to ZOAU 1.2.3.2 and Python 3.9 and still seeing the same results

**Comment by fernandofloresg** [comment]
Looking at our code and the fact that this happens when issuing tsocmd from USS this is not an issue specific to ibm_zos_core collection. I suggest looking at the profile for tso commands in ISPF and try adding them when issuing the tsocmd.
