### ISSUE TITLE
[Enabler] [zos_job_query] Convert to job & DD listings' JSON format

### ISSUE THREAD

**Issue by storfibm** [ansible-collections/ibm_zos_core#942]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Ansible module

zos_job_output, zos_job_query, zos_job_submit

### Enabler description

ZOAU 1.3 is moving towards broader JSON output generation for its APIs and utilities. The z/OS Core Collection should support this mechanism to allow for more predictable processing, and also minimize chances that changes to the interfaces will break functionality.

**Acceptance Criteria**
Given the z/OS Core Collection
When ZOAU's job listing (jobs.listing) and DD listing (jobs.list_dds, jobs.read_output) functionality is invoked
Then JSON output is processed

**Requirements**
-Refactor zos_job_submit, zos_job_query & zos_job_submit  as needed
-Invoke ZOAU's new JSON output mechanism for job and DD listing calls
-Retain back-level ZOAU support that runs prior code until all prior ZOAU 1.3 versions are deprecated

**Additional Context**
Sample `jobs.listing()` JSON object
`{`
`        "data": {`
`                "J0523319": {`
`                       "owner": "MYUSER",`
`                       "name": "USERSL",`
`                        "id": "J0523319",`
`                       "status": "CC",`
`                        "ccode": "0000"`
`                },`
`                "J0523318": {`
`                        "owner": "MYUSER",`
`                        "name": "USERSL",`
`                        "id": "J0523318",`
`                        "status": "CC",`
`                        "ccode": "0000"`
`                }`
`        },`
`        "program": "jls",`
`        "options": "-J ",`
`        "rc": "0",`
`        "jobs_found": "2"`
`}`

Sample `jobs.read_output()` JSON object
`{`
`        "data": {`
`                "content": "        1 //USERSL  JOB ,MYUSER,MSGLEVEL=(1,1),                                 J0487140`
`          //  MSGCLASS=A,CLASS=A,NOTIFY=&SYSUID`
`          IEFC653I SUBSTITUTION JCL - ,MYUSER,MSGLEVEL=(1,1),MSGCLASS=A,CLASS=A,NOTIFY=MYUSER`
`        2 //STEP1 EXEC PGM=BPXBATCH,PARM='PGM /bin/sleep 2'`
`        3 //MYEXE EXEC PGM=BPXBATCH,PARM='PGM /bin/echo hello'`
`        4 //STEP3 EXEC PGM=IEFBR14`
`        5 //SYSIN     DD *               GENERATED STATEMENT
"`
`        },`
`        "program": "pjdd",`
`        "options": "-J ",`
`        "rc": "0",`
`        "content_length": "451"`
`}`

**Comment by richp405** [comment]
Removed 'needs triage' until we see at least the functional spec for 1.3 output, and what functions will be impacted.  Looking forward to early copy of migration guide.

**Comment by storfibm** [comment]
Added sample output for `jobs.list_dds()` & `jobs.read_output()`

**Comment by ddimatos** [comment]
`jobs.listing()` has been renamed to `jobs.fetch_multiple()`, see [migration guide](https://www.ibm.com/docs/en/zoau/1.3.x?topic=planning-migrating-zoau-v13-from-v12x-earlier)

**Comment by ddimatos** [comment]
This item will be covered in issues #1110 , #1121 , thus this is a duplicate but will be referenced.
