### ISSUE TITLE
[Enabler] [zos_data_set, zos_copy] Refactor calls to use new alias and execute options

### ISSUE THREAD

**Issue by storfibm** [ansible-collections/ibm_zos_core#944]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Ansible module

zos_data_set, zos_copy

### Enabler description

ZOAU delivered alias support in 1.2.4, but the requisite Python code was missing. The feature was implemented for AC 1.8, but relied on direct option invocation (backup method). The z/OS Core Collection should refactor to use the new Python arguments.

**Acceptance Criteria**
Given the z/OS Core Collection
When alias support for data set copy operations is driven
Then the underlying new `alias` and `execute` flags are utilized

**Requirements**
-Integrate new `alias` and `execute` arguments for datasets.copy() operations
-Dependency on ZOAU 1.2.5

Additional context
https://jsw.ibm.com/browse/NAZARE-9807

**Comment by ddimatos** [comment]
It should be noted that the module `zos_data_set` had no such calls so I will remove it from the title.
