### ISSUE TITLE
[Enabler] [zos_data_set] Ensure module can process GDG data sets internally

### ISSUE THREAD

**Issue by storfibm** [ansible-collections/ibm_zos_core#947]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Ansible module

zos_data_set

### Enabler description

ZOAU is working on an initiative to support GDG data sets. `dls` and `datasets.listing()` are targeted for an initial rollout. The z/OS Core Collection should add this support for GDG by driving the new capabilities in ZOAU.

**Acceptance Criteria**
Given the z/OS Core Collection
When a interacts with GDG data sets
Then zos_data_set can internally process listing attributes for such data sets

**Requirements**
-Ability to process GDG data sets and their attributes
-Support `datasets.listing()` for relative data set names, e.g. MY.DATA.SET(x)
-Include considerations in #935 to target last, current and next GDG data sets
-New test cases for all potential variations
-Dependency on ZOAU 1.3

**Additional context**
https://jsw.ibm.com/browse/NAZARE-9618

**Comment by ddimatos** [comment]
This is a duplicate to https://github.com/ansible-collections/ibm_zos_core/issues/1371 , issue 1371 is part of the epic https://github.com/ansible-collections/ibm_zos_core/issues/1366 and will be used to track the work GDG support for this module.
