### ISSUE TITLE
[Enabler] Validate version check behavior for new ZOAU release code names

### ISSUE THREAD

**Issue by storfibm** [ansible-collections/ibm_zos_core#949]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

ZOAU is reworking the `zoaversion` output and including a new release name within brackets. The z/OS Core Collection should validate that this output change will not break any existing version checks.

**Acceptance Criteria**
Given the z/OS Core Collection
When a user has ZOAU 1.2.5 and later installed
Then modules can still perform underlying version checks

**Requirements**
-Allow version checks to perform as before
-Dependency on ZOAU 1.2.5

**Additional context**
https://jsw.ibm.com/browse/NAZARE-10077

**Comment by richp405** [comment]
I have 2 answers (well, 1 pending).

1: Ketan's module works fine with 1.2.3, 1.2.4, 1.2.4.2 and 1.2.5.0... 
2: My use of the lib/__init__ module does not work on 1.2.5.0, and I think the file may be discontinued.  I've asked zoau team, and can switch to using the zoau_version_checker.py utility if that is the case.

Methodology: I took the plugins/module_utils/zoau_version_checker, and added runcode at the bottom, and ran it using the pythonpath and environment variables to change the active version.

Added: 

vl = get_zoau_version_str()
print( vl )

gt2 = is_zoau_version_higher_than('1.2.6')
gt3 = is_zoau_version_higher_than('1.2.5')
gt4 = is_zoau_version_higher_than('1.2.4')
gt5 = is_zoau_version_higher_than('1.2.3')

print( "higher than: 6:{}, 5:{}, 4:{}, 3:{}".format(gt2,gt3,gt4,gt5) )

Got the expected output for each permutation, both as the version array, and the is_higher... response.

Once I hear back, I'll change the code in the other section (module_utils/job.py) if appropriate.

**Comment by richp405** [comment]
Zoau team is addressing the __init__ issue, so no changes are needed here.  The 2 version checkers can both continue to exist.
