### ISSUE TITLE
[Enabler] Ensure modules work with new ZOAU JSON schema - Phase 1

### ISSUE THREAD

**Issue by storfibm** [ansible-collections/ibm_zos_core#954]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

Phase 1 - ZOAU is reworking the JSON schema to be consistent across all utilities in multiple phases. The z/OS Core Collection should validate that this output change will not break any existing operations. Initially, it involves a new nested `data {}` object that will encapsulate the prior output. More meta data will be added in the future to utilities that had legacy JSON output, which should not immediately affect the z/OS Core Collection.

**Acceptance Criteria**
Given the z/OS Core Collection
When a user has ZOAU 1.3 and later installed
Then modules can still process legacy JSON output provided in the new ZOAU 1.3 schema

**Requirements**
-Ensure existing module functionality can continue to function
-Dependency on ZOAU 1.3
-Phase 1 utilitie changes only
-Validate: dmod, dsed, apfadm, zinfo and requisite Python API methods

**Additional context**
NAZARE-10086

**Comment by richp405** [comment]
I think we could do what we did for 1.2.3 versus 1.2.4: if we see a later number, expect the harmonized return.  Ketan and I have both done this for some job-query related stuff... this could be a variation on that theme.

**Comment by richp405** [comment]
Phase 1 is listed in  box 1267411252628

**Comment by ddimatos** [comment]
@richp405 regarding using conditional programming to support back levels , eg 1.2.x I don't think this is necessary for IBM z/OS Core 1.10.0-beta.1, this version will raise the minimum supported zoau to 1.3 and alleviate that need. There are too many breaking changes in zoau 1.3 that would be difficult to maintain backwards compatibility.

**Comment by ddimatos** [comment]
This work is already covered in the issues belonging to epic #931 , those issues have a reference back to this issue, thus this is no longer needed and will be cancelled.
