### ISSUE TITLE
[Enabler] Understand ansible-core changes returning a UTF-8 warning

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#984]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

As part of collaboration #983 this issue is to understand the ansible-core code changes historically, meaning find the commits and PRs associated to this change such this should provide the knowledge needed to asses the root cause behind the warning.

**Comment by ketankelkar** [comment]
found this config, which gets rid of 1 of the 2 warning messages: [ANSIBLE_MODULE_STRICT_UTF8_RESPONSE](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#envvar-ANSIBLE_MODULE_STRICT_UTF8_RESPONSE)

There is a note in the config doc there that says "Only ansible-core should evaluate this configuration"

before:


![Image](https://github.com/ansible-collections/ibm_zos_core/assets/10567394/a8bba04a-e20c-443f-b515-7aaa2b17fb93)


after:


![Image](https://github.com/ansible-collections/ibm_zos_core/assets/10567394/6e3ab1e6-703b-47f3-b306-005c959afba9)


config was activated in the command line: 
```bash
ANSIBLE_MODULE_STRICT_UTF8_RESPONSE=0 ansible-playbook -i ~/inventory.yml recreate-utf8-warning.yml 
```

**Comment by ketankelkar** [comment]
here is a link to the specific commit where this message was introduced into the code base -- note the date of the commit is only 7 months prior to today

https://github.com/ansible/ansible/commit/0ee7cfb128a62362c015b2235633615542572dbc

**Comment by ketankelkar** [comment]
Found a note in the above commit -- it is the responsibility of modules to ensure they don't return non-UTF8 data, or if necessary, to return it as base64 binary data. The note was added to the module development guide ([here](https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_best_practices.html#creating-correct-and-informative-module-output)).

>* Module return data must be encoded as strict UTF-8. Modules that cannot return UTF-8 encoded data should return the data encoded by something such as base64. Optionally modules can make the determination if they can encode as UTF-8 and utilize ``errors='replace'`` to replace non UTF-8 characters making the return values lossy.
