### ISSUE TITLE
[Enabler] Determine the modules impacted by the UTF-8 warning

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#986]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description
This is part of collaboration #983.
Determine which modules are impacted (maybe not every module), have a good understanding which `ibm_zos_core` modules are impacted and if some of the community modules are impacted.

**Comment by ddimatos** [comment]
This issue doubled in size, 5 pts were allocated to Q1, the remaining 5 for Q2 and the issue is now being put in Q2.

**Comment by ketankelkar** [comment]
For ibm_zos_core modules, I’ve primarily seen the warning crop up when the output from the result is printed (via debug module). Perhaps we need a cleanup/normalization routine in the ibm_zos_core collection any time data is added to the result. That being said, no particular ibm_zos_core module stood out as safe/unaffected by this deprecation warning.

These modules directly read or write content to z/OS and if any of the content contains a non-utf-8 char, the depr error will be raised:

- zos_blockinfile
- zos_find
- zos_job_submit, query, output
- zos_lineinfile
- zos_mvs_raw
- zos_operator
- zos_operator_action_query
- zos_tso_command
- zos_volume_init


These modules return file or data set names in the result, and any name containing a non-utf-8 char will raise the deprecation warning:

- zos_archive
- zos_backup_restore
- zos_blockinfile
- zos_copy
- zos_data_set
- zos_encode
- zos_fetch
- zos_lineinfile
- zos_mount
- zos_unarchive


These modules I am unsure about with regards to the deprecation warning:

- zos_apf
- zos_encode
- zos_gather_facts
- zos_ping
- zos_script


Note- I do not have recreates for each of these modules, but I have recreated the deprecation warning a number of ways with various modules and have noticed the pattern mentioned earlier
