### ISSUE TITLE
[Enabler] Implement the solution for the UTF-8 warning

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#988]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

This is part of collaboration #983.
 Implement the proposed solution for the UTF-8 warning.

**Comment by ketankelkar** [comment]
The vetting process of #987 has involved making changes to the code and developing/running playbooks, so the bulk of this task here will be running the pipelines and making any required changes (likely to test cases)
